INSERT INTO biome (id, name, image, description, dimension_id) VALUES
(1, 'Cherry Grove', '/biomes/minecraft_cherry_grove.png', 'The Cherry Grove biome', 2),
(2, 'Birch Forest', '/biomes/minecraft_birch_forest.png', 'The Birch Forest biome', 2),
(3, 'Savanna Plateau', '/biomes/minecraft_savanna_plateau.png', 'The Savanna Plateau biome', 2),
(4, 'Snowy Plains', '/biomes/minecraft_snowy_plains.png', 'The Snowy Plains biome', 2),
(5, 'End Highlands', '/biomes/minecraft_end_highlands.png', 'The End Highlands biome', 3),
(6, 'Deep Cold Ocean', '/biomes/minecraft_deep_cold_ocean.png', 'The Deep Cold Ocean biome', 2),
(7, 'Sparse Jungle', '/biomes/minecraft_sparse_jungle.png', 'The Sparse Jungle biome', 2),
(8, 'Windswept Gravelly Hills', '/biomes/minecraft_windswept_gravelly_hills.png', 'The Windswept Gravelly Hills biome', 2),
(9, 'Forest', '/biomes/minecraft_forest.png', 'The Forest biome', 2),
(10, 'Stony Shore', '/biomes/minecraft_stony_shore.png', 'The Stony Shore biome', 2),
(11, 'Deep Frozen Ocean', '/biomes/minecraft_deep_frozen_ocean.png', 'The Deep Frozen Ocean biome', 2),
(12, 'Jungle', '/biomes/minecraft_jungle.png', 'The Jungle biome', 2),
(13, 'Warm Ocean', '/biomes/minecraft_warm_ocean.png', 'The Warm Ocean biome', 2),
(14, 'Old Growth Birch Forest', '/biomes/minecraft_old_growth_birch_forest.png', 'The Old Growth Birch Forest biome', 2),
(15, 'Snowy Beach', '/biomes/minecraft_snowy_beach.png', 'The Snowy Beach biome', 2),
(16, 'Ocean', '/biomes/minecraft_ocean.png', 'The Ocean biome', 2),
(17, 'Mushroom Fields', '/biomes/minecraft_mushroom_fields.png', 'The Mushroom Fields biome', 2),
(18, 'Snowy Slopes', '/biomes/minecraft_snowy_slopes.png', 'The Snowy Slopes biome', 2),
(19, 'Cold Ocean', '/biomes/minecraft_cold_ocean.png', 'The Cold Ocean biome', 2),
(20, 'Frozen Ocean', '/biomes/minecraft_frozen_ocean.png', 'The Frozen Ocean biome', 2),
(21, 'Small End Islands', '/biomes/minecraft_small_end_islands.png', 'The Small End Islands biome', 3),
(22, 'Swamp', '/biomes/minecraft_swamp.png', 'The Swamp biome', 2),
(23, 'Deep Dark', '/biomes/minecraft_deep_dark.png', 'The Deep Dark biome', 2),
(24, 'Deep Ocean', '/biomes/minecraft_deep_ocean.png', 'The Deep Ocean biome', 2),
(25, 'Taiga', '/biomes/minecraft_taiga.png', 'The Taiga biome', 2),
(26, 'Lukewarm Ocean', '/biomes/minecraft_lukewarm_ocean.png', 'The Lukewarm Ocean biome', 2),
(27, 'Mangrove Swamp', '/biomes/minecraft_mangrove_swamp.png', 'The Mangrove Swamp biome', 2),
(28, 'Ice Spikes', '/biomes/minecraft_ice_spikes.png', 'The Ice Spikes biome', 2),
(29, 'Nether Wastes', '/biomes/minecraft_nether_wastes.png', 'The Nether Wastes biome', 4),
(30, 'Old Growth Pine Taiga', '/biomes/minecraft_old_growth_pine_taiga.png', 'The Old Growth Pine Taiga biome', 2),
(31, 'Meadow', '/biomes/minecraft_meadow.png', 'The Meadow biome', 2),
(32, 'Eroded Badlands', '/biomes/minecraft_eroded_badlands.png', 'The Eroded Badlands biome', 2),
(33, 'Grove', '/biomes/minecraft_grove.png', 'The Grove biome', 2),
(34, 'Plains', '/biomes/minecraft_plains.png', 'The Plains biome', 2),
(35, 'Snowy Taiga', '/biomes/minecraft_snowy_taiga.png', 'The Snowy Taiga biome', 2),
(36, 'Deep Lukewarm Ocean', '/biomes/minecraft_deep_lukewarm_ocean.png', 'The Deep Lukewarm Ocean biome', 2),
(37, 'Badlands', '/biomes/minecraft_badlands.png', 'The Badlands biome', 2),
(38, 'Jagged Peaks', '/biomes/minecraft_jagged_peaks.png', 'The Jagged Peaks biome', 2),
(39, 'Sunflower Plains', '/biomes/minecraft_sunflower_plains.png', 'The Sunflower Plains biome', 2),
(40, 'Stony Peaks', '/biomes/minecraft_stony_peaks.png', 'The Stony Peaks biome', 2),
(41, 'Warped Forest', '/biomes/minecraft_warped_forest.png', 'The Warped Forest biome', 4),
(42, 'Wooded Badlands', '/biomes/minecraft_wooded_badlands.png', 'The Wooded Badlands biome', 2),
(43, 'Windswept Forest', '/biomes/minecraft_windswept_forest.png', 'The Windswept Forest biome', 2),
(44, 'River', '/biomes/minecraft_river.png', 'The River biome', 2),
(45, 'Savanna', '/biomes/minecraft_savanna.png', 'The Savanna biome', 2),
(46, 'End Barrens', '/biomes/minecraft_end_barrens.png', 'The End Barrens biome', 3),
(47, 'The Void', '/biomes/minecraft_the_void.png', 'The The Void biome', 5),
(48, 'Beach', '/biomes/minecraft_beach.png', 'The Beach biome', 2),
(49, 'Crimson Forest', '/biomes/minecraft_crimson_forest.png', 'The Crimson Forest biome', 4),
(50, 'Basalt Deltas', '/biomes/minecraft_basalt_deltas.png', 'The Basalt Deltas biome', 4),
(51, 'Windswept Savanna', '/biomes/minecraft_windswept_savanna.png', 'The Windswept Savanna biome', 2),
(52, 'The End', '/biomes/minecraft_the_end.png', 'The The End biome', 3),
(53, 'Soul Sand Valley', '/biomes/minecraft_soul_sand_valley.png', 'The Soul Sand Valley biome', 4),
(54, 'Dark Forest', '/biomes/minecraft_dark_forest.png', 'The Dark Forest biome', 2),
(55, 'Windswept Hills', '/biomes/minecraft_windswept_hills.png', 'The Windswept Hills biome', 2),
(56, 'Dripstone Caves', '/biomes/minecraft_dripstone_caves.png', 'The Dripstone Caves biome', 2),
(57, 'Frozen River', '/biomes/minecraft_frozen_river.png', 'The Frozen River biome', 2),
(58, 'Desert', '/biomes/minecraft_desert.png', 'The Desert biome', 2),
(59, 'Bamboo Jungle', '/biomes/minecraft_bamboo_jungle.png', 'The Bamboo Jungle biome', 2),
(60, 'Flower Forest', '/biomes/minecraft_flower_forest.png', 'The Flower Forest biome', 2),
(61, 'Lush Caves', '/biomes/minecraft_lush_caves.png', 'The Lush Caves biome', 2),
(62, 'Old Growth Spruce Taiga', '/biomes/minecraft_old_growth_spruce_taiga.png', 'The Old Growth Spruce Taiga biome', 2),
(63, 'End Midlands', '/biomes/minecraft_end_midlands.png', 'The End Midlands biome', 3),
(64, 'Frozen Peaks', '/biomes/minecraft_frozen_peaks.png', 'The Frozen Peaks biome', 2);
