INSERT INTO item (id, name, image) VALUES 
(1, 'Dropper', '/items/minecraft_dropper.png'),
(2, 'Cobblestone', '/items/minecraft_cobblestone.png'),
(3, 'Redstone', '/items/minecraft_redstone.png'),
(4, 'Jungle Fence Gate', '/items/minecraft_jungle_fence_gate.png'),
(5, 'Stick', '/items/minecraft_stick.png'),
(6, 'Jungle Planks', '/items/minecraft_jungle_planks.png'),
(7, 'Stone Pressure Plate', '/items/minecraft_stone_pressure_plate.png'),
(8, 'Stone', '/items/minecraft_stone.png'),
(9, 'Bamboo Block', '/items/minecraft_bamboo_block.png'),
(10, 'Bamboo', '/items/minecraft_bamboo.png'),
(11, 'Cooked Porkchop', '/items/minecraft_cooked_porkchop.png'),
(12, 'Porkchop', '/items/minecraft_porkchop.png'),
(13, 'Polished Deepslate', '/items/minecraft_polished_deepslate.png'),
(14, 'Cobbled Deepslate', '/items/minecraft_cobbled_deepslate.png'),
(15, 'Pink Bed', '/items/minecraft_pink_bed.png'),
(16, 'Pink Dye', '/items/minecraft_pink_dye.png'),
(17, 'Black Bed', '/items/minecraft_black_bed.png'),
(18, 'Blue Bed', '/items/minecraft_blue_bed.png'),
(19, 'Brown Bed', '/items/minecraft_brown_bed.png'),
(20, 'Cyan Bed', '/items/minecraft_cyan_bed.png'),
(21, 'Gray Bed', '/items/minecraft_gray_bed.png'),
(22, 'Green Bed', '/items/minecraft_green_bed.png'),
(23, 'Light Blue Bed', '/items/minecraft_light_blue_bed.png'),
(24, 'Light Gray Bed', '/items/minecraft_light_gray_bed.png'),
(25, 'Lime Bed', '/items/minecraft_lime_bed.png'),
(26, 'Magenta Bed', '/items/minecraft_magenta_bed.png'),
(27, 'Orange Bed', '/items/minecraft_orange_bed.png'),
(28, 'Purple Bed', '/items/minecraft_purple_bed.png'),
(29, 'Red Bed', '/items/minecraft_red_bed.png'),
(30, 'Yellow Bed', '/items/minecraft_yellow_bed.png'),
(31, 'White Bed', '/items/minecraft_white_bed.png'),
(32, 'Dune Armor Trim Smithing Template', '/items/minecraft_dune_armor_trim_smithing_template.png'),
(33, 'Diamond', '/items/minecraft_diamond.png'),
(34, 'Sandstone', '/items/minecraft_sandstone.png'),
(35, 'Diorite Stairs', '/items/minecraft_diorite_stairs.png'),
(36, 'Diorite', '/items/minecraft_diorite.png'),
(37, 'Acacia Door', '/items/minecraft_acacia_door.png'),
(38, 'Acacia Planks', '/items/minecraft_acacia_planks.png'),
(39, 'Spruce Slab', '/items/minecraft_spruce_slab.png'),
(40, 'Spruce Planks', '/items/minecraft_spruce_planks.png'),
(41, 'Cracked Deepslate Bricks', '/items/minecraft_cracked_deepslate_bricks.png'),
(42, 'Deepslate Bricks', '/items/minecraft_deepslate_bricks.png'),
(43, 'Gray Terracotta', '/items/minecraft_gray_terracotta.png'),
(44, 'Terracotta', '/items/minecraft_terracotta.png'),
(45, 'Gray Dye', '/items/minecraft_gray_dye.png'),
(46, 'End Stone Brick Slab', '/items/minecraft_end_stone_brick_slab.png'),
(47, 'End Stone', '/items/minecraft_end_stone.png'),
(48, 'Red Glazed Terracotta', '/items/minecraft_red_glazed_terracotta.png'),
(49, 'Red Terracotta', '/items/minecraft_red_terracotta.png'),
(50, 'Gold Ingot', '/items/minecraft_gold_ingot.png'),
(51, 'Gold Ore', '/items/minecraft_gold_ore.png'),
(52, 'Cobbled Deepslate Stairs', '/items/minecraft_cobbled_deepslate_stairs.png'),
(53, 'Cobbled Deepslate Wall', '/items/minecraft_cobbled_deepslate_wall.png'),
(54, 'Smooth Red Sandstone Slab', '/items/minecraft_smooth_red_sandstone_slab.png'),
(55, 'Smooth Red Sandstone', '/items/minecraft_smooth_red_sandstone.png'),
(56, 'Brown Concrete Powder', '/items/minecraft_brown_concrete_powder.png'),
(57, 'Brown Dye', '/items/minecraft_brown_dye.png'),
(58, 'Sand', '/items/minecraft_sand.png'),
(59, 'Gravel', '/items/minecraft_gravel.png'),
(60, 'Pink Terracotta', '/items/minecraft_pink_terracotta.png'),
(61, 'Smooth Basalt', '/items/minecraft_smooth_basalt.png'),
(62, 'Basalt', '/items/minecraft_basalt.png'),
(63, 'Furnace Minecart', '/items/minecraft_furnace_minecart.png'),
(64, 'Furnace', '/items/minecraft_furnace.png'),
(65, 'Minecart', '/items/minecraft_minecart.png'),
(66, 'Dark Oak Planks', '/items/minecraft_dark_oak_planks.png'),
(67, 'Deepslate Tile Stairs', '/items/minecraft_deepslate_tile_stairs.png'),
(68, 'Bucket', '/items/minecraft_bucket.png'),
(69, 'Iron Ingot', '/items/minecraft_iron_ingot.png'),
(70, 'Blue Stained Glass Pane', '/items/minecraft_blue_stained_glass_pane.png'),
(71, 'Blue Stained Glass', '/items/minecraft_blue_stained_glass.png'),
(72, 'Lime Dye', '/items/minecraft_lime_dye.png'),
(73, 'Sea Pickle', '/items/minecraft_sea_pickle.png'),
(74, 'Cobbled Deepslate Slab', '/items/minecraft_cobbled_deepslate_slab.png'),
(75, 'Beehive', '/items/minecraft_beehive.png'),
(76, 'Honeycomb', '/items/minecraft_honeycomb.png'),
(77, 'Campfire', '/items/minecraft_campfire.png'),
(78, 'Lime Wool', '/items/minecraft_lime_wool.png'),
(79, 'Black Wool', '/items/minecraft_black_wool.png'),
(80, 'Blue Wool', '/items/minecraft_blue_wool.png'),
(81, 'Brown Wool', '/items/minecraft_brown_wool.png'),
(82, 'Cyan Wool', '/items/minecraft_cyan_wool.png'),
(83, 'Gray Wool', '/items/minecraft_gray_wool.png'),
(84, 'Green Wool', '/items/minecraft_green_wool.png'),
(85, 'Light Blue Wool', '/items/minecraft_light_blue_wool.png'),
(86, 'Light Gray Wool', '/items/minecraft_light_gray_wool.png'),
(87, 'Magenta Wool', '/items/minecraft_magenta_wool.png'),
(88, 'Orange Wool', '/items/minecraft_orange_wool.png'),
(89, 'Pink Wool', '/items/minecraft_pink_wool.png'),
(90, 'Purple Wool', '/items/minecraft_purple_wool.png'),
(91, 'Red Wool', '/items/minecraft_red_wool.png'),
(92, 'Yellow Wool', '/items/minecraft_yellow_wool.png'),
(93, 'White Wool', '/items/minecraft_white_wool.png'),
(94, 'White Terracotta', '/items/minecraft_white_terracotta.png'),
(95, 'White Dye', '/items/minecraft_white_dye.png'),
(96, 'Chiseled Red Sandstone', '/items/minecraft_chiseled_red_sandstone.png'),
(97, 'Red Sandstone Slab', '/items/minecraft_red_sandstone_slab.png'),
(98, 'White Banner', '/items/minecraft_white_banner.png'),
(99, 'Light Gray Stained Glass Pane', '/items/minecraft_light_gray_stained_glass_pane.png'),
(100, 'Glass Pane', '/items/minecraft_glass_pane.png'),
(101, 'Light Gray Dye', '/items/minecraft_light_gray_dye.png'),
(102, 'Powered Rail', '/items/minecraft_powered_rail.png'),
(103, 'Waxed Oxidized Copper', '/items/minecraft_waxed_oxidized_copper.png'),
(104, 'Oxidized Copper', '/items/minecraft_oxidized_copper.png'),
(105, 'Oak Wood', '/items/minecraft_oak_wood.png'),
(106, 'Oak Log', '/items/minecraft_oak_log.png'),
(107, 'Red Dye', '/items/minecraft_red_dye.png'),
(108, 'Lapis Block', '/items/minecraft_lapis_block.png'),
(109, 'Lapis Lazuli', '/items/minecraft_lapis_lazuli.png'),
(110, 'Blackstone Stairs', '/items/minecraft_blackstone_stairs.png'),
(111, 'Blackstone', '/items/minecraft_blackstone.png'),
(112, 'Honey Bottle', '/items/minecraft_honey_bottle.png'),
(113, 'Honey Block', '/items/minecraft_honey_block.png'),
(114, 'Glass Bottle', '/items/minecraft_glass_bottle.png'),
(115, 'Blue Dye', '/items/minecraft_blue_dye.png'),
(116, 'Brown Terracotta', '/items/minecraft_brown_terracotta.png'),
(117, 'Cobblestone Wall', '/items/minecraft_cobblestone_wall.png'),
(118, 'Cauldron', '/items/minecraft_cauldron.png'),
(119, 'Cut Copper Stairs', '/items/minecraft_cut_copper_stairs.png'),
(120, 'Cut Copper', '/items/minecraft_cut_copper.png'),
(121, 'Oak Fence Gate', '/items/minecraft_oak_fence_gate.png'),
(122, 'Oak Planks', '/items/minecraft_oak_planks.png'),
(123, 'Blue Terracotta', '/items/minecraft_blue_terracotta.png'),
(124, 'Deepslate Gold Ore', '/items/minecraft_deepslate_gold_ore.png'),
(125, 'Red Sandstone Wall', '/items/minecraft_red_sandstone_wall.png'),
(126, 'Red Sandstone', '/items/minecraft_red_sandstone.png'),
(127, 'Stone Shovel', '/items/minecraft_stone_shovel.png'),
(128, 'Packed Mud', '/items/minecraft_packed_mud.png'),
(129, 'Mud', '/items/minecraft_mud.png'),
(130, 'Wheat', '/items/minecraft_wheat.png'),
(131, 'Glass', '/items/minecraft_glass.png'),
(132, 'Gold Nugget', '/items/minecraft_gold_nugget.png'),
(133, 'Jungle Stairs', '/items/minecraft_jungle_stairs.png'),
(134, 'Spruce Stairs', '/items/minecraft_spruce_stairs.png'),
(135, 'Polished Blackstone Slab', '/items/minecraft_polished_blackstone_slab.png'),
(136, 'Spruce Fence Gate', '/items/minecraft_spruce_fence_gate.png'),
(137, 'Polished Blackstone Stairs', '/items/minecraft_polished_blackstone_stairs.png'),
(138, 'Polished Blackstone', '/items/minecraft_polished_blackstone.png'),
(139, 'Oxeye Daisy', '/items/minecraft_oxeye_daisy.png'),
(140, 'Leather Chestplate', '/items/minecraft_leather_chestplate.png'),
(141, 'Leather', '/items/minecraft_leather.png'),
(142, 'Golden Carrot', '/items/minecraft_golden_carrot.png'),
(143, 'Carrot', '/items/minecraft_carrot.png'),
(144, 'Smooth Quartz Slab', '/items/minecraft_smooth_quartz_slab.png'),
(145, 'Smooth Quartz', '/items/minecraft_smooth_quartz.png'),
(146, 'Oxidized Cut Copper Slab', '/items/minecraft_oxidized_cut_copper_slab.png'),
(147, 'Oxidized Cut Copper', '/items/minecraft_oxidized_cut_copper.png'),
(148, 'Magenta Glazed Terracotta', '/items/minecraft_magenta_glazed_terracotta.png'),
(149, 'Magenta Terracotta', '/items/minecraft_magenta_terracotta.png'),
(150, 'Deepslate Brick Wall', '/items/minecraft_deepslate_brick_wall.png'),
(151, 'Fletching Table', '/items/minecraft_fletching_table.png'),
(152, 'Flint', '/items/minecraft_flint.png'),
(153, 'Glow Item Frame', '/items/minecraft_glow_item_frame.png'),
(154, 'Item Frame', '/items/minecraft_item_frame.png'),
(155, 'Glow Ink Sac', '/items/minecraft_glow_ink_sac.png'),
(156, 'Stripped Dark Oak Wood', '/items/minecraft_stripped_dark_oak_wood.png'),
(157, 'Stripped Dark Oak Log', '/items/minecraft_stripped_dark_oak_log.png'),
(158, 'Stone Bricks', '/items/minecraft_stone_bricks.png'),
(159, 'Deepslate Brick Stairs', '/items/minecraft_deepslate_brick_stairs.png'),
(160, 'Brick Wall', '/items/minecraft_brick_wall.png'),
(161, 'Bricks', '/items/minecraft_bricks.png'),
(162, 'Redstone Lamp', '/items/minecraft_redstone_lamp.png'),
(163, 'Glowstone', '/items/minecraft_glowstone.png'),
(164, 'Brown Banner', '/items/minecraft_brown_banner.png'),
(165, 'Light Gray Stained Glass', '/items/minecraft_light_gray_stained_glass.png'),
(166, 'Blue Banner', '/items/minecraft_blue_banner.png'),
(167, 'Crimson Door', '/items/minecraft_crimson_door.png'),
(168, 'Crimson Planks', '/items/minecraft_crimson_planks.png'),
(169, 'Clock', '/items/minecraft_clock.png'),
(170, 'Light Blue Banner', '/items/minecraft_light_blue_banner.png'),
(171, 'Purpur Block', '/items/minecraft_purpur_block.png'),
(172, 'Popped Chorus Fruit', '/items/minecraft_popped_chorus_fruit.png'),
(173, 'Cut Red Sandstone', '/items/minecraft_cut_red_sandstone.png'),
(174, 'Sandstone Wall', '/items/minecraft_sandstone_wall.png'),
(175, 'Warped Hyphae', '/items/minecraft_warped_hyphae.png'),
(176, 'Warped Stem', '/items/minecraft_warped_stem.png'),
(177, 'Waxed Oxidized Cut Copper', '/items/minecraft_waxed_oxidized_cut_copper.png'),
(178, 'Diorite Slab', '/items/minecraft_diorite_slab.png'),
(179, 'Green Dye', '/items/minecraft_green_dye.png'),
(180, 'Mossy Stone Bricks', '/items/minecraft_mossy_stone_bricks.png'),
(181, 'Moss Block', '/items/minecraft_moss_block.png'),
(182, 'Mangrove Hanging Sign', '/items/minecraft_mangrove_hanging_sign.png'),
(183, 'Stripped Mangrove Log', '/items/minecraft_stripped_mangrove_log.png'),
(184, 'Chain', '/items/minecraft_chain.png'),
(185, 'Cooked Chicken', '/items/minecraft_cooked_chicken.png'),
(186, 'Chicken', '/items/minecraft_chicken.png'),
(187, 'Waxed Exposed Copper', '/items/minecraft_waxed_exposed_copper.png'),
(188, 'Exposed Copper', '/items/minecraft_exposed_copper.png'),
(189, 'Wayfinder Armor Trim Smithing Template', '/items/minecraft_wayfinder_armor_trim_smithing_template.png'),
(190, 'Waxed Exposed Cut Copper Slab', '/items/minecraft_waxed_exposed_cut_copper_slab.png'),
(191, 'Waxed Exposed Cut Copper', '/items/minecraft_waxed_exposed_cut_copper.png'),
(192, 'Baked Potato', '/items/minecraft_baked_potato.png'),
(193, 'Potato', '/items/minecraft_potato.png'),
(194, 'Sugar', '/items/minecraft_sugar.png'),
(195, 'Observer', '/items/minecraft_observer.png'),
(196, 'Quartz', '/items/minecraft_quartz.png'),
(197, 'Pink Banner', '/items/minecraft_pink_banner.png'),
(198, 'Waxed Oxidized Cut Copper Slab', '/items/minecraft_waxed_oxidized_cut_copper_slab.png'),
(199, 'Smooth Sandstone', '/items/minecraft_smooth_sandstone.png'),
(200, 'Dark Oak Trapdoor', '/items/minecraft_dark_oak_trapdoor.png'),
(201, 'Redstone Ore', '/items/minecraft_redstone_ore.png'),
(202, 'Iron Ore', '/items/minecraft_iron_ore.png'),
(203, 'Purple Dye', '/items/minecraft_purple_dye.png'),
(204, 'Waxed Weathered Cut Copper Stairs', '/items/minecraft_waxed_weathered_cut_copper_stairs.png'),
(205, 'Waxed Weathered Copper', '/items/minecraft_waxed_weathered_copper.png'),
(206, 'Candle', '/items/minecraft_candle.png'),
(207, 'String', '/items/minecraft_string.png'),
(208, 'Lantern', '/items/minecraft_lantern.png'),
(209, 'Torch', '/items/minecraft_torch.png'),
(210, 'Iron Nugget', '/items/minecraft_iron_nugget.png'),
(211, 'Polished Granite Stairs', '/items/minecraft_polished_granite_stairs.png'),
(212, 'Polished Granite', '/items/minecraft_polished_granite.png'),
(213, 'Waxed Weathered Cut Copper', '/items/minecraft_waxed_weathered_cut_copper.png'),
(214, 'Mossy Cobblestone Wall', '/items/minecraft_mossy_cobblestone_wall.png'),
(215, 'Mossy Cobblestone', '/items/minecraft_mossy_cobblestone.png'),
(216, 'Light Weighted Pressure Plate', '/items/minecraft_light_weighted_pressure_plate.png'),
(217, 'Green Terracotta', '/items/minecraft_green_terracotta.png'),
(218, 'Cracked Nether Bricks', '/items/minecraft_cracked_nether_bricks.png'),
(219, 'Nether Bricks', '/items/minecraft_nether_bricks.png'),
(220, 'Mossy Cobblestone Stairs', '/items/minecraft_mossy_cobblestone_stairs.png'),
(221, 'Cherry Fence', '/items/minecraft_cherry_fence.png'),
(222, 'Cherry Planks', '/items/minecraft_cherry_planks.png'),
(223, 'Polished Deepslate Stairs', '/items/minecraft_polished_deepslate_stairs.png'),
(224, 'Slime Ball', '/items/minecraft_slime_ball.png'),
(225, 'Slime Block', '/items/minecraft_slime_block.png'),
(226, 'Iron Block', '/items/minecraft_iron_block.png'),
(227, 'Birch Pressure Plate', '/items/minecraft_birch_pressure_plate.png'),
(228, 'Birch Planks', '/items/minecraft_birch_planks.png'),
(229, 'Hopper Minecart', '/items/minecraft_hopper_minecart.png'),
(230, 'Hopper', '/items/minecraft_hopper.png'),
(231, 'Copper Block', '/items/minecraft_copper_block.png'),
(232, 'Copper Ingot', '/items/minecraft_copper_ingot.png'),
(233, 'Nether Brick Slab', '/items/minecraft_nether_brick_slab.png'),
(234, 'End Crystal', '/items/minecraft_end_crystal.png'),
(235, 'Ender Eye', '/items/minecraft_ender_eye.png'),
(236, 'Ghast Tear', '/items/minecraft_ghast_tear.png'),
(237, 'Acacia Boat', '/items/minecraft_acacia_boat.png'),
(238, 'Weathered Cut Copper', '/items/minecraft_weathered_cut_copper.png'),
(239, 'Weathered Copper', '/items/minecraft_weathered_copper.png'),
(240, 'Oak Sign', '/items/minecraft_oak_sign.png'),
(241, 'Polished Blackstone Brick Slab', '/items/minecraft_polished_blackstone_brick_slab.png'),
(242, 'Cyan Carpet', '/items/minecraft_cyan_carpet.png'),
(243, 'Cyan Dye', '/items/minecraft_cyan_dye.png'),
(244, 'Black Carpet', '/items/minecraft_black_carpet.png'),
(245, 'Blue Carpet', '/items/minecraft_blue_carpet.png'),
(246, 'Brown Carpet', '/items/minecraft_brown_carpet.png'),
(247, 'Gray Carpet', '/items/minecraft_gray_carpet.png'),
(248, 'Green Carpet', '/items/minecraft_green_carpet.png'),
(249, 'Light Blue Carpet', '/items/minecraft_light_blue_carpet.png'),
(250, 'Light Gray Carpet', '/items/minecraft_light_gray_carpet.png'),
(251, 'Lime Carpet', '/items/minecraft_lime_carpet.png'),
(252, 'Magenta Carpet', '/items/minecraft_magenta_carpet.png'),
(253, 'Orange Carpet', '/items/minecraft_orange_carpet.png'),
(254, 'Pink Carpet', '/items/minecraft_pink_carpet.png'),
(255, 'Purple Carpet', '/items/minecraft_purple_carpet.png'),
(256, 'Red Carpet', '/items/minecraft_red_carpet.png'),
(257, 'Yellow Carpet', '/items/minecraft_yellow_carpet.png'),
(258, 'White Carpet', '/items/minecraft_white_carpet.png'),
(259, 'Yellow Concrete Powder', '/items/minecraft_yellow_concrete_powder.png'),
(260, 'Yellow Dye', '/items/minecraft_yellow_dye.png'),
(261, 'Diamond Sword', '/items/minecraft_diamond_sword.png'),
(262, 'Mossy Cobblestone Slab', '/items/minecraft_mossy_cobblestone_slab.png'),
(263, 'Waxed Cut Copper Stairs', '/items/minecraft_waxed_cut_copper_stairs.png'),
(264, 'Coarse Dirt', '/items/minecraft_coarse_dirt.png'),
(265, 'Dirt', '/items/minecraft_dirt.png'),
(266, 'Warped Fence', '/items/minecraft_warped_fence.png'),
(267, 'Warped Planks', '/items/minecraft_warped_planks.png'),
(268, 'Raw Iron', '/items/minecraft_raw_iron.png'),
(269, 'Bamboo Pressure Plate', '/items/minecraft_bamboo_pressure_plate.png'),
(270, 'Bamboo Planks', '/items/minecraft_bamboo_planks.png'),
(271, 'Chiseled Stone Bricks', '/items/minecraft_chiseled_stone_bricks.png'),
(272, 'Stone Brick Slab', '/items/minecraft_stone_brick_slab.png'),
(273, 'Andesite', '/items/minecraft_andesite.png'),
(274, 'Brush', '/items/minecraft_brush.png'),
(275, 'Feather', '/items/minecraft_feather.png'),
(276, 'Brown Stained Glass', '/items/minecraft_brown_stained_glass.png'),
(277, 'Cyan Concrete Powder', '/items/minecraft_cyan_concrete_powder.png'),
(278, 'Nether Quartz Ore', '/items/minecraft_nether_quartz_ore.png'),
(279, 'Andesite Wall', '/items/minecraft_andesite_wall.png'),
(280, 'Stone Sword', '/items/minecraft_stone_sword.png'),
(281, 'Waxed Cut Copper', '/items/minecraft_waxed_cut_copper.png'),
(282, 'Waxed Copper Block', '/items/minecraft_waxed_copper_block.png'),
(283, 'Birch Door', '/items/minecraft_birch_door.png'),
(284, 'Redstone Block', '/items/minecraft_redstone_block.png'),
(285, 'Comparator', '/items/minecraft_comparator.png'),
(286, 'Redstone Torch', '/items/minecraft_redstone_torch.png'),
(287, 'Mangrove Door', '/items/minecraft_mangrove_door.png'),
(288, 'Mangrove Planks', '/items/minecraft_mangrove_planks.png'),
(289, 'Crimson Pressure Plate', '/items/minecraft_crimson_pressure_plate.png'),
(290, 'Target', '/items/minecraft_target.png'),
(291, 'Hay Block', '/items/minecraft_hay_block.png'),
(292, 'Stripped Warped Hyphae', '/items/minecraft_stripped_warped_hyphae.png'),
(293, 'Stripped Warped Stem', '/items/minecraft_stripped_warped_stem.png'),
(294, 'Purple Candle', '/items/minecraft_purple_candle.png'),
(295, 'Smooth Sandstone Stairs', '/items/minecraft_smooth_sandstone_stairs.png'),
(296, 'Dark Oak Wood', '/items/minecraft_dark_oak_wood.png'),
(297, 'Dark Oak Log', '/items/minecraft_dark_oak_log.png'),
(298, 'Brown Glazed Terracotta', '/items/minecraft_brown_glazed_terracotta.png'),
(299, 'Warped Sign', '/items/minecraft_warped_sign.png'),
(300, 'Diamond Chestplate', '/items/minecraft_diamond_chestplate.png'),
(301, 'Fishing Rod', '/items/minecraft_fishing_rod.png'),
(302, 'Waxed Cut Copper Slab', '/items/minecraft_waxed_cut_copper_slab.png'),
(303, 'Dark Oak Hanging Sign', '/items/minecraft_dark_oak_hanging_sign.png'),
(304, 'Mushroom Stew', '/items/minecraft_mushroom_stew.png'),
(305, 'Brown Mushroom', '/items/minecraft_brown_mushroom.png'),
(306, 'Red Mushroom', '/items/minecraft_red_mushroom.png'),
(307, 'Bowl', '/items/minecraft_bowl.png'),
(308, 'Cobblestone Slab', '/items/minecraft_cobblestone_slab.png'),
(309, 'Cookie', '/items/minecraft_cookie.png'),
(310, 'Cocoa Beans', '/items/minecraft_cocoa_beans.png'),
(311, 'Sentry Armor Trim Smithing Template', '/items/minecraft_sentry_armor_trim_smithing_template.png'),
(312, 'Soul Torch', '/items/minecraft_soul_torch.png'),
(313, 'Coal', '/items/minecraft_coal.png'),
(314, 'Charcoal', '/items/minecraft_charcoal.png'),
(315, 'Soul Lantern', '/items/minecraft_soul_lantern.png'),
(316, 'End Stone Bricks', '/items/minecraft_end_stone_bricks.png'),
(317, 'Polished Blackstone Wall', '/items/minecraft_polished_blackstone_wall.png'),
(318, 'Deepslate Copper Ore', '/items/minecraft_deepslate_copper_ore.png'),
(319, 'Polished Diorite Stairs', '/items/minecraft_polished_diorite_stairs.png'),
(320, 'Polished Diorite', '/items/minecraft_polished_diorite.png'),
(321, 'Orange Dye', '/items/minecraft_orange_dye.png'),
(322, 'Torchflower', '/items/minecraft_torchflower.png'),
(323, 'Spruce Fence', '/items/minecraft_spruce_fence.png'),
(324, 'Granite Wall', '/items/minecraft_granite_wall.png'),
(325, 'Granite', '/items/minecraft_granite.png'),
(326, 'Deepslate Brick Slab', '/items/minecraft_deepslate_brick_slab.png'),
(327, 'Bamboo Mosaic', '/items/minecraft_bamboo_mosaic.png'),
(328, 'Bamboo Slab', '/items/minecraft_bamboo_slab.png'),
(329, 'Warped Button', '/items/minecraft_warped_button.png'),
(330, 'Waxed Oxidized Cut Copper Stairs', '/items/minecraft_waxed_oxidized_cut_copper_stairs.png'),
(331, 'Oxidized Cut Copper Stairs', '/items/minecraft_oxidized_cut_copper_stairs.png'),
(332, 'Sugar Cane', '/items/minecraft_sugar_cane.png'),
(333, 'Light Blue Dye', '/items/minecraft_light_blue_dye.png'),
(334, 'Blue Orchid', '/items/minecraft_blue_orchid.png'),
(335, 'Deepslate Tile Slab', '/items/minecraft_deepslate_tile_slab.png'),
(336, 'Deepslate Tiles', '/items/minecraft_deepslate_tiles.png'),
(337, 'Light Gray Glazed Terracotta', '/items/minecraft_light_gray_glazed_terracotta.png'),
(338, 'Light Gray Terracotta', '/items/minecraft_light_gray_terracotta.png'),
(339, 'Shulker Box', '/items/minecraft_shulker_box.png'),
(340, 'Chest', '/items/minecraft_chest.png'),
(341, 'Shulker Shell', '/items/minecraft_shulker_shell.png'),
(342, 'Music Disc 5', '/items/minecraft_music_disc_5.png'),
(343, 'Disc Fragment 5', '/items/minecraft_disc_fragment_5.png'),
(344, 'Melon', '/items/minecraft_melon.png'),
(345, 'Melon Slice', '/items/minecraft_melon_slice.png'),
(346, 'Dark Oak Sign', '/items/minecraft_dark_oak_sign.png'),
(347, 'Polished Blackstone Bricks', '/items/minecraft_polished_blackstone_bricks.png'),
(348, 'Cooked Salmon', '/items/minecraft_cooked_salmon.png'),
(349, 'Salmon', '/items/minecraft_salmon.png'),
(350, 'Sticky Piston', '/items/minecraft_sticky_piston.png'),
(351, 'Piston', '/items/minecraft_piston.png'),
(352, 'Trapped Chest', '/items/minecraft_trapped_chest.png'),
(353, 'Tripwire Hook', '/items/minecraft_tripwire_hook.png'),
(354, 'Dark Oak Fence Gate', '/items/minecraft_dark_oak_fence_gate.png'),
(355, 'Sandstone Slab', '/items/minecraft_sandstone_slab.png'),
(356, 'Chiseled Sandstone', '/items/minecraft_chiseled_sandstone.png'),
(357, 'Ender Chest', '/items/minecraft_ender_chest.png'),
(358, 'Obsidian', '/items/minecraft_obsidian.png'),
(359, 'Orange Stained Glass Pane', '/items/minecraft_orange_stained_glass_pane.png'),
(360, 'Acacia Pressure Plate', '/items/minecraft_acacia_pressure_plate.png'),
(361, 'Brick Slab', '/items/minecraft_brick_slab.png'),
(362, 'Bamboo Mosaic Stairs', '/items/minecraft_bamboo_mosaic_stairs.png'),
(363, 'Emerald', '/items/minecraft_emerald.png'),
(364, 'Emerald Block', '/items/minecraft_emerald_block.png'),
(365, 'Pink Stained Glass', '/items/minecraft_pink_stained_glass.png'),
(366, 'Purpur Slab', '/items/minecraft_purpur_slab.png'),
(367, 'Purpur Pillar', '/items/minecraft_purpur_pillar.png'),
(368, 'Mangrove Button', '/items/minecraft_mangrove_button.png'),
(369, 'Leather Helmet', '/items/minecraft_leather_helmet.png'),
(370, 'Polished Granite Slab', '/items/minecraft_polished_granite_slab.png'),
(371, 'Emerald Ore', '/items/minecraft_emerald_ore.png'),
(372, 'Red Sandstone Stairs', '/items/minecraft_red_sandstone_stairs.png'),
(373, 'Acacia Button', '/items/minecraft_acacia_button.png'),
(374, 'Amethyst Block', '/items/minecraft_amethyst_block.png'),
(375, 'Amethyst Shard', '/items/minecraft_amethyst_shard.png'),
(376, 'Stone Stairs', '/items/minecraft_stone_stairs.png'),
(377, 'Birch Chest Boat', '/items/minecraft_birch_chest_boat.png'),
(378, 'Birch Boat', '/items/minecraft_birch_boat.png'),
(379, 'Prismarine Stairs', '/items/minecraft_prismarine_stairs.png'),
(380, 'Prismarine', '/items/minecraft_prismarine.png'),
(381, 'Orange Candle', '/items/minecraft_orange_candle.png'),
(382, 'Stripped Acacia Wood', '/items/minecraft_stripped_acacia_wood.png'),
(383, 'Stripped Acacia Log', '/items/minecraft_stripped_acacia_log.png'),
(384, 'Dried Kelp Block', '/items/minecraft_dried_kelp_block.png'),
(385, 'Dried Kelp', '/items/minecraft_dried_kelp.png'),
(386, 'Andesite Stairs', '/items/minecraft_andesite_stairs.png'),
(387, 'Beetroot Soup', '/items/minecraft_beetroot_soup.png'),
(388, 'Beetroot', '/items/minecraft_beetroot.png'),
(389, 'Cooked Cod', '/items/minecraft_cooked_cod.png'),
(390, 'Cod', '/items/minecraft_cod.png'),
(391, 'Orange Glazed Terracotta', '/items/minecraft_orange_glazed_terracotta.png'),
(392, 'Orange Terracotta', '/items/minecraft_orange_terracotta.png'),
(393, 'Bone Meal', '/items/minecraft_bone_meal.png'),
(394, 'Bone', '/items/minecraft_bone.png'),
(395, 'Netherite Scrap', '/items/minecraft_netherite_scrap.png'),
(396, 'Ancient Debris', '/items/minecraft_ancient_debris.png'),
(397, 'Jack O Lantern', '/items/minecraft_jack_o_lantern.png'),
(398, 'Carved Pumpkin', '/items/minecraft_carved_pumpkin.png'),
(399, 'End Stone Brick Wall', '/items/minecraft_end_stone_brick_wall.png'),
(400, 'Cooked Mutton', '/items/minecraft_cooked_mutton.png'),
(401, 'Mutton', '/items/minecraft_mutton.png'),
(402, 'Chiseled Quartz Block', '/items/minecraft_chiseled_quartz_block.png'),
(403, 'Quartz Slab', '/items/minecraft_quartz_slab.png'),
(404, 'Polished Blackstone Brick Wall', '/items/minecraft_polished_blackstone_brick_wall.png'),
(405, 'Iron Chestplate', '/items/minecraft_iron_chestplate.png'),
(406, 'Mangrove Boat', '/items/minecraft_mangrove_boat.png'),
(407, 'Iron Pickaxe', '/items/minecraft_iron_pickaxe.png'),
(408, 'Iron Shovel', '/items/minecraft_iron_shovel.png'),
(409, 'Iron Axe', '/items/minecraft_iron_axe.png'),
(410, 'Iron Hoe', '/items/minecraft_iron_hoe.png'),
(411, 'Iron Sword', '/items/minecraft_iron_sword.png'),
(412, 'Iron Helmet', '/items/minecraft_iron_helmet.png'),
(413, 'Iron Leggings', '/items/minecraft_iron_leggings.png'),
(414, 'Iron Boots', '/items/minecraft_iron_boots.png'),
(415, 'Iron Horse Armor', '/items/minecraft_iron_horse_armor.png'),
(416, 'Chainmail Helmet', '/items/minecraft_chainmail_helmet.png'),
(417, 'Chainmail Chestplate', '/items/minecraft_chainmail_chestplate.png'),
(418, 'Chainmail Leggings', '/items/minecraft_chainmail_leggings.png'),
(419, 'Chainmail Boots', '/items/minecraft_chainmail_boots.png'),
(420, 'Cooked Beef', '/items/minecraft_cooked_beef.png'),
(421, 'Beef', '/items/minecraft_beef.png'),
(422, 'Vine', '/items/minecraft_vine.png'),
(423, 'Writable Book', '/items/minecraft_writable_book.png'),
(424, 'Book', '/items/minecraft_book.png'),
(425, 'Ink Sac', '/items/minecraft_ink_sac.png'),
(426, 'Dispenser', '/items/minecraft_dispenser.png'),
(427, 'Bow', '/items/minecraft_bow.png'),
(428, 'Green Stained Glass Pane', '/items/minecraft_green_stained_glass_pane.png'),
(429, 'Deepslate Diamond Ore', '/items/minecraft_deepslate_diamond_ore.png'),
(430, 'Lily Of The Valley', '/items/minecraft_lily_of_the_valley.png'),
(431, 'Bamboo Sign', '/items/minecraft_bamboo_sign.png'),
(432, 'Chiseled Polished Blackstone', '/items/minecraft_chiseled_polished_blackstone.png'),
(433, 'Raw Gold', '/items/minecraft_raw_gold.png'),
(434, 'Chorus Fruit', '/items/minecraft_chorus_fruit.png'),
(435, 'Brick', '/items/minecraft_brick.png'),
(436, 'Clay Ball', '/items/minecraft_clay_ball.png'),
(437, 'Nether Brick', '/items/minecraft_nether_brick.png'),
(438, 'Stone Slab', '/items/minecraft_stone_slab.png'),
(439, 'Magenta Dye', '/items/minecraft_magenta_dye.png'),
(440, 'Allium', '/items/minecraft_allium.png'),
(441, 'Golden Pickaxe', '/items/minecraft_golden_pickaxe.png'),
(442, 'Golden Shovel', '/items/minecraft_golden_shovel.png'),
(443, 'Golden Axe', '/items/minecraft_golden_axe.png'),
(444, 'Golden Hoe', '/items/minecraft_golden_hoe.png'),
(445, 'Golden Sword', '/items/minecraft_golden_sword.png'),
(446, 'Golden Helmet', '/items/minecraft_golden_helmet.png'),
(447, 'Golden Chestplate', '/items/minecraft_golden_chestplate.png'),
(448, 'Golden Leggings', '/items/minecraft_golden_leggings.png'),
(449, 'Golden Boots', '/items/minecraft_golden_boots.png'),
(450, 'Golden Horse Armor', '/items/minecraft_golden_horse_armor.png'),
(451, 'Quartz Stairs', '/items/minecraft_quartz_stairs.png'),
(452, 'Quartz Block', '/items/minecraft_quartz_block.png'),
(453, 'Quartz Pillar', '/items/minecraft_quartz_pillar.png'),
(454, 'Nether Brick Wall', '/items/minecraft_nether_brick_wall.png'),
(455, 'Oak Boat', '/items/minecraft_oak_boat.png'),
(456, 'Acacia Sign', '/items/minecraft_acacia_sign.png'),
(457, 'Warped Pressure Plate', '/items/minecraft_warped_pressure_plate.png'),
(458, 'Pumpkin Seeds', '/items/minecraft_pumpkin_seeds.png'),
(459, 'Pumpkin', '/items/minecraft_pumpkin.png'),
(460, 'Sandstone Stairs', '/items/minecraft_sandstone_stairs.png'),
(461, 'Cut Sandstone', '/items/minecraft_cut_sandstone.png'),
(462, 'Magenta Stained Glass Pane', '/items/minecraft_magenta_stained_glass_pane.png'),
(463, 'Clay', '/items/minecraft_clay.png'),
(464, 'Ender Pearl', '/items/minecraft_ender_pearl.png'),
(465, 'Blaze Powder', '/items/minecraft_blaze_powder.png'),
(466, 'Crimson Button', '/items/minecraft_crimson_button.png'),
(467, 'Deepslate Tile Wall', '/items/minecraft_deepslate_tile_wall.png'),
(468, 'Calibrated Sculk Sensor', '/items/minecraft_calibrated_sculk_sensor.png'),
(469, 'Sculk Sensor', '/items/minecraft_sculk_sensor.png'),
(470, 'Purple Glazed Terracotta', '/items/minecraft_purple_glazed_terracotta.png'),
(471, 'Purple Terracotta', '/items/minecraft_purple_terracotta.png'),
(472, 'Stripped Mangrove Wood', '/items/minecraft_stripped_mangrove_wood.png'),
(473, 'Purple Concrete Powder', '/items/minecraft_purple_concrete_powder.png'),
(474, 'White Tulip', '/items/minecraft_white_tulip.png'),
(475, 'Netherite Shovel', '/items/minecraft_netherite_shovel.png'),
(476, 'Cyan Stained Glass', '/items/minecraft_cyan_stained_glass.png'),
(477, 'Yellow Terracotta', '/items/minecraft_yellow_terracotta.png'),
(478, 'Andesite Slab', '/items/minecraft_andesite_slab.png'),
(479, 'Blackstone Wall', '/items/minecraft_blackstone_wall.png'),
(480, 'Deepslate Iron Ore', '/items/minecraft_deepslate_iron_ore.png'),
(481, 'Shears', '/items/minecraft_shears.png'),
(482, 'Deepslate Redstone Ore', '/items/minecraft_deepslate_redstone_ore.png'),
(483, 'Rabbit Stew', '/items/minecraft_rabbit_stew.png'),
(484, 'Cooked Rabbit', '/items/minecraft_cooked_rabbit.png'),
(485, 'Honeycomb Block', '/items/minecraft_honeycomb_block.png'),
(486, 'Black Dye', '/items/minecraft_black_dye.png'),
(487, 'Wither Rose', '/items/minecraft_wither_rose.png'),
(488, 'Eye Armor Trim Smithing Template', '/items/minecraft_eye_armor_trim_smithing_template.png'),
(489, 'Crimson Fence', '/items/minecraft_crimson_fence.png'),
(490, 'Stone Brick Wall', '/items/minecraft_stone_brick_wall.png'),
(491, 'Yellow Glazed Terracotta', '/items/minecraft_yellow_glazed_terracotta.png'),
(492, 'Smoker', '/items/minecraft_smoker.png'),
(493, 'Bamboo Trapdoor', '/items/minecraft_bamboo_trapdoor.png'),
(494, 'Tnt Minecart', '/items/minecraft_tnt_minecart.png'),
(495, 'Tnt', '/items/minecraft_tnt.png'),
(496, 'Exposed Cut Copper Stairs', '/items/minecraft_exposed_cut_copper_stairs.png'),
(497, 'Exposed Cut Copper', '/items/minecraft_exposed_cut_copper.png'),
(498, 'Cherry Fence Gate', '/items/minecraft_cherry_fence_gate.png'),
(499, 'Chiseled Nether Bricks', '/items/minecraft_chiseled_nether_bricks.png'),
(500, 'Dandelion', '/items/minecraft_dandelion.png'),
(501, 'Heavy Weighted Pressure Plate', '/items/minecraft_heavy_weighted_pressure_plate.png'),
(502, 'Netherite Ingot', '/items/minecraft_netherite_ingot.png'),
(503, 'White Candle', '/items/minecraft_white_candle.png'),
(504, 'Dark Oak Stairs', '/items/minecraft_dark_oak_stairs.png'),
(505, 'Cherry Button', '/items/minecraft_cherry_button.png'),
(506, 'Netherite Sword', '/items/minecraft_netherite_sword.png'),
(507, 'Dark Prismarine Slab', '/items/minecraft_dark_prismarine_slab.png'),
(508, 'Dark Prismarine', '/items/minecraft_dark_prismarine.png'),
(509, 'Spruce Trapdoor', '/items/minecraft_spruce_trapdoor.png'),
(510, 'Fire Charge', '/items/minecraft_fire_charge.png'),
(511, 'Gunpowder', '/items/minecraft_gunpowder.png'),
(512, 'Weathered Cut Copper Slab', '/items/minecraft_weathered_cut_copper_slab.png'),
(513, 'Quartz Bricks', '/items/minecraft_quartz_bricks.png'),
(514, 'Coast Armor Trim Smithing Template', '/items/minecraft_coast_armor_trim_smithing_template.png'),
(515, 'Oak Trapdoor', '/items/minecraft_oak_trapdoor.png'),
(516, 'Purple Stained Glass Pane', '/items/minecraft_purple_stained_glass_pane.png'),
(517, 'Purple Stained Glass', '/items/minecraft_purple_stained_glass.png'),
(518, 'Blaze Rod', '/items/minecraft_blaze_rod.png'),
(519, 'Crimson Sign', '/items/minecraft_crimson_sign.png'),
(520, 'Barrel', '/items/minecraft_barrel.png'),
(521, 'Red Stained Glass', '/items/minecraft_red_stained_glass.png'),
(522, 'Polished Blackstone Brick Stairs', '/items/minecraft_polished_blackstone_brick_stairs.png'),
(523, 'Mossy Stone Brick Stairs', '/items/minecraft_mossy_stone_brick_stairs.png'),
(524, 'Oak Pressure Plate', '/items/minecraft_oak_pressure_plate.png'),
(525, 'Gray Stained Glass', '/items/minecraft_gray_stained_glass.png'),
(526, 'Polished Deepslate Wall', '/items/minecraft_polished_deepslate_wall.png'),
(527, 'Smooth Stone Slab', '/items/minecraft_smooth_stone_slab.png'),
(528, 'Smooth Stone', '/items/minecraft_smooth_stone.png'),
(529, 'Warped Trapdoor', '/items/minecraft_warped_trapdoor.png'),
(530, 'Sunflower', '/items/minecraft_sunflower.png'),
(531, 'Gray Glazed Terracotta', '/items/minecraft_gray_glazed_terracotta.png'),
(532, 'Granite Slab', '/items/minecraft_granite_slab.png'),
(533, 'Black Glazed Terracotta', '/items/minecraft_black_glazed_terracotta.png'),
(534, 'Black Terracotta', '/items/minecraft_black_terracotta.png'),
(535, 'Deepslate Emerald Ore', '/items/minecraft_deepslate_emerald_ore.png'),
(536, 'Warped Fungus On A Stick', '/items/minecraft_warped_fungus_on_a_stick.png'),
(537, 'Warped Fungus', '/items/minecraft_warped_fungus.png'),
(538, 'Polished Deepslate Slab', '/items/minecraft_polished_deepslate_slab.png'),
(539, 'Blue Ice', '/items/minecraft_blue_ice.png'),
(540, 'Packed Ice', '/items/minecraft_packed_ice.png'),
(541, 'Acacia Wood', '/items/minecraft_acacia_wood.png'),
(542, 'Acacia Log', '/items/minecraft_acacia_log.png'),
(543, 'Red Sand', '/items/minecraft_red_sand.png'),
(544, 'Cut Sandstone Slab', '/items/minecraft_cut_sandstone_slab.png'),
(545, 'Spyglass', '/items/minecraft_spyglass.png'),
(546, 'Diamond Block', '/items/minecraft_diamond_block.png'),
(547, 'Stripped Oak Wood', '/items/minecraft_stripped_oak_wood.png'),
(548, 'Stripped Oak Log', '/items/minecraft_stripped_oak_log.png'),
(549, 'End Rod', '/items/minecraft_end_rod.png'),
(550, 'Red Nether Brick Slab', '/items/minecraft_red_nether_brick_slab.png'),
(551, 'Red Nether Bricks', '/items/minecraft_red_nether_bricks.png'),
(552, 'Light Blue Candle', '/items/minecraft_light_blue_candle.png'),
(553, 'Blue Candle', '/items/minecraft_blue_candle.png'),
(554, 'Crimson Hanging Sign', '/items/minecraft_crimson_hanging_sign.png'),
(555, 'Stripped Crimson Stem', '/items/minecraft_stripped_crimson_stem.png'),
(556, 'Snout Armor Trim Smithing Template', '/items/minecraft_snout_armor_trim_smithing_template.png'),
(557, 'Compass', '/items/minecraft_compass.png'),
(558, 'Bamboo Button', '/items/minecraft_bamboo_button.png'),
(559, 'Brown Candle', '/items/minecraft_brown_candle.png'),
(560, 'Red Nether Brick Wall', '/items/minecraft_red_nether_brick_wall.png'),
(561, 'Pink Candle', '/items/minecraft_pink_candle.png'),
(562, 'Bamboo Hanging Sign', '/items/minecraft_bamboo_hanging_sign.png'),
(563, 'Stripped Bamboo Block', '/items/minecraft_stripped_bamboo_block.png'),
(564, 'Cherry Hanging Sign', '/items/minecraft_cherry_hanging_sign.png'),
(565, 'Stripped Cherry Log', '/items/minecraft_stripped_cherry_log.png'),
(566, 'Red Nether Brick Stairs', '/items/minecraft_red_nether_brick_stairs.png'),
(567, 'Moss Carpet', '/items/minecraft_moss_carpet.png'),
(568, 'Oak Door', '/items/minecraft_oak_door.png'),
(569, 'Wooden Sword', '/items/minecraft_wooden_sword.png'),
(570, 'Nether Wart Block', '/items/minecraft_nether_wart_block.png'),
(571, 'Nether Wart', '/items/minecraft_nether_wart.png'),
(572, 'Paper', '/items/minecraft_paper.png'),
(573, 'Respawn Anchor', '/items/minecraft_respawn_anchor.png'),
(574, 'Crying Obsidian', '/items/minecraft_crying_obsidian.png'),
(575, 'Sea Lantern', '/items/minecraft_sea_lantern.png'),
(576, 'Prismarine Crystals', '/items/minecraft_prismarine_crystals.png'),
(577, 'Prismarine Shard', '/items/minecraft_prismarine_shard.png'),
(578, 'Polished Andesite Slab', '/items/minecraft_polished_andesite_slab.png'),
(579, 'Polished Andesite', '/items/minecraft_polished_andesite.png'),
(580, 'Pink Petals', '/items/minecraft_pink_petals.png'),
(581, 'End Stone Brick Stairs', '/items/minecraft_end_stone_brick_stairs.png'),
(582, 'Stripped Birch Wood', '/items/minecraft_stripped_birch_wood.png'),
(583, 'Stripped Birch Log', '/items/minecraft_stripped_birch_log.png'),
(584, 'Blackstone Slab', '/items/minecraft_blackstone_slab.png'),
(585, 'Granite Stairs', '/items/minecraft_granite_stairs.png'),
(586, 'Bookshelf', '/items/minecraft_bookshelf.png'),
(587, 'Mangrove Chest Boat', '/items/minecraft_mangrove_chest_boat.png'),
(588, 'Birch Sign', '/items/minecraft_birch_sign.png'),
(589, 'Diamond Axe', '/items/minecraft_diamond_axe.png'),
(590, 'Lodestone', '/items/minecraft_lodestone.png'),
(591, 'Cherry Slab', '/items/minecraft_cherry_slab.png'),
(592, 'Oak Button', '/items/minecraft_oak_button.png'),
(593, 'Mangrove Sign', '/items/minecraft_mangrove_sign.png'),
(594, 'Orange Stained Glass', '/items/minecraft_orange_stained_glass.png'),
(595, 'Gray Stained Glass Pane', '/items/minecraft_gray_stained_glass_pane.png'),
(596, 'Spruce Pressure Plate', '/items/minecraft_spruce_pressure_plate.png'),
(597, 'Warped Door', '/items/minecraft_warped_door.png'),
(598, 'Cactus', '/items/minecraft_cactus.png'),
(599, 'Cobblestone Stairs', '/items/minecraft_cobblestone_stairs.png'),
(600, 'Rose Bush', '/items/minecraft_rose_bush.png'),
(601, 'Red Stained Glass Pane', '/items/minecraft_red_stained_glass_pane.png'),
(602, 'Note Block', '/items/minecraft_note_block.png'),
(603, 'Iron Bars', '/items/minecraft_iron_bars.png'),
(604, 'Turtle Helmet', '/items/minecraft_turtle_helmet.png'),
(605, 'Scute', '/items/minecraft_scute.png'),
(606, 'Netherite Hoe', '/items/minecraft_netherite_hoe.png'),
(607, 'Shield', '/items/minecraft_shield.png'),
(608, 'Yellow Stained Glass Pane', '/items/minecraft_yellow_stained_glass_pane.png'),
(609, 'Yellow Stained Glass', '/items/minecraft_yellow_stained_glass.png'),
(610, 'Diamond Hoe', '/items/minecraft_diamond_hoe.png'),
(611, 'Brown Stained Glass Pane', '/items/minecraft_brown_stained_glass_pane.png'),
(612, 'Scaffolding', '/items/minecraft_scaffolding.png'),
(613, 'Jungle Slab', '/items/minecraft_jungle_slab.png'),
(614, 'Lever', '/items/minecraft_lever.png'),
(615, 'Smooth Sandstone Slab', '/items/minecraft_smooth_sandstone_slab.png'),
(616, 'Purple Banner', '/items/minecraft_purple_banner.png'),
(617, 'Acacia Fence', '/items/minecraft_acacia_fence.png'),
(618, 'Dark Oak Boat', '/items/minecraft_dark_oak_boat.png'),
(619, 'Bone Block', '/items/minecraft_bone_block.png'),
(620, 'Weathered Cut Copper Stairs', '/items/minecraft_weathered_cut_copper_stairs.png'),
(621, 'Arrow', '/items/minecraft_arrow.png'),
(622, 'Wooden Hoe', '/items/minecraft_wooden_hoe.png'),
(623, 'Magenta Stained Glass', '/items/minecraft_magenta_stained_glass.png'),
(624, 'Dark Oak Door', '/items/minecraft_dark_oak_door.png'),
(625, 'Light Blue Terracotta', '/items/minecraft_light_blue_terracotta.png'),
(626, 'Coal Ore', '/items/minecraft_coal_ore.png'),
(627, 'Poppy', '/items/minecraft_poppy.png'),
(628, 'Prismarine Brick Stairs', '/items/minecraft_prismarine_brick_stairs.png'),
(629, 'Prismarine Bricks', '/items/minecraft_prismarine_bricks.png'),
(630, 'Waxed Weathered Cut Copper Slab', '/items/minecraft_waxed_weathered_cut_copper_slab.png'),
(631, 'Mangrove Wood', '/items/minecraft_mangrove_wood.png'),
(632, 'Mangrove Log', '/items/minecraft_mangrove_log.png'),
(633, 'Birch Stairs', '/items/minecraft_birch_stairs.png'),
(634, 'Rabbit', '/items/minecraft_rabbit.png'),
(635, 'Birch Wood', '/items/minecraft_birch_wood.png'),
(636, 'Birch Log', '/items/minecraft_birch_log.png'),
(637, 'Exposed Cut Copper Slab', '/items/minecraft_exposed_cut_copper_slab.png'),
(638, 'Nether Gold Ore', '/items/minecraft_nether_gold_ore.png'),
(639, 'Acacia Fence Gate', '/items/minecraft_acacia_fence_gate.png'),
(640, 'Shaper Armor Trim Smithing Template', '/items/minecraft_shaper_armor_trim_smithing_template.png'),
(641, 'Black Stained Glass Pane', '/items/minecraft_black_stained_glass_pane.png'),
(642, 'Dark Prismarine Stairs', '/items/minecraft_dark_prismarine_stairs.png'),
(643, 'Raw Iron Block', '/items/minecraft_raw_iron_block.png'),
(644, 'Waxed Exposed Cut Copper Stairs', '/items/minecraft_waxed_exposed_cut_copper_stairs.png'),
(645, 'Polished Andesite Stairs', '/items/minecraft_polished_andesite_stairs.png'),
(646, 'Stone Brick Stairs', '/items/minecraft_stone_brick_stairs.png'),
(647, 'Smooth Quartz Stairs', '/items/minecraft_smooth_quartz_stairs.png'),
(648, 'Green Stained Glass', '/items/minecraft_green_stained_glass.png'),
(649, 'Crimson Hyphae', '/items/minecraft_crimson_hyphae.png'),
(650, 'Crimson Stem', '/items/minecraft_crimson_stem.png'),
(651, 'Bamboo Door', '/items/minecraft_bamboo_door.png'),
(652, 'Chiseled Deepslate', '/items/minecraft_chiseled_deepslate.png'),
(653, 'Gold Block', '/items/minecraft_gold_block.png'),
(654, 'Cut Copper Slab', '/items/minecraft_cut_copper_slab.png'),
(655, 'Polished Diorite Slab', '/items/minecraft_polished_diorite_slab.png'),
(656, 'Orange Banner', '/items/minecraft_orange_banner.png'),
(657, 'Acacia Hanging Sign', '/items/minecraft_acacia_hanging_sign.png'),
(658, 'Netherite Upgrade Smithing Template', '/items/minecraft_netherite_upgrade_smithing_template.png'),
(659, 'Netherrack', '/items/minecraft_netherrack.png'),
(660, 'Wooden Axe', '/items/minecraft_wooden_axe.png'),
(661, 'Green Glazed Terracotta', '/items/minecraft_green_glazed_terracotta.png'),
(662, 'Gray Candle', '/items/minecraft_gray_candle.png'),
(663, 'Spruce Door', '/items/minecraft_spruce_door.png'),
(664, 'Red Banner', '/items/minecraft_red_banner.png'),
(665, 'Smithing Table', '/items/minecraft_smithing_table.png'),
(666, 'Wooden Shovel', '/items/minecraft_wooden_shovel.png'),
(667, 'Acacia Slab', '/items/minecraft_acacia_slab.png'),
(668, 'Blast Furnace', '/items/minecraft_blast_furnace.png'),
(669, 'Stone Hoe', '/items/minecraft_stone_hoe.png'),
(670, 'Bamboo Fence', '/items/minecraft_bamboo_fence.png'),
(671, 'Wooden Pickaxe', '/items/minecraft_wooden_pickaxe.png'),
(672, 'Stone Button', '/items/minecraft_stone_button.png'),
(673, 'Light Gray Candle', '/items/minecraft_light_gray_candle.png'),
(674, 'Birch Button', '/items/minecraft_birch_button.png'),
(675, 'Kelp', '/items/minecraft_kelp.png'),
(676, 'Diamond Shovel', '/items/minecraft_diamond_shovel.png'),
(677, 'Stone Pickaxe', '/items/minecraft_stone_pickaxe.png'),
(678, 'Lime Stained Glass Pane', '/items/minecraft_lime_stained_glass_pane.png'),
(679, 'Lime Stained Glass', '/items/minecraft_lime_stained_glass.png'),
(680, 'Mangrove Fence', '/items/minecraft_mangrove_fence.png'),
(681, 'Decorated Pot', '/items/minecraft_decorated_pot.png'),
(682, 'Bamboo Fence Gate', '/items/minecraft_bamboo_fence_gate.png'),
(683, 'Bamboo Mosaic Slab', '/items/minecraft_bamboo_mosaic_slab.png'),
(684, 'Cherry Trapdoor', '/items/minecraft_cherry_trapdoor.png'),
(685, 'Lightning Rod', '/items/minecraft_lightning_rod.png'),
(686, 'Netherite Chestplate', '/items/minecraft_netherite_chestplate.png'),
(687, 'Creeper Banner Pattern', '/items/minecraft_creeper_banner_pattern.png'),
(688, 'Creeper Head', '/items/minecraft_creeper_head.png'),
(689, 'Deepslate', '/items/minecraft_deepslate.png'),
(690, 'Loom', '/items/minecraft_loom.png'),
(691, 'Deepslate Lapis Ore', '/items/minecraft_deepslate_lapis_ore.png'),
(692, 'Cherry Pressure Plate', '/items/minecraft_cherry_pressure_plate.png'),
(693, 'Copper Ore', '/items/minecraft_copper_ore.png'),
(694, 'Jukebox', '/items/minecraft_jukebox.png'),
(695, 'Lead', '/items/minecraft_lead.png'),
(696, 'Brick Stairs', '/items/minecraft_brick_stairs.png'),
(697, 'Magenta Banner', '/items/minecraft_magenta_banner.png'),
(698, 'Magma Block', '/items/minecraft_magma_block.png'),
(699, 'Magma Cream', '/items/minecraft_magma_cream.png'),
(700, 'Diamond Ore', '/items/minecraft_diamond_ore.png'),
(701, 'Oak Fence', '/items/minecraft_oak_fence.png'),
(702, 'Jungle Trapdoor', '/items/minecraft_jungle_trapdoor.png'),
(703, 'Composter', '/items/minecraft_composter.png'),
(704, 'Lime Candle', '/items/minecraft_lime_candle.png'),
(705, 'Stone Axe', '/items/minecraft_stone_axe.png'),
(706, 'Dark Oak Fence', '/items/minecraft_dark_oak_fence.png'),
(707, 'Warped Fence Gate', '/items/minecraft_warped_fence_gate.png'),
(708, 'Cartography Table', '/items/minecraft_cartography_table.png'),
(709, 'Raw Copper', '/items/minecraft_raw_copper.png'),
(710, 'Grindstone', '/items/minecraft_grindstone.png'),
(711, 'Peony', '/items/minecraft_peony.png'),
(712, 'Flint And Steel', '/items/minecraft_flint_and_steel.png'),
(713, 'Mud Brick Stairs', '/items/minecraft_mud_brick_stairs.png'),
(714, 'Mud Bricks', '/items/minecraft_mud_bricks.png'),
(715, 'Ladder', '/items/minecraft_ladder.png'),
(716, 'Crimson Slab', '/items/minecraft_crimson_slab.png'),
(717, 'Cyan Stained Glass Pane', '/items/minecraft_cyan_stained_glass_pane.png'),
(718, 'Crimson Trapdoor', '/items/minecraft_crimson_trapdoor.png'),
(719, 'Light Blue Concrete Powder', '/items/minecraft_light_blue_concrete_powder.png'),
(720, 'Painting', '/items/minecraft_painting.png'),
(721, 'Oak Stairs', '/items/minecraft_oak_stairs.png'),
(722, 'Pink Glazed Terracotta', '/items/minecraft_pink_glazed_terracotta.png'),
(723, 'Pumpkin Pie', '/items/minecraft_pumpkin_pie.png'),
(724, 'Egg', '/items/minecraft_egg.png'),
(725, 'Netherite Block', '/items/minecraft_netherite_block.png'),
(726, 'Netherite Helmet', '/items/minecraft_netherite_helmet.png'),
(727, 'Dripstone Block', '/items/minecraft_dripstone_block.png'),
(728, 'Pointed Dripstone', '/items/minecraft_pointed_dripstone.png'),
(729, 'Chest Minecart', '/items/minecraft_chest_minecart.png'),
(730, 'Pink Concrete Powder', '/items/minecraft_pink_concrete_powder.png'),
(731, 'Polished Basalt', '/items/minecraft_polished_basalt.png'),
(732, 'Crafting Table', '/items/minecraft_crafting_table.png'),
(733, 'Bamboo Chest Raft', '/items/minecraft_bamboo_chest_raft.png'),
(734, 'Bamboo Raft', '/items/minecraft_bamboo_raft.png'),
(735, 'Netherite Axe', '/items/minecraft_netherite_axe.png'),
(736, 'Jungle Fence', '/items/minecraft_jungle_fence.png'),
(737, 'Prismarine Slab', '/items/minecraft_prismarine_slab.png'),
(738, 'Spruce Hanging Sign', '/items/minecraft_spruce_hanging_sign.png'),
(739, 'Stripped Spruce Log', '/items/minecraft_stripped_spruce_log.png'),
(740, 'Black Banner', '/items/minecraft_black_banner.png'),
(741, 'Chiseled Bookshelf', '/items/minecraft_chiseled_bookshelf.png'),
(742, 'Mud Brick Slab', '/items/minecraft_mud_brick_slab.png'),
(743, 'Dark Oak Pressure Plate', '/items/minecraft_dark_oak_pressure_plate.png'),
(744, 'Birch Fence Gate', '/items/minecraft_birch_fence_gate.png'),
(745, 'Spire Armor Trim Smithing Template', '/items/minecraft_spire_armor_trim_smithing_template.png'),
(746, 'Raw Copper Block', '/items/minecraft_raw_copper_block.png'),
(747, 'Nether Brick Stairs', '/items/minecraft_nether_brick_stairs.png'),
(748, 'Yellow Banner', '/items/minecraft_yellow_banner.png'),
(749, 'Diorite Wall', '/items/minecraft_diorite_wall.png'),
(750, 'Enchanting Table', '/items/minecraft_enchanting_table.png'),
(751, 'Spruce Boat', '/items/minecraft_spruce_boat.png'),
(752, 'Dark Oak Chest Boat', '/items/minecraft_dark_oak_chest_boat.png'),
(753, 'Orange Concrete Powder', '/items/minecraft_orange_concrete_powder.png'),
(754, 'Spruce Chest Boat', '/items/minecraft_spruce_chest_boat.png'),
(755, 'Cyan Banner', '/items/minecraft_cyan_banner.png'),
(756, 'Raiser Armor Trim Smithing Template', '/items/minecraft_raiser_armor_trim_smithing_template.png'),
(757, 'Pink Stained Glass Pane', '/items/minecraft_pink_stained_glass_pane.png'),
(758, 'Crossbow', '/items/minecraft_crossbow.png'),
(759, 'Flower Pot', '/items/minecraft_flower_pot.png'),
(760, 'Birch Slab', '/items/minecraft_birch_slab.png'),
(761, 'Rabbit Hide', '/items/minecraft_rabbit_hide.png'),
(762, 'Cracked Polished Blackstone Bricks', '/items/minecraft_cracked_polished_blackstone_bricks.png'),
(763, 'Gray Concrete Powder', '/items/minecraft_gray_concrete_powder.png'),
(764, 'Activator Rail', '/items/minecraft_activator_rail.png'),
(765, 'Rib Armor Trim Smithing Template', '/items/minecraft_rib_armor_trim_smithing_template.png'),
(766, 'Mangrove Slab', '/items/minecraft_mangrove_slab.png'),
(767, 'Cherry Sign', '/items/minecraft_cherry_sign.png'),
(768, 'Cracked Deepslate Tiles', '/items/minecraft_cracked_deepslate_tiles.png'),
(769, 'Oak Chest Boat', '/items/minecraft_oak_chest_boat.png'),
(770, 'Crimson Fence Gate', '/items/minecraft_crimson_fence_gate.png'),
(771, 'Ward Armor Trim Smithing Template', '/items/minecraft_ward_armor_trim_smithing_template.png'),
(772, 'Firework Rocket', '/items/minecraft_firework_rocket.png'),
(773, 'Soul Campfire', '/items/minecraft_soul_campfire.png'),
(774, 'Diamond Pickaxe', '/items/minecraft_diamond_pickaxe.png'),
(775, 'Netherite Pickaxe', '/items/minecraft_netherite_pickaxe.png'),
(776, 'Cut Red Sandstone Slab', '/items/minecraft_cut_red_sandstone_slab.png'),
(777, 'Bamboo Stairs', '/items/minecraft_bamboo_stairs.png'),
(778, 'Jungle Hanging Sign', '/items/minecraft_jungle_hanging_sign.png'),
(779, 'Stripped Jungle Log', '/items/minecraft_stripped_jungle_log.png'),
(780, 'Prismarine Brick Slab', '/items/minecraft_prismarine_brick_slab.png'),
(781, 'Jungle Sign', '/items/minecraft_jungle_sign.png'),
(782, 'Jungle Chest Boat', '/items/minecraft_jungle_chest_boat.png'),
(783, 'Jungle Boat', '/items/minecraft_jungle_boat.png'),
(784, 'Melon Seeds', '/items/minecraft_melon_seeds.png'),
(785, 'Glistering Melon Slice', '/items/minecraft_glistering_melon_slice.png'),
(786, 'Vex Armor Trim Smithing Template', '/items/minecraft_vex_armor_trim_smithing_template.png'),
(787, 'Crimson Stairs', '/items/minecraft_crimson_stairs.png'),
(788, 'Lime Concrete Powder', '/items/minecraft_lime_concrete_powder.png'),
(789, 'Cherry Wood', '/items/minecraft_cherry_wood.png'),
(790, 'Cherry Log', '/items/minecraft_cherry_log.png'),
(791, 'Pink Tulip', '/items/minecraft_pink_tulip.png'),
(792, 'Light Blue Stained Glass', '/items/minecraft_light_blue_stained_glass.png'),
(793, 'White Stained Glass Pane', '/items/minecraft_white_stained_glass_pane.png'),
(794, 'Prismarine Wall', '/items/minecraft_prismarine_wall.png'),
(795, 'Stripped Spruce Wood', '/items/minecraft_stripped_spruce_wood.png'),
(796, 'Snow', '/items/minecraft_snow.png'),
(797, 'Snow Block', '/items/minecraft_snow_block.png'),
(798, 'Cake', '/items/minecraft_cake.png'),
(799, 'Milk Bucket', '/items/minecraft_milk_bucket.png'),
(800, 'Green Candle', '/items/minecraft_green_candle.png'),
(801, 'Mangrove Pressure Plate', '/items/minecraft_mangrove_pressure_plate.png'),
(802, 'Birch Fence', '/items/minecraft_birch_fence.png'),
(803, 'Red Concrete Powder', '/items/minecraft_red_concrete_powder.png'),
(804, 'Fermented Spider Eye', '/items/minecraft_fermented_spider_eye.png'),
(805, 'Spider Eye', '/items/minecraft_spider_eye.png'),
(806, 'Jungle Wood', '/items/minecraft_jungle_wood.png'),
(807, 'Jungle Log', '/items/minecraft_jungle_log.png'),
(808, 'Blue Glazed Terracotta', '/items/minecraft_blue_glazed_terracotta.png'),
(809, 'Dark Oak Button', '/items/minecraft_dark_oak_button.png'),
(810, 'Smooth Red Sandstone Stairs', '/items/minecraft_smooth_red_sandstone_stairs.png'),
(811, 'Mud Brick Wall', '/items/minecraft_mud_brick_wall.png'),
(812, 'Cherry Stairs', '/items/minecraft_cherry_stairs.png'),
(813, 'Wild Armor Trim Smithing Template', '/items/minecraft_wild_armor_trim_smithing_template.png'),
(814, 'Leather Leggings', '/items/minecraft_leather_leggings.png'),
(815, 'Lilac', '/items/minecraft_lilac.png'),
(816, 'Spruce Sign', '/items/minecraft_spruce_sign.png'),
(817, 'Beacon', '/items/minecraft_beacon.png'),
(818, 'Nether Star', '/items/minecraft_nether_star.png'),
(819, 'Brewing Stand', '/items/minecraft_brewing_stand.png'),
(820, 'Magenta Candle', '/items/minecraft_magenta_candle.png'),
(821, 'Lapis Ore', '/items/minecraft_lapis_ore.png'),
(822, 'Mangrove Stairs', '/items/minecraft_mangrove_stairs.png'),
(823, 'Mossy Stone Brick Slab', '/items/minecraft_mossy_stone_brick_slab.png'),
(824, 'Acacia Stairs', '/items/minecraft_acacia_stairs.png'),
(825, 'Bread', '/items/minecraft_bread.png'),
(826, 'White Glazed Terracotta', '/items/minecraft_white_glazed_terracotta.png'),
(827, 'Snowball', '/items/minecraft_snowball.png'),
(828, 'Pitcher Plant', '/items/minecraft_pitcher_plant.png'),
(829, 'Light Blue Glazed Terracotta', '/items/minecraft_light_blue_glazed_terracotta.png'),
(830, 'Mossy Stone Brick Wall', '/items/minecraft_mossy_stone_brick_wall.png'),
(831, 'Lime Banner', '/items/minecraft_lime_banner.png'),
(832, 'Raw Gold Block', '/items/minecraft_raw_gold_block.png'),
(833, 'Light Gray Banner', '/items/minecraft_light_gray_banner.png'),
(834, 'Netherite Leggings', '/items/minecraft_netherite_leggings.png'),
(835, 'Warped Hanging Sign', '/items/minecraft_warped_hanging_sign.png'),
(836, 'Purpur Stairs', '/items/minecraft_purpur_stairs.png'),
(837, 'Coal Block', '/items/minecraft_coal_block.png'),
(838, 'Red Candle', '/items/minecraft_red_candle.png'),
(839, 'Gray Banner', '/items/minecraft_gray_banner.png'),
(840, 'Lectern', '/items/minecraft_lectern.png'),
(841, 'Deepslate Coal Ore', '/items/minecraft_deepslate_coal_ore.png'),
(842, 'Cornflower', '/items/minecraft_cornflower.png'),
(843, 'Mangrove Fence Gate', '/items/minecraft_mangrove_fence_gate.png'),
(844, 'Light Blue Stained Glass Pane', '/items/minecraft_light_blue_stained_glass_pane.png'),
(845, 'Carrot On A Stick', '/items/minecraft_carrot_on_a_stick.png'),
(846, 'Blue Concrete Powder', '/items/minecraft_blue_concrete_powder.png'),
(847, 'Skull Banner Pattern', '/items/minecraft_skull_banner_pattern.png'),
(848, 'Wither Skeleton Skull', '/items/minecraft_wither_skeleton_skull.png'),
(849, 'Mojang Banner Pattern', '/items/minecraft_mojang_banner_pattern.png'),
(850, 'Enchanted Golden Apple', '/items/minecraft_enchanted_golden_apple.png'),
(851, 'Tinted Glass', '/items/minecraft_tinted_glass.png'),
(852, 'Red Tulip', '/items/minecraft_red_tulip.png'),
(853, 'Spectral Arrow', '/items/minecraft_spectral_arrow.png'),
(854, 'Glowstone Dust', '/items/minecraft_glowstone_dust.png'),
(855, 'Mangrove Trapdoor', '/items/minecraft_mangrove_trapdoor.png'),
(856, 'Stripped Cherry Wood', '/items/minecraft_stripped_cherry_wood.png'),
(857, 'Netherite Boots', '/items/minecraft_netherite_boots.png'),
(858, 'Birch Hanging Sign', '/items/minecraft_birch_hanging_sign.png'),
(859, 'Black Candle', '/items/minecraft_black_candle.png'),
(860, 'Silence Armor Trim Smithing Template', '/items/minecraft_silence_armor_trim_smithing_template.png'),
(861, 'Green Concrete Powder', '/items/minecraft_green_concrete_powder.png'),
(862, 'Birch Trapdoor', '/items/minecraft_birch_trapdoor.png'),
(863, 'Leather Horse Armor', '/items/minecraft_leather_horse_armor.png'),
(864, 'Spruce Wood', '/items/minecraft_spruce_wood.png'),
(865, 'Spruce Log', '/items/minecraft_spruce_log.png'),
(866, 'Detector Rail', '/items/minecraft_detector_rail.png'),
(867, 'Yellow Candle', '/items/minecraft_yellow_candle.png'),
(868, 'Acacia Chest Boat', '/items/minecraft_acacia_chest_boat.png'),
(869, 'Stonecutter', '/items/minecraft_stonecutter.png'),
(870, 'Cyan Terracotta', '/items/minecraft_cyan_terracotta.png'),
(871, 'Lime Terracotta', '/items/minecraft_lime_terracotta.png'),
(872, 'Golden Apple', '/items/minecraft_golden_apple.png'),
(873, 'Apple', '/items/minecraft_apple.png'),
(874, 'Iron Trapdoor', '/items/minecraft_iron_trapdoor.png'),
(875, 'White Stained Glass', '/items/minecraft_white_stained_glass.png'),
(876, 'Daylight Detector', '/items/minecraft_daylight_detector.png'),
(877, 'Rail', '/items/minecraft_rail.png'),
(878, 'Stripped Jungle Wood', '/items/minecraft_stripped_jungle_wood.png'),
(879, 'Flower Banner Pattern', '/items/minecraft_flower_banner_pattern.png'),
(880, 'Diamond Boots', '/items/minecraft_diamond_boots.png'),
(881, 'Warped Stairs', '/items/minecraft_warped_stairs.png'),
(882, 'Cracked Stone Bricks', '/items/minecraft_cracked_stone_bricks.png'),
(883, 'Oak Slab', '/items/minecraft_oak_slab.png'),
(884, 'Leather Boots', '/items/minecraft_leather_boots.png'),
(885, 'Stripped Crimson Hyphae', '/items/minecraft_stripped_crimson_hyphae.png'),
(886, 'Cherry Door', '/items/minecraft_cherry_door.png'),
(887, 'Cherry Chest Boat', '/items/minecraft_cherry_chest_boat.png'),
(888, 'Cherry Boat', '/items/minecraft_cherry_boat.png'),
(889, 'White Concrete Powder', '/items/minecraft_white_concrete_powder.png'),
(890, 'Anvil', '/items/minecraft_anvil.png'),
(891, 'Warped Slab', '/items/minecraft_warped_slab.png'),
(892, 'Host Armor Trim Smithing Template', '/items/minecraft_host_armor_trim_smithing_template.png'),
(893, 'Oak Hanging Sign', '/items/minecraft_oak_hanging_sign.png'),
(894, 'Light Gray Concrete Powder', '/items/minecraft_light_gray_concrete_powder.png'),
(895, 'Map', '/items/minecraft_map.png'),
(896, 'Sponge', '/items/minecraft_sponge.png'),
(897, 'Wet Sponge', '/items/minecraft_wet_sponge.png'),
(898, 'Orange Tulip', '/items/minecraft_orange_tulip.png'),
(899, 'Cyan Candle', '/items/minecraft_cyan_candle.png'),
(900, 'Jungle Door', '/items/minecraft_jungle_door.png'),
(901, 'Conduit', '/items/minecraft_conduit.png'),
(902, 'Nautilus Shell', '/items/minecraft_nautilus_shell.png'),
(903, 'Heart Of The Sea', '/items/minecraft_heart_of_the_sea.png'),
(904, 'Muddy Mangrove Roots', '/items/minecraft_muddy_mangrove_roots.png'),
(905, 'Mangrove Roots', '/items/minecraft_mangrove_roots.png'),
(906, 'Iron Door', '/items/minecraft_iron_door.png'),
(907, 'Armor Stand', '/items/minecraft_armor_stand.png'),
(908, 'Magenta Concrete Powder', '/items/minecraft_magenta_concrete_powder.png'),
(909, 'Diamond Leggings', '/items/minecraft_diamond_leggings.png'),
(910, 'Lime Glazed Terracotta', '/items/minecraft_lime_glazed_terracotta.png'),
(911, 'Dark Oak Slab', '/items/minecraft_dark_oak_slab.png'),
(912, 'Acacia Trapdoor', '/items/minecraft_acacia_trapdoor.png'),
(913, 'Diamond Helmet', '/items/minecraft_diamond_helmet.png'),
(914, 'Green Banner', '/items/minecraft_green_banner.png'),
(915, 'Jungle Pressure Plate', '/items/minecraft_jungle_pressure_plate.png'),
(916, 'Black Stained Glass', '/items/minecraft_black_stained_glass.png'),
(917, 'Azure Bluet', '/items/minecraft_azure_bluet.png'),
(918, 'Nether Brick Fence', '/items/minecraft_nether_brick_fence.png'),
(919, 'Repeater', '/items/minecraft_repeater.png'),
(920, 'Tide Armor Trim Smithing Template', '/items/minecraft_tide_armor_trim_smithing_template.png'),
(921, 'Ice', '/items/minecraft_ice.png'),
(922, 'Black Concrete Powder', '/items/minecraft_black_concrete_powder.png'),
(923, 'Cyan Glazed Terracotta', '/items/minecraft_cyan_glazed_terracotta.png'),
(924, 'Polished Blackstone Pressure Plate', '/items/minecraft_polished_blackstone_pressure_plate.png'),
(925, 'Jungle Button', '/items/minecraft_jungle_button.png'),
(926, 'Spruce Button', '/items/minecraft_spruce_button.png'),
(927, 'Polished Blackstone Button', '/items/minecraft_polished_blackstone_button.png'),
(928, 'Recovery Compass', '/items/minecraft_recovery_compass.png'),
(929, 'Echo Shard', '/items/minecraft_echo_shard.png'),
(930, 'Mangrove Leaves', '/items/minecraft_mangrove_leaves.png'),
(931, 'Flowering Azalea Leaves', '/items/minecraft_flowering_azalea_leaves.png'),
(932, 'Spruce Leaves', '/items/minecraft_spruce_leaves.png'),
(933, 'Warped Wart Block', '/items/minecraft_warped_wart_block.png'),
(934, 'Oak Leaves', '/items/minecraft_oak_leaves.png'),
(935, 'Birch Leaves', '/items/minecraft_birch_leaves.png'),
(936, 'Azalea Leaves', '/items/minecraft_azalea_leaves.png'),
(937, 'Cherry Leaves', '/items/minecraft_cherry_leaves.png'),
(938, 'Acacia Leaves', '/items/minecraft_acacia_leaves.png'),
(939, 'Dark Oak Leaves', '/items/minecraft_dark_oak_leaves.png'),
(940, 'Jungle Leaves', '/items/minecraft_jungle_leaves.png'),
(941, 'Glow Berries', '/items/minecraft_glow_berries.png'),
(942, 'Sweet Berries', '/items/minecraft_sweet_berries.png'),
(943, 'Pufferfish', '/items/minecraft_pufferfish.png'),
(944, 'Tropical Fish', '/items/minecraft_tropical_fish.png'),
(945, 'Suspicious Sand', '/items/minecraft_suspicious_sand.png'),
(946, 'Pitcher Pod', '/items/minecraft_pitcher_pod.png'),
(947, 'Beetroot Seeds', '/items/minecraft_beetroot_seeds.png'),
(948, 'Torchflower Seeds', '/items/minecraft_torchflower_seeds.png'),
(949, 'Wheat Seeds', '/items/minecraft_wheat_seeds.png'),
(950, 'Music Disc Pigstep', '/items/minecraft_music_disc_pigstep.png'),
(951, 'Music Disc Stal', '/items/minecraft_music_disc_stal.png'),
(952, 'Music Disc Blocks', '/items/minecraft_music_disc_blocks.png'),
(953, 'Music Disc Ward', '/items/minecraft_music_disc_ward.png'),
(954, 'Music Disc Cat', '/items/minecraft_music_disc_cat.png'),
(955, 'Music Disc Wait', '/items/minecraft_music_disc_wait.png'),
(956, 'Music Disc Mall', '/items/minecraft_music_disc_mall.png'),
(957, 'Music Disc 11', '/items/minecraft_music_disc_11.png'),
(958, 'Music Disc Far', '/items/minecraft_music_disc_far.png'),
(959, 'Music Disc Otherside', '/items/minecraft_music_disc_otherside.png'),
(960, 'Music Disc Relic', '/items/minecraft_music_disc_relic.png'),
(961, 'Music Disc Strad', '/items/minecraft_music_disc_strad.png'),
(962, 'Music Disc Chirp', '/items/minecraft_music_disc_chirp.png'),
(963, 'Music Disc 13', '/items/minecraft_music_disc_13.png'),
(964, 'Music Disc Mellohi', '/items/minecraft_music_disc_mellohi.png'),
(965, 'Tropical Fish Bucket', '/items/minecraft_tropical_fish_bucket.png'),
(966, 'Written Book', '/items/minecraft_written_book.png'),
(967, 'Snort Pottery Sherd', '/items/minecraft_snort_pottery_sherd.png'),
(968, 'Friend Pottery Sherd', '/items/minecraft_friend_pottery_sherd.png'),
(969, 'Miner Pottery Sherd', '/items/minecraft_miner_pottery_sherd.png'),
(970, 'Brewer Pottery Sherd', '/items/minecraft_brewer_pottery_sherd.png'),
(971, 'Heart Pottery Sherd', '/items/minecraft_heart_pottery_sherd.png'),
(972, 'Angler Pottery Sherd', '/items/minecraft_angler_pottery_sherd.png'),
(973, 'Explorer Pottery Sherd', '/items/minecraft_explorer_pottery_sherd.png'),
(974, 'Blade Pottery Sherd', '/items/minecraft_blade_pottery_sherd.png'),
(975, 'Skull Pottery Sherd', '/items/minecraft_skull_pottery_sherd.png'),
(976, 'Plenty Pottery Sherd', '/items/minecraft_plenty_pottery_sherd.png'),
(977, 'Danger Pottery Sherd', '/items/minecraft_danger_pottery_sherd.png'),
(978, 'Sheaf Pottery Sherd', '/items/minecraft_sheaf_pottery_sherd.png'),
(979, 'Howl Pottery Sherd', '/items/minecraft_howl_pottery_sherd.png'),
(980, 'Arms Up Pottery Sherd', '/items/minecraft_arms_up_pottery_sherd.png'),
(981, 'Shelter Pottery Sherd', '/items/minecraft_shelter_pottery_sherd.png'),
(982, 'Archer Pottery Sherd', '/items/minecraft_archer_pottery_sherd.png'),
(983, 'Prize Pottery Sherd', '/items/minecraft_prize_pottery_sherd.png'),
(984, 'Burn Pottery Sherd', '/items/minecraft_burn_pottery_sherd.png'),
(985, 'Mourner Pottery Sherd', '/items/minecraft_mourner_pottery_sherd.png'),
(986, 'Heartbreak Pottery Sherd', '/items/minecraft_heartbreak_pottery_sherd.png'),
(987, 'Oak Sapling', '/items/minecraft_oak_sapling.png'),
(988, 'Jungle Sapling', '/items/minecraft_jungle_sapling.png'),
(989, 'Mangrove Propagule', '/items/minecraft_mangrove_propagule.png'),
(990, 'Dark Oak Sapling', '/items/minecraft_dark_oak_sapling.png'),
(991, 'Cherry Sapling', '/items/minecraft_cherry_sapling.png'),
(992, 'Flowering Azalea', '/items/minecraft_flowering_azalea.png'),
(993, 'Azalea', '/items/minecraft_azalea.png'),
(994, 'Birch Sapling', '/items/minecraft_birch_sapling.png'),
(995, 'Acacia Sapling', '/items/minecraft_acacia_sapling.png'),
(996, 'Spruce Sapling', '/items/minecraft_spruce_sapling.png'),
(997, 'Trident', '/items/minecraft_trident.png'),
(998, 'Zombie Head', '/items/minecraft_zombie_head.png'),
(999, 'Piglin Head', '/items/minecraft_piglin_head.png'),
(1000, 'Dragon Head', '/items/minecraft_dragon_head.png'),
(1001, 'Skeleton Skull', '/items/minecraft_skeleton_skull.png'),
(1002, 'Player Head', '/items/minecraft_player_head.png'),
(1003, 'Petrified Oak Slab', '/items/minecraft_petrified_oak_slab.png'),
(1004, 'Chorus Flower', '/items/minecraft_chorus_flower.png'),
(1005, 'Spore Blossom', '/items/minecraft_spore_blossom.png'),
(1006, 'Podzol', '/items/minecraft_podzol.png'),
(1007, 'Rooted Dirt', '/items/minecraft_rooted_dirt.png'),
(1008, 'Grass Block', '/items/minecraft_grass_block.png'),
(1009, 'Mycelium', '/items/minecraft_mycelium.png'),
(1010, 'Gilded Blackstone', '/items/minecraft_gilded_blackstone.png'),
(1011, 'Bell', '/items/minecraft_bell.png'),
(1012, 'Chipped Anvil', '/items/minecraft_chipped_anvil.png'),
(1013, 'Damaged Anvil', '/items/minecraft_damaged_anvil.png'),
(1014, 'Enchanted Book', '/items/minecraft_enchanted_book.png'),
(1015, 'Knowledge Book', '/items/minecraft_knowledge_book.png'),
(1016, 'Tipped Arrow', '/items/minecraft_tipped_arrow.png'),
(1017, 'Soul Soil', '/items/minecraft_soul_soil.png'),
(1018, 'Soul Sand', '/items/minecraft_soul_sand.png'),
(1019, 'Saddle', '/items/minecraft_saddle.png'),
(1020, 'Diamond Horse Armor', '/items/minecraft_diamond_horse_armor.png'),
(1021, 'Name Tag', '/items/minecraft_name_tag.png'),
(1022, 'Suspicious Stew', '/items/minecraft_suspicious_stew.png'),
(1023, 'Sculk Catalyst', '/items/minecraft_sculk_catalyst.png'),
(1024, 'Sculk', '/items/minecraft_sculk.png'),
(1025, 'Experience Bottle', '/items/minecraft_experience_bottle.png'),
(1026, 'Potion', '/items/minecraft_potion.png'),
(1027, 'Crimson Nylium', '/items/minecraft_crimson_nylium.png'),
(1028, 'Crimson Fungus', '/items/minecraft_crimson_fungus.png'),
(1029, 'Crimson Roots', '/items/minecraft_crimson_roots.png'),
(1030, 'Piglin Banner Pattern', '/items/minecraft_piglin_banner_pattern.png'),
(1031, 'Rotten Flesh', '/items/minecraft_rotten_flesh.png'),
(1032, 'Gameplay/fishing/fish', '/items/minecraft_gameplay/fishing/fish.png'),
(1033, 'Totem Of Undying', '/items/minecraft_totem_of_undying.png'),
(1034, 'Creeper Drop Music Discs', '/items/minecraft_creeper_drop_music_discs.png'),
(1035, 'Phantom Membrane', '/items/minecraft_phantom_membrane.png'),
(1036, 'Pearlescent Froglight', '/items/minecraft_pearlescent_froglight.png'),
(1037, 'Verdant Froglight', '/items/minecraft_verdant_froglight.png'),
(1038, 'Ochre Froglight', '/items/minecraft_ochre_froglight.png'),
(1039, 'Seagrass', '/items/minecraft_seagrass.png'),
(1040, 'Rabbit Foot', '/items/minecraft_rabbit_foot.png'),
(1041, 'Lily Pad', '/items/minecraft_lily_pad.png'),
(1042, 'Splash Potion', '/items/minecraft_splash_potion.png'),
(1043, 'Gameplay/fishing/junk', '/items/minecraft_gameplay/fishing/junk.png'),
(1044, 'Gameplay/fishing/treasure', '/items/minecraft_gameplay/fishing/treasure.png');
