INSERT INTO item (id, name, image) VALUES 
(1, 'Dropper', '/items/minecraft:dropper.png'),
(2, 'Cobblestone', '/items/minecraft:cobblestone.png'),
(3, 'Redstone', '/items/minecraft:redstone.png'),
(4, 'Jungle Fence Gate', '/items/minecraft:jungle_fence_gate.png'),
(5, 'Stick', '/items/minecraft:stick.png'),
(6, 'Jungle Planks', '/items/minecraft:jungle_planks.png'),
(7, 'Stone Pressure Plate', '/items/minecraft:stone_pressure_plate.png'),
(8, 'Stone', '/items/minecraft:stone.png'),
(9, 'Bamboo Block', '/items/minecraft:bamboo_block.png'),
(10, 'Bamboo', '/items/minecraft:bamboo.png'),
(11, 'Cooked Porkchop', '/items/minecraft:cooked_porkchop.png'),
(12, 'Porkchop', '/items/minecraft:porkchop.png'),
(13, 'Polished Deepslate', '/items/minecraft:polished_deepslate.png'),
(14, 'Cobbled Deepslate', '/items/minecraft:cobbled_deepslate.png'),
(15, 'Pink Bed', '/items/minecraft:pink_bed.png'),
(16, 'Pink Dye', '/items/minecraft:pink_dye.png'),
(17, 'Black Bed', '/items/minecraft:black_bed.png'),
(18, 'Blue Bed', '/items/minecraft:blue_bed.png'),
(19, 'Brown Bed', '/items/minecraft:brown_bed.png'),
(20, 'Cyan Bed', '/items/minecraft:cyan_bed.png'),
(21, 'Gray Bed', '/items/minecraft:gray_bed.png'),
(22, 'Green Bed', '/items/minecraft:green_bed.png'),
(23, 'Light Blue Bed', '/items/minecraft:light_blue_bed.png'),
(24, 'Light Gray Bed', '/items/minecraft:light_gray_bed.png'),
(25, 'Lime Bed', '/items/minecraft:lime_bed.png'),
(26, 'Magenta Bed', '/items/minecraft:magenta_bed.png'),
(27, 'Orange Bed', '/items/minecraft:orange_bed.png'),
(28, 'Purple Bed', '/items/minecraft:purple_bed.png'),
(29, 'Red Bed', '/items/minecraft:red_bed.png'),
(30, 'Yellow Bed', '/items/minecraft:yellow_bed.png'),
(31, 'White Bed', '/items/minecraft:white_bed.png'),
(32, 'Dune Armor Trim Smithing Template', '/items/minecraft:dune_armor_trim_smithing_template.png'),
(33, 'Diamond', '/items/minecraft:diamond.png'),
(34, 'Sandstone', '/items/minecraft:sandstone.png'),
(35, 'Diorite Stairs', '/items/minecraft:diorite_stairs.png'),
(36, 'Diorite', '/items/minecraft:diorite.png'),
(37, 'Acacia Door', '/items/minecraft:acacia_door.png'),
(38, 'Acacia Planks', '/items/minecraft:acacia_planks.png'),
(39, 'Spruce Slab', '/items/minecraft:spruce_slab.png'),
(40, 'Spruce Planks', '/items/minecraft:spruce_planks.png'),
(41, 'Cracked Deepslate Bricks', '/items/minecraft:cracked_deepslate_bricks.png'),
(42, 'Deepslate Bricks', '/items/minecraft:deepslate_bricks.png'),
(43, 'Gray Terracotta', '/items/minecraft:gray_terracotta.png'),
(44, 'Terracotta', '/items/minecraft:terracotta.png'),
(45, 'Gray Dye', '/items/minecraft:gray_dye.png'),
(46, 'End Stone Brick Slab', '/items/minecraft:end_stone_brick_slab.png'),
(47, 'End Stone', '/items/minecraft:end_stone.png'),
(48, 'Red Glazed Terracotta', '/items/minecraft:red_glazed_terracotta.png'),
(49, 'Red Terracotta', '/items/minecraft:red_terracotta.png'),
(50, 'Gold Ingot', '/items/minecraft:gold_ingot.png'),
(51, 'Gold Ore', '/items/minecraft:gold_ore.png'),
(52, 'Cobbled Deepslate Stairs', '/items/minecraft:cobbled_deepslate_stairs.png'),
(53, 'Cobbled Deepslate Wall', '/items/minecraft:cobbled_deepslate_wall.png'),
(54, 'Smooth Red Sandstone Slab', '/items/minecraft:smooth_red_sandstone_slab.png'),
(55, 'Smooth Red Sandstone', '/items/minecraft:smooth_red_sandstone.png'),
(56, 'Brown Concrete Powder', '/items/minecraft:brown_concrete_powder.png'),
(57, 'Brown Dye', '/items/minecraft:brown_dye.png'),
(58, 'Sand', '/items/minecraft:sand.png'),
(59, 'Gravel', '/items/minecraft:gravel.png'),
(60, 'Pink Terracotta', '/items/minecraft:pink_terracotta.png'),
(61, 'Smooth Basalt', '/items/minecraft:smooth_basalt.png'),
(62, 'Basalt', '/items/minecraft:basalt.png'),
(63, 'Furnace Minecart', '/items/minecraft:furnace_minecart.png'),
(64, 'Furnace', '/items/minecraft:furnace.png'),
(65, 'Minecart', '/items/minecraft:minecart.png'),
(66, 'Dark Oak Planks', '/items/minecraft:dark_oak_planks.png'),
(67, 'Deepslate Tile Stairs', '/items/minecraft:deepslate_tile_stairs.png'),
(68, 'Bucket', '/items/minecraft:bucket.png'),
(69, 'Iron Ingot', '/items/minecraft:iron_ingot.png'),
(70, 'Blue Stained Glass Pane', '/items/minecraft:blue_stained_glass_pane.png'),
(71, 'Blue Stained Glass', '/items/minecraft:blue_stained_glass.png'),
(72, 'Lime Dye', '/items/minecraft:lime_dye.png'),
(73, 'Sea Pickle', '/items/minecraft:sea_pickle.png'),
(74, 'Cobbled Deepslate Slab', '/items/minecraft:cobbled_deepslate_slab.png'),
(75, 'Beehive', '/items/minecraft:beehive.png'),
(76, 'Honeycomb', '/items/minecraft:honeycomb.png'),
(77, 'Campfire', '/items/minecraft:campfire.png'),
(78, 'Lime Wool', '/items/minecraft:lime_wool.png'),
(79, 'Black Wool', '/items/minecraft:black_wool.png'),
(80, 'Blue Wool', '/items/minecraft:blue_wool.png'),
(81, 'Brown Wool', '/items/minecraft:brown_wool.png'),
(82, 'Cyan Wool', '/items/minecraft:cyan_wool.png'),
(83, 'Gray Wool', '/items/minecraft:gray_wool.png'),
(84, 'Green Wool', '/items/minecraft:green_wool.png'),
(85, 'Light Blue Wool', '/items/minecraft:light_blue_wool.png'),
(86, 'Light Gray Wool', '/items/minecraft:light_gray_wool.png'),
(87, 'Magenta Wool', '/items/minecraft:magenta_wool.png'),
(88, 'Orange Wool', '/items/minecraft:orange_wool.png'),
(89, 'Pink Wool', '/items/minecraft:pink_wool.png'),
(90, 'Purple Wool', '/items/minecraft:purple_wool.png'),
(91, 'Red Wool', '/items/minecraft:red_wool.png'),
(92, 'Yellow Wool', '/items/minecraft:yellow_wool.png'),
(93, 'White Wool', '/items/minecraft:white_wool.png'),
(94, 'White Terracotta', '/items/minecraft:white_terracotta.png'),
(95, 'White Dye', '/items/minecraft:white_dye.png'),
(96, 'Chiseled Red Sandstone', '/items/minecraft:chiseled_red_sandstone.png'),
(97, 'Red Sandstone Slab', '/items/minecraft:red_sandstone_slab.png'),
(98, 'White Banner', '/items/minecraft:white_banner.png'),
(99, 'Light Gray Stained Glass Pane', '/items/minecraft:light_gray_stained_glass_pane.png'),
(100, 'Glass Pane', '/items/minecraft:glass_pane.png'),
(101, 'Light Gray Dye', '/items/minecraft:light_gray_dye.png'),
(102, 'Powered Rail', '/items/minecraft:powered_rail.png'),
(103, 'Waxed Oxidized Copper', '/items/minecraft:waxed_oxidized_copper.png'),
(104, 'Oxidized Copper', '/items/minecraft:oxidized_copper.png'),
(105, 'Oak Wood', '/items/minecraft:oak_wood.png'),
(106, 'Oak Log', '/items/minecraft:oak_log.png'),
(107, 'Red Dye', '/items/minecraft:red_dye.png'),
(108, 'Lapis Block', '/items/minecraft:lapis_block.png'),
(109, 'Lapis Lazuli', '/items/minecraft:lapis_lazuli.png'),
(110, 'Blackstone Stairs', '/items/minecraft:blackstone_stairs.png'),
(111, 'Blackstone', '/items/minecraft:blackstone.png'),
(112, 'Honey Bottle', '/items/minecraft:honey_bottle.png'),
(113, 'Honey Block', '/items/minecraft:honey_block.png'),
(114, 'Glass Bottle', '/items/minecraft:glass_bottle.png'),
(115, 'Blue Dye', '/items/minecraft:blue_dye.png'),
(116, 'Brown Terracotta', '/items/minecraft:brown_terracotta.png'),
(117, 'Cobblestone Wall', '/items/minecraft:cobblestone_wall.png'),
(118, 'Cauldron', '/items/minecraft:cauldron.png'),
(119, 'Cut Copper Stairs', '/items/minecraft:cut_copper_stairs.png'),
(120, 'Cut Copper', '/items/minecraft:cut_copper.png'),
(121, 'Oak Fence Gate', '/items/minecraft:oak_fence_gate.png'),
(122, 'Oak Planks', '/items/minecraft:oak_planks.png'),
(123, 'Blue Terracotta', '/items/minecraft:blue_terracotta.png'),
(124, 'Deepslate Gold Ore', '/items/minecraft:deepslate_gold_ore.png'),
(125, 'Red Sandstone Wall', '/items/minecraft:red_sandstone_wall.png'),
(126, 'Red Sandstone', '/items/minecraft:red_sandstone.png'),
(127, 'Stone Shovel', '/items/minecraft:stone_shovel.png'),
(128, 'Packed Mud', '/items/minecraft:packed_mud.png'),
(129, 'Mud', '/items/minecraft:mud.png'),
(130, 'Wheat', '/items/minecraft:wheat.png'),
(131, 'Glass', '/items/minecraft:glass.png'),
(132, 'Gold Nugget', '/items/minecraft:gold_nugget.png'),
(133, 'Jungle Stairs', '/items/minecraft:jungle_stairs.png'),
(134, 'Spruce Stairs', '/items/minecraft:spruce_stairs.png'),
(135, 'Polished Blackstone Slab', '/items/minecraft:polished_blackstone_slab.png'),
(136, 'Spruce Fence Gate', '/items/minecraft:spruce_fence_gate.png'),
(137, 'Polished Blackstone Stairs', '/items/minecraft:polished_blackstone_stairs.png'),
(138, 'Polished Blackstone', '/items/minecraft:polished_blackstone.png'),
(139, 'Oxeye Daisy', '/items/minecraft:oxeye_daisy.png'),
(140, 'Leather Chestplate', '/items/minecraft:leather_chestplate.png'),
(141, 'Leather', '/items/minecraft:leather.png'),
(142, 'Golden Carrot', '/items/minecraft:golden_carrot.png'),
(143, 'Carrot', '/items/minecraft:carrot.png'),
(144, 'Smooth Quartz Slab', '/items/minecraft:smooth_quartz_slab.png'),
(145, 'Smooth Quartz', '/items/minecraft:smooth_quartz.png'),
(146, 'Oxidized Cut Copper Slab', '/items/minecraft:oxidized_cut_copper_slab.png'),
(147, 'Oxidized Cut Copper', '/items/minecraft:oxidized_cut_copper.png'),
(148, 'Magenta Glazed Terracotta', '/items/minecraft:magenta_glazed_terracotta.png'),
(149, 'Magenta Terracotta', '/items/minecraft:magenta_terracotta.png'),
(150, 'Deepslate Brick Wall', '/items/minecraft:deepslate_brick_wall.png'),
(151, 'Fletching Table', '/items/minecraft:fletching_table.png'),
(152, 'Flint', '/items/minecraft:flint.png'),
(153, 'Glow Item Frame', '/items/minecraft:glow_item_frame.png'),
(154, 'Item Frame', '/items/minecraft:item_frame.png'),
(155, 'Glow Ink Sac', '/items/minecraft:glow_ink_sac.png'),
(156, 'Stripped Dark Oak Wood', '/items/minecraft:stripped_dark_oak_wood.png'),
(157, 'Stripped Dark Oak Log', '/items/minecraft:stripped_dark_oak_log.png'),
(158, 'Stone Bricks', '/items/minecraft:stone_bricks.png'),
(159, 'Deepslate Brick Stairs', '/items/minecraft:deepslate_brick_stairs.png'),
(160, 'Brick Wall', '/items/minecraft:brick_wall.png'),
(161, 'Bricks', '/items/minecraft:bricks.png'),
(162, 'Redstone Lamp', '/items/minecraft:redstone_lamp.png'),
(163, 'Glowstone', '/items/minecraft:glowstone.png'),
(164, 'Brown Banner', '/items/minecraft:brown_banner.png'),
(165, 'Light Gray Stained Glass', '/items/minecraft:light_gray_stained_glass.png'),
(166, 'Blue Banner', '/items/minecraft:blue_banner.png'),
(167, 'Crimson Door', '/items/minecraft:crimson_door.png'),
(168, 'Crimson Planks', '/items/minecraft:crimson_planks.png'),
(169, 'Clock', '/items/minecraft:clock.png'),
(170, 'Light Blue Banner', '/items/minecraft:light_blue_banner.png'),
(171, 'Purpur Block', '/items/minecraft:purpur_block.png'),
(172, 'Popped Chorus Fruit', '/items/minecraft:popped_chorus_fruit.png'),
(173, 'Cut Red Sandstone', '/items/minecraft:cut_red_sandstone.png'),
(174, 'Sandstone Wall', '/items/minecraft:sandstone_wall.png'),
(175, 'Warped Hyphae', '/items/minecraft:warped_hyphae.png'),
(176, 'Warped Stem', '/items/minecraft:warped_stem.png'),
(177, 'Waxed Oxidized Cut Copper', '/items/minecraft:waxed_oxidized_cut_copper.png'),
(178, 'Diorite Slab', '/items/minecraft:diorite_slab.png'),
(179, 'Green Dye', '/items/minecraft:green_dye.png'),
(180, 'Mossy Stone Bricks', '/items/minecraft:mossy_stone_bricks.png'),
(181, 'Moss Block', '/items/minecraft:moss_block.png'),
(182, 'Mangrove Hanging Sign', '/items/minecraft:mangrove_hanging_sign.png'),
(183, 'Stripped Mangrove Log', '/items/minecraft:stripped_mangrove_log.png'),
(184, 'Chain', '/items/minecraft:chain.png'),
(185, 'Cooked Chicken', '/items/minecraft:cooked_chicken.png'),
(186, 'Chicken', '/items/minecraft:chicken.png'),
(187, 'Waxed Exposed Copper', '/items/minecraft:waxed_exposed_copper.png'),
(188, 'Exposed Copper', '/items/minecraft:exposed_copper.png'),
(189, 'Wayfinder Armor Trim Smithing Template', '/items/minecraft:wayfinder_armor_trim_smithing_template.png'),
(190, 'Waxed Exposed Cut Copper Slab', '/items/minecraft:waxed_exposed_cut_copper_slab.png'),
(191, 'Waxed Exposed Cut Copper', '/items/minecraft:waxed_exposed_cut_copper.png'),
(192, 'Baked Potato', '/items/minecraft:baked_potato.png'),
(193, 'Potato', '/items/minecraft:potato.png'),
(194, 'Sugar', '/items/minecraft:sugar.png'),
(195, 'Observer', '/items/minecraft:observer.png'),
(196, 'Quartz', '/items/minecraft:quartz.png'),
(197, 'Pink Banner', '/items/minecraft:pink_banner.png'),
(198, 'Waxed Oxidized Cut Copper Slab', '/items/minecraft:waxed_oxidized_cut_copper_slab.png'),
(199, 'Smooth Sandstone', '/items/minecraft:smooth_sandstone.png'),
(200, 'Dark Oak Trapdoor', '/items/minecraft:dark_oak_trapdoor.png'),
(201, 'Redstone Ore', '/items/minecraft:redstone_ore.png'),
(202, 'Iron Ore', '/items/minecraft:iron_ore.png'),
(203, 'Purple Dye', '/items/minecraft:purple_dye.png'),
(204, 'Waxed Weathered Cut Copper Stairs', '/items/minecraft:waxed_weathered_cut_copper_stairs.png'),
(205, 'Waxed Weathered Copper', '/items/minecraft:waxed_weathered_copper.png'),
(206, 'Candle', '/items/minecraft:candle.png'),
(207, 'String', '/items/minecraft:string.png'),
(208, 'Lantern', '/items/minecraft:lantern.png'),
(209, 'Torch', '/items/minecraft:torch.png'),
(210, 'Iron Nugget', '/items/minecraft:iron_nugget.png'),
(211, 'Polished Granite Stairs', '/items/minecraft:polished_granite_stairs.png'),
(212, 'Polished Granite', '/items/minecraft:polished_granite.png'),
(213, 'Waxed Weathered Cut Copper', '/items/minecraft:waxed_weathered_cut_copper.png'),
(214, 'Mossy Cobblestone Wall', '/items/minecraft:mossy_cobblestone_wall.png'),
(215, 'Mossy Cobblestone', '/items/minecraft:mossy_cobblestone.png'),
(216, 'Light Weighted Pressure Plate', '/items/minecraft:light_weighted_pressure_plate.png'),
(217, 'Green Terracotta', '/items/minecraft:green_terracotta.png'),
(218, 'Cracked Nether Bricks', '/items/minecraft:cracked_nether_bricks.png'),
(219, 'Nether Bricks', '/items/minecraft:nether_bricks.png'),
(220, 'Mossy Cobblestone Stairs', '/items/minecraft:mossy_cobblestone_stairs.png'),
(221, 'Cherry Fence', '/items/minecraft:cherry_fence.png'),
(222, 'Cherry Planks', '/items/minecraft:cherry_planks.png'),
(223, 'Polished Deepslate Stairs', '/items/minecraft:polished_deepslate_stairs.png'),
(224, 'Slime Ball', '/items/minecraft:slime_ball.png'),
(225, 'Slime Block', '/items/minecraft:slime_block.png'),
(226, 'Iron Block', '/items/minecraft:iron_block.png'),
(227, 'Birch Pressure Plate', '/items/minecraft:birch_pressure_plate.png'),
(228, 'Birch Planks', '/items/minecraft:birch_planks.png'),
(229, 'Hopper Minecart', '/items/minecraft:hopper_minecart.png'),
(230, 'Hopper', '/items/minecraft:hopper.png'),
(231, 'Copper Block', '/items/minecraft:copper_block.png'),
(232, 'Copper Ingot', '/items/minecraft:copper_ingot.png'),
(233, 'Nether Brick Slab', '/items/minecraft:nether_brick_slab.png'),
(234, 'End Crystal', '/items/minecraft:end_crystal.png'),
(235, 'Ender Eye', '/items/minecraft:ender_eye.png'),
(236, 'Ghast Tear', '/items/minecraft:ghast_tear.png'),
(237, 'Acacia Boat', '/items/minecraft:acacia_boat.png'),
(238, 'Weathered Cut Copper', '/items/minecraft:weathered_cut_copper.png'),
(239, 'Weathered Copper', '/items/minecraft:weathered_copper.png'),
(240, 'Oak Sign', '/items/minecraft:oak_sign.png'),
(241, 'Polished Blackstone Brick Slab', '/items/minecraft:polished_blackstone_brick_slab.png'),
(242, 'Cyan Carpet', '/items/minecraft:cyan_carpet.png'),
(243, 'Cyan Dye', '/items/minecraft:cyan_dye.png'),
(244, 'Black Carpet', '/items/minecraft:black_carpet.png'),
(245, 'Blue Carpet', '/items/minecraft:blue_carpet.png'),
(246, 'Brown Carpet', '/items/minecraft:brown_carpet.png'),
(247, 'Gray Carpet', '/items/minecraft:gray_carpet.png'),
(248, 'Green Carpet', '/items/minecraft:green_carpet.png'),
(249, 'Light Blue Carpet', '/items/minecraft:light_blue_carpet.png'),
(250, 'Light Gray Carpet', '/items/minecraft:light_gray_carpet.png'),
(251, 'Lime Carpet', '/items/minecraft:lime_carpet.png'),
(252, 'Magenta Carpet', '/items/minecraft:magenta_carpet.png'),
(253, 'Orange Carpet', '/items/minecraft:orange_carpet.png'),
(254, 'Pink Carpet', '/items/minecraft:pink_carpet.png'),
(255, 'Purple Carpet', '/items/minecraft:purple_carpet.png'),
(256, 'Red Carpet', '/items/minecraft:red_carpet.png'),
(257, 'Yellow Carpet', '/items/minecraft:yellow_carpet.png'),
(258, 'White Carpet', '/items/minecraft:white_carpet.png'),
(259, 'Yellow Concrete Powder', '/items/minecraft:yellow_concrete_powder.png'),
(260, 'Yellow Dye', '/items/minecraft:yellow_dye.png'),
(261, 'Diamond Sword', '/items/minecraft:diamond_sword.png'),
(262, 'Mossy Cobblestone Slab', '/items/minecraft:mossy_cobblestone_slab.png'),
(263, 'Waxed Cut Copper Stairs', '/items/minecraft:waxed_cut_copper_stairs.png'),
(264, 'Coarse Dirt', '/items/minecraft:coarse_dirt.png'),
(265, 'Dirt', '/items/minecraft:dirt.png'),
(266, 'Warped Fence', '/items/minecraft:warped_fence.png'),
(267, 'Warped Planks', '/items/minecraft:warped_planks.png'),
(268, 'Raw Iron', '/items/minecraft:raw_iron.png'),
(269, 'Bamboo Pressure Plate', '/items/minecraft:bamboo_pressure_plate.png'),
(270, 'Bamboo Planks', '/items/minecraft:bamboo_planks.png'),
(271, 'Chiseled Stone Bricks', '/items/minecraft:chiseled_stone_bricks.png'),
(272, 'Stone Brick Slab', '/items/minecraft:stone_brick_slab.png'),
(273, 'Andesite', '/items/minecraft:andesite.png'),
(274, 'Brush', '/items/minecraft:brush.png'),
(275, 'Feather', '/items/minecraft:feather.png'),
(276, 'Brown Stained Glass', '/items/minecraft:brown_stained_glass.png'),
(277, 'Cyan Concrete Powder', '/items/minecraft:cyan_concrete_powder.png'),
(278, 'Nether Quartz Ore', '/items/minecraft:nether_quartz_ore.png'),
(279, 'Andesite Wall', '/items/minecraft:andesite_wall.png'),
(280, 'Stone Sword', '/items/minecraft:stone_sword.png'),
(281, 'Waxed Cut Copper', '/items/minecraft:waxed_cut_copper.png'),
(282, 'Waxed Copper Block', '/items/minecraft:waxed_copper_block.png'),
(283, 'Birch Door', '/items/minecraft:birch_door.png'),
(284, 'Redstone Block', '/items/minecraft:redstone_block.png'),
(285, 'Comparator', '/items/minecraft:comparator.png'),
(286, 'Redstone Torch', '/items/minecraft:redstone_torch.png'),
(287, 'Mangrove Door', '/items/minecraft:mangrove_door.png'),
(288, 'Mangrove Planks', '/items/minecraft:mangrove_planks.png'),
(289, 'Crimson Pressure Plate', '/items/minecraft:crimson_pressure_plate.png'),
(290, 'Target', '/items/minecraft:target.png'),
(291, 'Hay Block', '/items/minecraft:hay_block.png'),
(292, 'Stripped Warped Hyphae', '/items/minecraft:stripped_warped_hyphae.png'),
(293, 'Stripped Warped Stem', '/items/minecraft:stripped_warped_stem.png'),
(294, 'Purple Candle', '/items/minecraft:purple_candle.png'),
(295, 'Smooth Sandstone Stairs', '/items/minecraft:smooth_sandstone_stairs.png'),
(296, 'Dark Oak Wood', '/items/minecraft:dark_oak_wood.png'),
(297, 'Dark Oak Log', '/items/minecraft:dark_oak_log.png'),
(298, 'Brown Glazed Terracotta', '/items/minecraft:brown_glazed_terracotta.png'),
(299, 'Warped Sign', '/items/minecraft:warped_sign.png'),
(300, 'Diamond Chestplate', '/items/minecraft:diamond_chestplate.png'),
(301, 'Fishing Rod', '/items/minecraft:fishing_rod.png'),
(302, 'Waxed Cut Copper Slab', '/items/minecraft:waxed_cut_copper_slab.png'),
(303, 'Dark Oak Hanging Sign', '/items/minecraft:dark_oak_hanging_sign.png'),
(304, 'Mushroom Stew', '/items/minecraft:mushroom_stew.png'),
(305, 'Brown Mushroom', '/items/minecraft:brown_mushroom.png'),
(306, 'Red Mushroom', '/items/minecraft:red_mushroom.png'),
(307, 'Bowl', '/items/minecraft:bowl.png'),
(308, 'Cobblestone Slab', '/items/minecraft:cobblestone_slab.png'),
(309, 'Cookie', '/items/minecraft:cookie.png'),
(310, 'Cocoa Beans', '/items/minecraft:cocoa_beans.png'),
(311, 'Sentry Armor Trim Smithing Template', '/items/minecraft:sentry_armor_trim_smithing_template.png'),
(312, 'Soul Torch', '/items/minecraft:soul_torch.png'),
(313, 'Coal', '/items/minecraft:coal.png'),
(314, 'Charcoal', '/items/minecraft:charcoal.png'),
(315, 'Soul Lantern', '/items/minecraft:soul_lantern.png'),
(316, 'End Stone Bricks', '/items/minecraft:end_stone_bricks.png'),
(317, 'Polished Blackstone Wall', '/items/minecraft:polished_blackstone_wall.png'),
(318, 'Deepslate Copper Ore', '/items/minecraft:deepslate_copper_ore.png'),
(319, 'Polished Diorite Stairs', '/items/minecraft:polished_diorite_stairs.png'),
(320, 'Polished Diorite', '/items/minecraft:polished_diorite.png'),
(321, 'Orange Dye', '/items/minecraft:orange_dye.png'),
(322, 'Torchflower', '/items/minecraft:torchflower.png'),
(323, 'Spruce Fence', '/items/minecraft:spruce_fence.png'),
(324, 'Granite Wall', '/items/minecraft:granite_wall.png'),
(325, 'Granite', '/items/minecraft:granite.png'),
(326, 'Deepslate Brick Slab', '/items/minecraft:deepslate_brick_slab.png'),
(327, 'Bamboo Mosaic', '/items/minecraft:bamboo_mosaic.png'),
(328, 'Bamboo Slab', '/items/minecraft:bamboo_slab.png'),
(329, 'Warped Button', '/items/minecraft:warped_button.png'),
(330, 'Waxed Oxidized Cut Copper Stairs', '/items/minecraft:waxed_oxidized_cut_copper_stairs.png'),
(331, 'Oxidized Cut Copper Stairs', '/items/minecraft:oxidized_cut_copper_stairs.png'),
(332, 'Sugar Cane', '/items/minecraft:sugar_cane.png'),
(333, 'Light Blue Dye', '/items/minecraft:light_blue_dye.png'),
(334, 'Blue Orchid', '/items/minecraft:blue_orchid.png'),
(335, 'Deepslate Tile Slab', '/items/minecraft:deepslate_tile_slab.png'),
(336, 'Deepslate Tiles', '/items/minecraft:deepslate_tiles.png'),
(337, 'Light Gray Glazed Terracotta', '/items/minecraft:light_gray_glazed_terracotta.png'),
(338, 'Light Gray Terracotta', '/items/minecraft:light_gray_terracotta.png'),
(339, 'Shulker Box', '/items/minecraft:shulker_box.png'),
(340, 'Chest', '/items/minecraft:chest.png'),
(341, 'Shulker Shell', '/items/minecraft:shulker_shell.png'),
(342, 'Music Disc 5', '/items/minecraft:music_disc_5.png'),
(343, 'Disc Fragment 5', '/items/minecraft:disc_fragment_5.png'),
(344, 'Melon', '/items/minecraft:melon.png'),
(345, 'Melon Slice', '/items/minecraft:melon_slice.png'),
(346, 'Dark Oak Sign', '/items/minecraft:dark_oak_sign.png'),
(347, 'Polished Blackstone Bricks', '/items/minecraft:polished_blackstone_bricks.png'),
(348, 'Cooked Salmon', '/items/minecraft:cooked_salmon.png'),
(349, 'Salmon', '/items/minecraft:salmon.png'),
(350, 'Sticky Piston', '/items/minecraft:sticky_piston.png'),
(351, 'Piston', '/items/minecraft:piston.png'),
(352, 'Trapped Chest', '/items/minecraft:trapped_chest.png'),
(353, 'Tripwire Hook', '/items/minecraft:tripwire_hook.png'),
(354, 'Dark Oak Fence Gate', '/items/minecraft:dark_oak_fence_gate.png'),
(355, 'Sandstone Slab', '/items/minecraft:sandstone_slab.png'),
(356, 'Chiseled Sandstone', '/items/minecraft:chiseled_sandstone.png'),
(357, 'Ender Chest', '/items/minecraft:ender_chest.png'),
(358, 'Obsidian', '/items/minecraft:obsidian.png'),
(359, 'Orange Stained Glass Pane', '/items/minecraft:orange_stained_glass_pane.png'),
(360, 'Acacia Pressure Plate', '/items/minecraft:acacia_pressure_plate.png'),
(361, 'Brick Slab', '/items/minecraft:brick_slab.png'),
(362, 'Bamboo Mosaic Stairs', '/items/minecraft:bamboo_mosaic_stairs.png'),
(363, 'Emerald', '/items/minecraft:emerald.png'),
(364, 'Emerald Block', '/items/minecraft:emerald_block.png'),
(365, 'Pink Stained Glass', '/items/minecraft:pink_stained_glass.png'),
(366, 'Purpur Slab', '/items/minecraft:purpur_slab.png'),
(367, 'Purpur Pillar', '/items/minecraft:purpur_pillar.png'),
(368, 'Mangrove Button', '/items/minecraft:mangrove_button.png'),
(369, 'Leather Helmet', '/items/minecraft:leather_helmet.png'),
(370, 'Polished Granite Slab', '/items/minecraft:polished_granite_slab.png'),
(371, 'Emerald Ore', '/items/minecraft:emerald_ore.png'),
(372, 'Red Sandstone Stairs', '/items/minecraft:red_sandstone_stairs.png'),
(373, 'Acacia Button', '/items/minecraft:acacia_button.png'),
(374, 'Amethyst Block', '/items/minecraft:amethyst_block.png'),
(375, 'Amethyst Shard', '/items/minecraft:amethyst_shard.png'),
(376, 'Stone Stairs', '/items/minecraft:stone_stairs.png'),
(377, 'Birch Chest Boat', '/items/minecraft:birch_chest_boat.png'),
(378, 'Birch Boat', '/items/minecraft:birch_boat.png'),
(379, 'Prismarine Stairs', '/items/minecraft:prismarine_stairs.png'),
(380, 'Prismarine', '/items/minecraft:prismarine.png'),
(381, 'Orange Candle', '/items/minecraft:orange_candle.png'),
(382, 'Stripped Acacia Wood', '/items/minecraft:stripped_acacia_wood.png'),
(383, 'Stripped Acacia Log', '/items/minecraft:stripped_acacia_log.png'),
(384, 'Dried Kelp Block', '/items/minecraft:dried_kelp_block.png'),
(385, 'Dried Kelp', '/items/minecraft:dried_kelp.png'),
(386, 'Andesite Stairs', '/items/minecraft:andesite_stairs.png'),
(387, 'Beetroot Soup', '/items/minecraft:beetroot_soup.png'),
(388, 'Beetroot', '/items/minecraft:beetroot.png'),
(389, 'Cooked Cod', '/items/minecraft:cooked_cod.png'),
(390, 'Cod', '/items/minecraft:cod.png'),
(391, 'Orange Glazed Terracotta', '/items/minecraft:orange_glazed_terracotta.png'),
(392, 'Orange Terracotta', '/items/minecraft:orange_terracotta.png'),
(393, 'Bone Meal', '/items/minecraft:bone_meal.png'),
(394, 'Bone', '/items/minecraft:bone.png'),
(395, 'Netherite Scrap', '/items/minecraft:netherite_scrap.png'),
(396, 'Ancient Debris', '/items/minecraft:ancient_debris.png'),
(397, 'Jack O Lantern', '/items/minecraft:jack_o_lantern.png'),
(398, 'Carved Pumpkin', '/items/minecraft:carved_pumpkin.png'),
(399, 'End Stone Brick Wall', '/items/minecraft:end_stone_brick_wall.png'),
(400, 'Cooked Mutton', '/items/minecraft:cooked_mutton.png'),
(401, 'Mutton', '/items/minecraft:mutton.png'),
(402, 'Chiseled Quartz Block', '/items/minecraft:chiseled_quartz_block.png'),
(403, 'Quartz Slab', '/items/minecraft:quartz_slab.png'),
(404, 'Polished Blackstone Brick Wall', '/items/minecraft:polished_blackstone_brick_wall.png'),
(405, 'Iron Chestplate', '/items/minecraft:iron_chestplate.png'),
(406, 'Mangrove Boat', '/items/minecraft:mangrove_boat.png'),
(407, 'Iron Pickaxe', '/items/minecraft:iron_pickaxe.png'),
(408, 'Iron Shovel', '/items/minecraft:iron_shovel.png'),
(409, 'Iron Axe', '/items/minecraft:iron_axe.png'),
(410, 'Iron Hoe', '/items/minecraft:iron_hoe.png'),
(411, 'Iron Sword', '/items/minecraft:iron_sword.png'),
(412, 'Iron Helmet', '/items/minecraft:iron_helmet.png'),
(413, 'Iron Leggings', '/items/minecraft:iron_leggings.png'),
(414, 'Iron Boots', '/items/minecraft:iron_boots.png'),
(415, 'Iron Horse Armor', '/items/minecraft:iron_horse_armor.png'),
(416, 'Chainmail Helmet', '/items/minecraft:chainmail_helmet.png'),
(417, 'Chainmail Chestplate', '/items/minecraft:chainmail_chestplate.png'),
(418, 'Chainmail Leggings', '/items/minecraft:chainmail_leggings.png'),
(419, 'Chainmail Boots', '/items/minecraft:chainmail_boots.png'),
(420, 'Cooked Beef', '/items/minecraft:cooked_beef.png'),
(421, 'Beef', '/items/minecraft:beef.png'),
(422, 'Vine', '/items/minecraft:vine.png'),
(423, 'Writable Book', '/items/minecraft:writable_book.png'),
(424, 'Book', '/items/minecraft:book.png'),
(425, 'Ink Sac', '/items/minecraft:ink_sac.png'),
(426, 'Dispenser', '/items/minecraft:dispenser.png'),
(427, 'Bow', '/items/minecraft:bow.png'),
(428, 'Green Stained Glass Pane', '/items/minecraft:green_stained_glass_pane.png'),
(429, 'Deepslate Diamond Ore', '/items/minecraft:deepslate_diamond_ore.png'),
(430, 'Lily Of The Valley', '/items/minecraft:lily_of_the_valley.png'),
(431, 'Bamboo Sign', '/items/minecraft:bamboo_sign.png'),
(432, 'Chiseled Polished Blackstone', '/items/minecraft:chiseled_polished_blackstone.png'),
(433, 'Raw Gold', '/items/minecraft:raw_gold.png'),
(434, 'Chorus Fruit', '/items/minecraft:chorus_fruit.png'),
(435, 'Brick', '/items/minecraft:brick.png'),
(436, 'Clay Ball', '/items/minecraft:clay_ball.png'),
(437, 'Nether Brick', '/items/minecraft:nether_brick.png'),
(438, 'Stone Slab', '/items/minecraft:stone_slab.png'),
(439, 'Magenta Dye', '/items/minecraft:magenta_dye.png'),
(440, 'Allium', '/items/minecraft:allium.png'),
(441, 'Golden Pickaxe', '/items/minecraft:golden_pickaxe.png'),
(442, 'Golden Shovel', '/items/minecraft:golden_shovel.png'),
(443, 'Golden Axe', '/items/minecraft:golden_axe.png'),
(444, 'Golden Hoe', '/items/minecraft:golden_hoe.png'),
(445, 'Golden Sword', '/items/minecraft:golden_sword.png'),
(446, 'Golden Helmet', '/items/minecraft:golden_helmet.png'),
(447, 'Golden Chestplate', '/items/minecraft:golden_chestplate.png'),
(448, 'Golden Leggings', '/items/minecraft:golden_leggings.png'),
(449, 'Golden Boots', '/items/minecraft:golden_boots.png'),
(450, 'Golden Horse Armor', '/items/minecraft:golden_horse_armor.png'),
(451, 'Quartz Stairs', '/items/minecraft:quartz_stairs.png'),
(452, 'Quartz Block', '/items/minecraft:quartz_block.png'),
(453, 'Quartz Pillar', '/items/minecraft:quartz_pillar.png'),
(454, 'Nether Brick Wall', '/items/minecraft:nether_brick_wall.png'),
(455, 'Oak Boat', '/items/minecraft:oak_boat.png'),
(456, 'Acacia Sign', '/items/minecraft:acacia_sign.png'),
(457, 'Warped Pressure Plate', '/items/minecraft:warped_pressure_plate.png'),
(458, 'Pumpkin Seeds', '/items/minecraft:pumpkin_seeds.png'),
(459, 'Pumpkin', '/items/minecraft:pumpkin.png'),
(460, 'Sandstone Stairs', '/items/minecraft:sandstone_stairs.png'),
(461, 'Cut Sandstone', '/items/minecraft:cut_sandstone.png'),
(462, 'Magenta Stained Glass Pane', '/items/minecraft:magenta_stained_glass_pane.png'),
(463, 'Clay', '/items/minecraft:clay.png'),
(464, 'Ender Pearl', '/items/minecraft:ender_pearl.png'),
(465, 'Blaze Powder', '/items/minecraft:blaze_powder.png'),
(466, 'Crimson Button', '/items/minecraft:crimson_button.png'),
(467, 'Deepslate Tile Wall', '/items/minecraft:deepslate_tile_wall.png'),
(468, 'Calibrated Sculk Sensor', '/items/minecraft:calibrated_sculk_sensor.png'),
(469, 'Sculk Sensor', '/items/minecraft:sculk_sensor.png'),
(470, 'Purple Glazed Terracotta', '/items/minecraft:purple_glazed_terracotta.png'),
(471, 'Purple Terracotta', '/items/minecraft:purple_terracotta.png'),
(472, 'Stripped Mangrove Wood', '/items/minecraft:stripped_mangrove_wood.png'),
(473, 'Purple Concrete Powder', '/items/minecraft:purple_concrete_powder.png'),
(474, 'White Tulip', '/items/minecraft:white_tulip.png'),
(475, 'Netherite Shovel', '/items/minecraft:netherite_shovel.png'),
(476, 'Cyan Stained Glass', '/items/minecraft:cyan_stained_glass.png'),
(477, 'Yellow Terracotta', '/items/minecraft:yellow_terracotta.png'),
(478, 'Andesite Slab', '/items/minecraft:andesite_slab.png'),
(479, 'Blackstone Wall', '/items/minecraft:blackstone_wall.png'),
(480, 'Deepslate Iron Ore', '/items/minecraft:deepslate_iron_ore.png'),
(481, 'Shears', '/items/minecraft:shears.png'),
(482, 'Deepslate Redstone Ore', '/items/minecraft:deepslate_redstone_ore.png'),
(483, 'Rabbit Stew', '/items/minecraft:rabbit_stew.png'),
(484, 'Cooked Rabbit', '/items/minecraft:cooked_rabbit.png'),
(485, 'Honeycomb Block', '/items/minecraft:honeycomb_block.png'),
(486, 'Black Dye', '/items/minecraft:black_dye.png'),
(487, 'Wither Rose', '/items/minecraft:wither_rose.png'),
(488, 'Eye Armor Trim Smithing Template', '/items/minecraft:eye_armor_trim_smithing_template.png'),
(489, 'Crimson Fence', '/items/minecraft:crimson_fence.png'),
(490, 'Stone Brick Wall', '/items/minecraft:stone_brick_wall.png'),
(491, 'Yellow Glazed Terracotta', '/items/minecraft:yellow_glazed_terracotta.png'),
(492, 'Smoker', '/items/minecraft:smoker.png'),
(493, 'Bamboo Trapdoor', '/items/minecraft:bamboo_trapdoor.png'),
(494, 'Tnt Minecart', '/items/minecraft:tnt_minecart.png'),
(495, 'Tnt', '/items/minecraft:tnt.png'),
(496, 'Exposed Cut Copper Stairs', '/items/minecraft:exposed_cut_copper_stairs.png'),
(497, 'Exposed Cut Copper', '/items/minecraft:exposed_cut_copper.png'),
(498, 'Cherry Fence Gate', '/items/minecraft:cherry_fence_gate.png'),
(499, 'Chiseled Nether Bricks', '/items/minecraft:chiseled_nether_bricks.png'),
(500, 'Dandelion', '/items/minecraft:dandelion.png'),
(501, 'Heavy Weighted Pressure Plate', '/items/minecraft:heavy_weighted_pressure_plate.png'),
(502, 'Netherite Ingot', '/items/minecraft:netherite_ingot.png'),
(503, 'White Candle', '/items/minecraft:white_candle.png'),
(504, 'Dark Oak Stairs', '/items/minecraft:dark_oak_stairs.png'),
(505, 'Cherry Button', '/items/minecraft:cherry_button.png'),
(506, 'Netherite Sword', '/items/minecraft:netherite_sword.png'),
(507, 'Dark Prismarine Slab', '/items/minecraft:dark_prismarine_slab.png'),
(508, 'Dark Prismarine', '/items/minecraft:dark_prismarine.png'),
(509, 'Spruce Trapdoor', '/items/minecraft:spruce_trapdoor.png'),
(510, 'Fire Charge', '/items/minecraft:fire_charge.png'),
(511, 'Gunpowder', '/items/minecraft:gunpowder.png'),
(512, 'Weathered Cut Copper Slab', '/items/minecraft:weathered_cut_copper_slab.png'),
(513, 'Quartz Bricks', '/items/minecraft:quartz_bricks.png'),
(514, 'Coast Armor Trim Smithing Template', '/items/minecraft:coast_armor_trim_smithing_template.png'),
(515, 'Oak Trapdoor', '/items/minecraft:oak_trapdoor.png'),
(516, 'Purple Stained Glass Pane', '/items/minecraft:purple_stained_glass_pane.png'),
(517, 'Purple Stained Glass', '/items/minecraft:purple_stained_glass.png'),
(518, 'Blaze Rod', '/items/minecraft:blaze_rod.png'),
(519, 'Crimson Sign', '/items/minecraft:crimson_sign.png'),
(520, 'Barrel', '/items/minecraft:barrel.png'),
(521, 'Red Stained Glass', '/items/minecraft:red_stained_glass.png'),
(522, 'Polished Blackstone Brick Stairs', '/items/minecraft:polished_blackstone_brick_stairs.png'),
(523, 'Mossy Stone Brick Stairs', '/items/minecraft:mossy_stone_brick_stairs.png'),
(524, 'Oak Pressure Plate', '/items/minecraft:oak_pressure_plate.png'),
(525, 'Gray Stained Glass', '/items/minecraft:gray_stained_glass.png'),
(526, 'Polished Deepslate Wall', '/items/minecraft:polished_deepslate_wall.png'),
(527, 'Smooth Stone Slab', '/items/minecraft:smooth_stone_slab.png'),
(528, 'Smooth Stone', '/items/minecraft:smooth_stone.png'),
(529, 'Warped Trapdoor', '/items/minecraft:warped_trapdoor.png'),
(530, 'Sunflower', '/items/minecraft:sunflower.png'),
(531, 'Gray Glazed Terracotta', '/items/minecraft:gray_glazed_terracotta.png'),
(532, 'Granite Slab', '/items/minecraft:granite_slab.png'),
(533, 'Black Glazed Terracotta', '/items/minecraft:black_glazed_terracotta.png'),
(534, 'Black Terracotta', '/items/minecraft:black_terracotta.png'),
(535, 'Deepslate Emerald Ore', '/items/minecraft:deepslate_emerald_ore.png'),
(536, 'Warped Fungus On A Stick', '/items/minecraft:warped_fungus_on_a_stick.png'),
(537, 'Warped Fungus', '/items/minecraft:warped_fungus.png'),
(538, 'Polished Deepslate Slab', '/items/minecraft:polished_deepslate_slab.png'),
(539, 'Blue Ice', '/items/minecraft:blue_ice.png'),
(540, 'Packed Ice', '/items/minecraft:packed_ice.png'),
(541, 'Acacia Wood', '/items/minecraft:acacia_wood.png'),
(542, 'Acacia Log', '/items/minecraft:acacia_log.png'),
(543, 'Red Sand', '/items/minecraft:red_sand.png'),
(544, 'Cut Sandstone Slab', '/items/minecraft:cut_sandstone_slab.png'),
(545, 'Spyglass', '/items/minecraft:spyglass.png'),
(546, 'Diamond Block', '/items/minecraft:diamond_block.png'),
(547, 'Stripped Oak Wood', '/items/minecraft:stripped_oak_wood.png'),
(548, 'Stripped Oak Log', '/items/minecraft:stripped_oak_log.png'),
(549, 'End Rod', '/items/minecraft:end_rod.png'),
(550, 'Red Nether Brick Slab', '/items/minecraft:red_nether_brick_slab.png'),
(551, 'Red Nether Bricks', '/items/minecraft:red_nether_bricks.png'),
(552, 'Light Blue Candle', '/items/minecraft:light_blue_candle.png'),
(553, 'Blue Candle', '/items/minecraft:blue_candle.png'),
(554, 'Crimson Hanging Sign', '/items/minecraft:crimson_hanging_sign.png'),
(555, 'Stripped Crimson Stem', '/items/minecraft:stripped_crimson_stem.png'),
(556, 'Snout Armor Trim Smithing Template', '/items/minecraft:snout_armor_trim_smithing_template.png'),
(557, 'Compass', '/items/minecraft:compass.png'),
(558, 'Bamboo Button', '/items/minecraft:bamboo_button.png'),
(559, 'Brown Candle', '/items/minecraft:brown_candle.png'),
(560, 'Red Nether Brick Wall', '/items/minecraft:red_nether_brick_wall.png'),
(561, 'Pink Candle', '/items/minecraft:pink_candle.png'),
(562, 'Bamboo Hanging Sign', '/items/minecraft:bamboo_hanging_sign.png'),
(563, 'Stripped Bamboo Block', '/items/minecraft:stripped_bamboo_block.png'),
(564, 'Cherry Hanging Sign', '/items/minecraft:cherry_hanging_sign.png'),
(565, 'Stripped Cherry Log', '/items/minecraft:stripped_cherry_log.png'),
(566, 'Red Nether Brick Stairs', '/items/minecraft:red_nether_brick_stairs.png'),
(567, 'Moss Carpet', '/items/minecraft:moss_carpet.png'),
(568, 'Oak Door', '/items/minecraft:oak_door.png'),
(569, 'Wooden Sword', '/items/minecraft:wooden_sword.png'),
(570, 'Nether Wart Block', '/items/minecraft:nether_wart_block.png'),
(571, 'Nether Wart', '/items/minecraft:nether_wart.png'),
(572, 'Paper', '/items/minecraft:paper.png'),
(573, 'Respawn Anchor', '/items/minecraft:respawn_anchor.png'),
(574, 'Crying Obsidian', '/items/minecraft:crying_obsidian.png'),
(575, 'Sea Lantern', '/items/minecraft:sea_lantern.png'),
(576, 'Prismarine Crystals', '/items/minecraft:prismarine_crystals.png'),
(577, 'Prismarine Shard', '/items/minecraft:prismarine_shard.png'),
(578, 'Polished Andesite Slab', '/items/minecraft:polished_andesite_slab.png'),
(579, 'Polished Andesite', '/items/minecraft:polished_andesite.png'),
(580, 'Pink Petals', '/items/minecraft:pink_petals.png'),
(581, 'End Stone Brick Stairs', '/items/minecraft:end_stone_brick_stairs.png'),
(582, 'Stripped Birch Wood', '/items/minecraft:stripped_birch_wood.png'),
(583, 'Stripped Birch Log', '/items/minecraft:stripped_birch_log.png'),
(584, 'Blackstone Slab', '/items/minecraft:blackstone_slab.png'),
(585, 'Granite Stairs', '/items/minecraft:granite_stairs.png'),
(586, 'Bookshelf', '/items/minecraft:bookshelf.png'),
(587, 'Mangrove Chest Boat', '/items/minecraft:mangrove_chest_boat.png'),
(588, 'Birch Sign', '/items/minecraft:birch_sign.png'),
(589, 'Diamond Axe', '/items/minecraft:diamond_axe.png'),
(590, 'Lodestone', '/items/minecraft:lodestone.png'),
(591, 'Cherry Slab', '/items/minecraft:cherry_slab.png'),
(592, 'Oak Button', '/items/minecraft:oak_button.png'),
(593, 'Mangrove Sign', '/items/minecraft:mangrove_sign.png'),
(594, 'Orange Stained Glass', '/items/minecraft:orange_stained_glass.png'),
(595, 'Gray Stained Glass Pane', '/items/minecraft:gray_stained_glass_pane.png'),
(596, 'Spruce Pressure Plate', '/items/minecraft:spruce_pressure_plate.png'),
(597, 'Warped Door', '/items/minecraft:warped_door.png'),
(598, 'Cactus', '/items/minecraft:cactus.png'),
(599, 'Cobblestone Stairs', '/items/minecraft:cobblestone_stairs.png'),
(600, 'Rose Bush', '/items/minecraft:rose_bush.png'),
(601, 'Red Stained Glass Pane', '/items/minecraft:red_stained_glass_pane.png'),
(602, 'Note Block', '/items/minecraft:note_block.png'),
(603, 'Iron Bars', '/items/minecraft:iron_bars.png'),
(604, 'Turtle Helmet', '/items/minecraft:turtle_helmet.png'),
(605, 'Scute', '/items/minecraft:scute.png'),
(606, 'Netherite Hoe', '/items/minecraft:netherite_hoe.png'),
(607, 'Shield', '/items/minecraft:shield.png'),
(608, 'Yellow Stained Glass Pane', '/items/minecraft:yellow_stained_glass_pane.png'),
(609, 'Yellow Stained Glass', '/items/minecraft:yellow_stained_glass.png'),
(610, 'Diamond Hoe', '/items/minecraft:diamond_hoe.png'),
(611, 'Brown Stained Glass Pane', '/items/minecraft:brown_stained_glass_pane.png'),
(612, 'Scaffolding', '/items/minecraft:scaffolding.png'),
(613, 'Jungle Slab', '/items/minecraft:jungle_slab.png'),
(614, 'Lever', '/items/minecraft:lever.png'),
(615, 'Smooth Sandstone Slab', '/items/minecraft:smooth_sandstone_slab.png'),
(616, 'Purple Banner', '/items/minecraft:purple_banner.png'),
(617, 'Acacia Fence', '/items/minecraft:acacia_fence.png'),
(618, 'Dark Oak Boat', '/items/minecraft:dark_oak_boat.png'),
(619, 'Bone Block', '/items/minecraft:bone_block.png'),
(620, 'Weathered Cut Copper Stairs', '/items/minecraft:weathered_cut_copper_stairs.png'),
(621, 'Arrow', '/items/minecraft:arrow.png'),
(622, 'Wooden Hoe', '/items/minecraft:wooden_hoe.png'),
(623, 'Magenta Stained Glass', '/items/minecraft:magenta_stained_glass.png'),
(624, 'Dark Oak Door', '/items/minecraft:dark_oak_door.png'),
(625, 'Light Blue Terracotta', '/items/minecraft:light_blue_terracotta.png'),
(626, 'Coal Ore', '/items/minecraft:coal_ore.png'),
(627, 'Poppy', '/items/minecraft:poppy.png'),
(628, 'Prismarine Brick Stairs', '/items/minecraft:prismarine_brick_stairs.png'),
(629, 'Prismarine Bricks', '/items/minecraft:prismarine_bricks.png'),
(630, 'Waxed Weathered Cut Copper Slab', '/items/minecraft:waxed_weathered_cut_copper_slab.png'),
(631, 'Mangrove Wood', '/items/minecraft:mangrove_wood.png'),
(632, 'Mangrove Log', '/items/minecraft:mangrove_log.png'),
(633, 'Birch Stairs', '/items/minecraft:birch_stairs.png'),
(634, 'Rabbit', '/items/minecraft:rabbit.png'),
(635, 'Birch Wood', '/items/minecraft:birch_wood.png'),
(636, 'Birch Log', '/items/minecraft:birch_log.png'),
(637, 'Exposed Cut Copper Slab', '/items/minecraft:exposed_cut_copper_slab.png'),
(638, 'Nether Gold Ore', '/items/minecraft:nether_gold_ore.png'),
(639, 'Acacia Fence Gate', '/items/minecraft:acacia_fence_gate.png'),
(640, 'Shaper Armor Trim Smithing Template', '/items/minecraft:shaper_armor_trim_smithing_template.png'),
(641, 'Black Stained Glass Pane', '/items/minecraft:black_stained_glass_pane.png'),
(642, 'Dark Prismarine Stairs', '/items/minecraft:dark_prismarine_stairs.png'),
(643, 'Raw Iron Block', '/items/minecraft:raw_iron_block.png'),
(644, 'Waxed Exposed Cut Copper Stairs', '/items/minecraft:waxed_exposed_cut_copper_stairs.png'),
(645, 'Polished Andesite Stairs', '/items/minecraft:polished_andesite_stairs.png'),
(646, 'Stone Brick Stairs', '/items/minecraft:stone_brick_stairs.png'),
(647, 'Smooth Quartz Stairs', '/items/minecraft:smooth_quartz_stairs.png'),
(648, 'Green Stained Glass', '/items/minecraft:green_stained_glass.png'),
(649, 'Crimson Hyphae', '/items/minecraft:crimson_hyphae.png'),
(650, 'Crimson Stem', '/items/minecraft:crimson_stem.png'),
(651, 'Bamboo Door', '/items/minecraft:bamboo_door.png'),
(652, 'Chiseled Deepslate', '/items/minecraft:chiseled_deepslate.png'),
(653, 'Gold Block', '/items/minecraft:gold_block.png'),
(654, 'Cut Copper Slab', '/items/minecraft:cut_copper_slab.png'),
(655, 'Polished Diorite Slab', '/items/minecraft:polished_diorite_slab.png'),
(656, 'Orange Banner', '/items/minecraft:orange_banner.png'),
(657, 'Acacia Hanging Sign', '/items/minecraft:acacia_hanging_sign.png'),
(658, 'Netherite Upgrade Smithing Template', '/items/minecraft:netherite_upgrade_smithing_template.png'),
(659, 'Netherrack', '/items/minecraft:netherrack.png'),
(660, 'Wooden Axe', '/items/minecraft:wooden_axe.png'),
(661, 'Green Glazed Terracotta', '/items/minecraft:green_glazed_terracotta.png'),
(662, 'Gray Candle', '/items/minecraft:gray_candle.png'),
(663, 'Spruce Door', '/items/minecraft:spruce_door.png'),
(664, 'Red Banner', '/items/minecraft:red_banner.png'),
(665, 'Smithing Table', '/items/minecraft:smithing_table.png'),
(666, 'Wooden Shovel', '/items/minecraft:wooden_shovel.png'),
(667, 'Acacia Slab', '/items/minecraft:acacia_slab.png'),
(668, 'Blast Furnace', '/items/minecraft:blast_furnace.png'),
(669, 'Stone Hoe', '/items/minecraft:stone_hoe.png'),
(670, 'Bamboo Fence', '/items/minecraft:bamboo_fence.png'),
(671, 'Wooden Pickaxe', '/items/minecraft:wooden_pickaxe.png'),
(672, 'Stone Button', '/items/minecraft:stone_button.png'),
(673, 'Light Gray Candle', '/items/minecraft:light_gray_candle.png'),
(674, 'Birch Button', '/items/minecraft:birch_button.png'),
(675, 'Kelp', '/items/minecraft:kelp.png'),
(676, 'Diamond Shovel', '/items/minecraft:diamond_shovel.png'),
(677, 'Stone Pickaxe', '/items/minecraft:stone_pickaxe.png'),
(678, 'Lime Stained Glass Pane', '/items/minecraft:lime_stained_glass_pane.png'),
(679, 'Lime Stained Glass', '/items/minecraft:lime_stained_glass.png'),
(680, 'Mangrove Fence', '/items/minecraft:mangrove_fence.png'),
(681, 'Decorated Pot', '/items/minecraft:decorated_pot.png'),
(682, 'Bamboo Fence Gate', '/items/minecraft:bamboo_fence_gate.png'),
(683, 'Bamboo Mosaic Slab', '/items/minecraft:bamboo_mosaic_slab.png'),
(684, 'Cherry Trapdoor', '/items/minecraft:cherry_trapdoor.png'),
(685, 'Lightning Rod', '/items/minecraft:lightning_rod.png'),
(686, 'Netherite Chestplate', '/items/minecraft:netherite_chestplate.png'),
(687, 'Creeper Banner Pattern', '/items/minecraft:creeper_banner_pattern.png'),
(688, 'Creeper Head', '/items/minecraft:creeper_head.png'),
(689, 'Deepslate', '/items/minecraft:deepslate.png'),
(690, 'Loom', '/items/minecraft:loom.png'),
(691, 'Deepslate Lapis Ore', '/items/minecraft:deepslate_lapis_ore.png'),
(692, 'Cherry Pressure Plate', '/items/minecraft:cherry_pressure_plate.png'),
(693, 'Copper Ore', '/items/minecraft:copper_ore.png'),
(694, 'Jukebox', '/items/minecraft:jukebox.png'),
(695, 'Lead', '/items/minecraft:lead.png'),
(696, 'Brick Stairs', '/items/minecraft:brick_stairs.png'),
(697, 'Magenta Banner', '/items/minecraft:magenta_banner.png'),
(698, 'Magma Block', '/items/minecraft:magma_block.png'),
(699, 'Magma Cream', '/items/minecraft:magma_cream.png'),
(700, 'Diamond Ore', '/items/minecraft:diamond_ore.png'),
(701, 'Oak Fence', '/items/minecraft:oak_fence.png'),
(702, 'Jungle Trapdoor', '/items/minecraft:jungle_trapdoor.png'),
(703, 'Composter', '/items/minecraft:composter.png'),
(704, 'Lime Candle', '/items/minecraft:lime_candle.png'),
(705, 'Stone Axe', '/items/minecraft:stone_axe.png'),
(706, 'Dark Oak Fence', '/items/minecraft:dark_oak_fence.png'),
(707, 'Warped Fence Gate', '/items/minecraft:warped_fence_gate.png'),
(708, 'Cartography Table', '/items/minecraft:cartography_table.png'),
(709, 'Raw Copper', '/items/minecraft:raw_copper.png'),
(710, 'Grindstone', '/items/minecraft:grindstone.png'),
(711, 'Peony', '/items/minecraft:peony.png'),
(712, 'Flint And Steel', '/items/minecraft:flint_and_steel.png'),
(713, 'Mud Brick Stairs', '/items/minecraft:mud_brick_stairs.png'),
(714, 'Mud Bricks', '/items/minecraft:mud_bricks.png'),
(715, 'Ladder', '/items/minecraft:ladder.png'),
(716, 'Crimson Slab', '/items/minecraft:crimson_slab.png'),
(717, 'Cyan Stained Glass Pane', '/items/minecraft:cyan_stained_glass_pane.png'),
(718, 'Crimson Trapdoor', '/items/minecraft:crimson_trapdoor.png'),
(719, 'Light Blue Concrete Powder', '/items/minecraft:light_blue_concrete_powder.png'),
(720, 'Painting', '/items/minecraft:painting.png'),
(721, 'Oak Stairs', '/items/minecraft:oak_stairs.png'),
(722, 'Pink Glazed Terracotta', '/items/minecraft:pink_glazed_terracotta.png'),
(723, 'Pumpkin Pie', '/items/minecraft:pumpkin_pie.png'),
(724, 'Egg', '/items/minecraft:egg.png'),
(725, 'Netherite Block', '/items/minecraft:netherite_block.png'),
(726, 'Netherite Helmet', '/items/minecraft:netherite_helmet.png'),
(727, 'Dripstone Block', '/items/minecraft:dripstone_block.png'),
(728, 'Pointed Dripstone', '/items/minecraft:pointed_dripstone.png'),
(729, 'Chest Minecart', '/items/minecraft:chest_minecart.png'),
(730, 'Pink Concrete Powder', '/items/minecraft:pink_concrete_powder.png'),
(731, 'Polished Basalt', '/items/minecraft:polished_basalt.png'),
(732, 'Crafting Table', '/items/minecraft:crafting_table.png'),
(733, 'Bamboo Chest Raft', '/items/minecraft:bamboo_chest_raft.png'),
(734, 'Bamboo Raft', '/items/minecraft:bamboo_raft.png'),
(735, 'Netherite Axe', '/items/minecraft:netherite_axe.png'),
(736, 'Jungle Fence', '/items/minecraft:jungle_fence.png'),
(737, 'Prismarine Slab', '/items/minecraft:prismarine_slab.png'),
(738, 'Spruce Hanging Sign', '/items/minecraft:spruce_hanging_sign.png'),
(739, 'Stripped Spruce Log', '/items/minecraft:stripped_spruce_log.png'),
(740, 'Black Banner', '/items/minecraft:black_banner.png'),
(741, 'Chiseled Bookshelf', '/items/minecraft:chiseled_bookshelf.png'),
(742, 'Mud Brick Slab', '/items/minecraft:mud_brick_slab.png'),
(743, 'Dark Oak Pressure Plate', '/items/minecraft:dark_oak_pressure_plate.png'),
(744, 'Birch Fence Gate', '/items/minecraft:birch_fence_gate.png'),
(745, 'Spire Armor Trim Smithing Template', '/items/minecraft:spire_armor_trim_smithing_template.png'),
(746, 'Raw Copper Block', '/items/minecraft:raw_copper_block.png'),
(747, 'Nether Brick Stairs', '/items/minecraft:nether_brick_stairs.png'),
(748, 'Yellow Banner', '/items/minecraft:yellow_banner.png'),
(749, 'Diorite Wall', '/items/minecraft:diorite_wall.png'),
(750, 'Enchanting Table', '/items/minecraft:enchanting_table.png'),
(751, 'Spruce Boat', '/items/minecraft:spruce_boat.png'),
(752, 'Dark Oak Chest Boat', '/items/minecraft:dark_oak_chest_boat.png'),
(753, 'Orange Concrete Powder', '/items/minecraft:orange_concrete_powder.png'),
(754, 'Spruce Chest Boat', '/items/minecraft:spruce_chest_boat.png'),
(755, 'Cyan Banner', '/items/minecraft:cyan_banner.png'),
(756, 'Raiser Armor Trim Smithing Template', '/items/minecraft:raiser_armor_trim_smithing_template.png'),
(757, 'Pink Stained Glass Pane', '/items/minecraft:pink_stained_glass_pane.png'),
(758, 'Crossbow', '/items/minecraft:crossbow.png'),
(759, 'Flower Pot', '/items/minecraft:flower_pot.png'),
(760, 'Birch Slab', '/items/minecraft:birch_slab.png'),
(761, 'Rabbit Hide', '/items/minecraft:rabbit_hide.png'),
(762, 'Cracked Polished Blackstone Bricks', '/items/minecraft:cracked_polished_blackstone_bricks.png'),
(763, 'Gray Concrete Powder', '/items/minecraft:gray_concrete_powder.png'),
(764, 'Activator Rail', '/items/minecraft:activator_rail.png'),
(765, 'Rib Armor Trim Smithing Template', '/items/minecraft:rib_armor_trim_smithing_template.png'),
(766, 'Mangrove Slab', '/items/minecraft:mangrove_slab.png'),
(767, 'Cherry Sign', '/items/minecraft:cherry_sign.png'),
(768, 'Cracked Deepslate Tiles', '/items/minecraft:cracked_deepslate_tiles.png'),
(769, 'Oak Chest Boat', '/items/minecraft:oak_chest_boat.png'),
(770, 'Crimson Fence Gate', '/items/minecraft:crimson_fence_gate.png'),
(771, 'Ward Armor Trim Smithing Template', '/items/minecraft:ward_armor_trim_smithing_template.png'),
(772, 'Firework Rocket', '/items/minecraft:firework_rocket.png'),
(773, 'Soul Campfire', '/items/minecraft:soul_campfire.png'),
(774, 'Diamond Pickaxe', '/items/minecraft:diamond_pickaxe.png'),
(775, 'Netherite Pickaxe', '/items/minecraft:netherite_pickaxe.png'),
(776, 'Cut Red Sandstone Slab', '/items/minecraft:cut_red_sandstone_slab.png'),
(777, 'Bamboo Stairs', '/items/minecraft:bamboo_stairs.png'),
(778, 'Jungle Hanging Sign', '/items/minecraft:jungle_hanging_sign.png'),
(779, 'Stripped Jungle Log', '/items/minecraft:stripped_jungle_log.png'),
(780, 'Prismarine Brick Slab', '/items/minecraft:prismarine_brick_slab.png'),
(781, 'Jungle Sign', '/items/minecraft:jungle_sign.png'),
(782, 'Jungle Chest Boat', '/items/minecraft:jungle_chest_boat.png'),
(783, 'Jungle Boat', '/items/minecraft:jungle_boat.png'),
(784, 'Melon Seeds', '/items/minecraft:melon_seeds.png'),
(785, 'Glistering Melon Slice', '/items/minecraft:glistering_melon_slice.png'),
(786, 'Vex Armor Trim Smithing Template', '/items/minecraft:vex_armor_trim_smithing_template.png'),
(787, 'Crimson Stairs', '/items/minecraft:crimson_stairs.png'),
(788, 'Lime Concrete Powder', '/items/minecraft:lime_concrete_powder.png'),
(789, 'Cherry Wood', '/items/minecraft:cherry_wood.png'),
(790, 'Cherry Log', '/items/minecraft:cherry_log.png'),
(791, 'Pink Tulip', '/items/minecraft:pink_tulip.png'),
(792, 'Light Blue Stained Glass', '/items/minecraft:light_blue_stained_glass.png'),
(793, 'White Stained Glass Pane', '/items/minecraft:white_stained_glass_pane.png'),
(794, 'Prismarine Wall', '/items/minecraft:prismarine_wall.png'),
(795, 'Stripped Spruce Wood', '/items/minecraft:stripped_spruce_wood.png'),
(796, 'Snow', '/items/minecraft:snow.png'),
(797, 'Snow Block', '/items/minecraft:snow_block.png'),
(798, 'Cake', '/items/minecraft:cake.png'),
(799, 'Milk Bucket', '/items/minecraft:milk_bucket.png'),
(800, 'Green Candle', '/items/minecraft:green_candle.png'),
(801, 'Mangrove Pressure Plate', '/items/minecraft:mangrove_pressure_plate.png'),
(802, 'Birch Fence', '/items/minecraft:birch_fence.png'),
(803, 'Red Concrete Powder', '/items/minecraft:red_concrete_powder.png'),
(804, 'Fermented Spider Eye', '/items/minecraft:fermented_spider_eye.png'),
(805, 'Spider Eye', '/items/minecraft:spider_eye.png'),
(806, 'Jungle Wood', '/items/minecraft:jungle_wood.png'),
(807, 'Jungle Log', '/items/minecraft:jungle_log.png'),
(808, 'Blue Glazed Terracotta', '/items/minecraft:blue_glazed_terracotta.png'),
(809, 'Dark Oak Button', '/items/minecraft:dark_oak_button.png'),
(810, 'Smooth Red Sandstone Stairs', '/items/minecraft:smooth_red_sandstone_stairs.png'),
(811, 'Mud Brick Wall', '/items/minecraft:mud_brick_wall.png'),
(812, 'Cherry Stairs', '/items/minecraft:cherry_stairs.png'),
(813, 'Wild Armor Trim Smithing Template', '/items/minecraft:wild_armor_trim_smithing_template.png'),
(814, 'Leather Leggings', '/items/minecraft:leather_leggings.png'),
(815, 'Lilac', '/items/minecraft:lilac.png'),
(816, 'Spruce Sign', '/items/minecraft:spruce_sign.png'),
(817, 'Beacon', '/items/minecraft:beacon.png'),
(818, 'Nether Star', '/items/minecraft:nether_star.png'),
(819, 'Brewing Stand', '/items/minecraft:brewing_stand.png'),
(820, 'Magenta Candle', '/items/minecraft:magenta_candle.png'),
(821, 'Lapis Ore', '/items/minecraft:lapis_ore.png'),
(822, 'Mangrove Stairs', '/items/minecraft:mangrove_stairs.png'),
(823, 'Mossy Stone Brick Slab', '/items/minecraft:mossy_stone_brick_slab.png'),
(824, 'Acacia Stairs', '/items/minecraft:acacia_stairs.png'),
(825, 'Bread', '/items/minecraft:bread.png'),
(826, 'White Glazed Terracotta', '/items/minecraft:white_glazed_terracotta.png'),
(827, 'Snowball', '/items/minecraft:snowball.png'),
(828, 'Pitcher Plant', '/items/minecraft:pitcher_plant.png'),
(829, 'Light Blue Glazed Terracotta', '/items/minecraft:light_blue_glazed_terracotta.png'),
(830, 'Mossy Stone Brick Wall', '/items/minecraft:mossy_stone_brick_wall.png'),
(831, 'Lime Banner', '/items/minecraft:lime_banner.png'),
(832, 'Raw Gold Block', '/items/minecraft:raw_gold_block.png'),
(833, 'Light Gray Banner', '/items/minecraft:light_gray_banner.png'),
(834, 'Netherite Leggings', '/items/minecraft:netherite_leggings.png'),
(835, 'Warped Hanging Sign', '/items/minecraft:warped_hanging_sign.png'),
(836, 'Purpur Stairs', '/items/minecraft:purpur_stairs.png'),
(837, 'Coal Block', '/items/minecraft:coal_block.png'),
(838, 'Red Candle', '/items/minecraft:red_candle.png'),
(839, 'Gray Banner', '/items/minecraft:gray_banner.png'),
(840, 'Lectern', '/items/minecraft:lectern.png'),
(841, 'Deepslate Coal Ore', '/items/minecraft:deepslate_coal_ore.png'),
(842, 'Cornflower', '/items/minecraft:cornflower.png'),
(843, 'Mangrove Fence Gate', '/items/minecraft:mangrove_fence_gate.png'),
(844, 'Light Blue Stained Glass Pane', '/items/minecraft:light_blue_stained_glass_pane.png'),
(845, 'Carrot On A Stick', '/items/minecraft:carrot_on_a_stick.png'),
(846, 'Blue Concrete Powder', '/items/minecraft:blue_concrete_powder.png'),
(847, 'Skull Banner Pattern', '/items/minecraft:skull_banner_pattern.png'),
(848, 'Wither Skeleton Skull', '/items/minecraft:wither_skeleton_skull.png'),
(849, 'Mojang Banner Pattern', '/items/minecraft:mojang_banner_pattern.png'),
(850, 'Enchanted Golden Apple', '/items/minecraft:enchanted_golden_apple.png'),
(851, 'Tinted Glass', '/items/minecraft:tinted_glass.png'),
(852, 'Red Tulip', '/items/minecraft:red_tulip.png'),
(853, 'Spectral Arrow', '/items/minecraft:spectral_arrow.png'),
(854, 'Glowstone Dust', '/items/minecraft:glowstone_dust.png'),
(855, 'Mangrove Trapdoor', '/items/minecraft:mangrove_trapdoor.png'),
(856, 'Stripped Cherry Wood', '/items/minecraft:stripped_cherry_wood.png'),
(857, 'Netherite Boots', '/items/minecraft:netherite_boots.png'),
(858, 'Birch Hanging Sign', '/items/minecraft:birch_hanging_sign.png'),
(859, 'Black Candle', '/items/minecraft:black_candle.png'),
(860, 'Silence Armor Trim Smithing Template', '/items/minecraft:silence_armor_trim_smithing_template.png'),
(861, 'Green Concrete Powder', '/items/minecraft:green_concrete_powder.png'),
(862, 'Birch Trapdoor', '/items/minecraft:birch_trapdoor.png'),
(863, 'Leather Horse Armor', '/items/minecraft:leather_horse_armor.png'),
(864, 'Spruce Wood', '/items/minecraft:spruce_wood.png'),
(865, 'Spruce Log', '/items/minecraft:spruce_log.png'),
(866, 'Detector Rail', '/items/minecraft:detector_rail.png'),
(867, 'Yellow Candle', '/items/minecraft:yellow_candle.png'),
(868, 'Acacia Chest Boat', '/items/minecraft:acacia_chest_boat.png'),
(869, 'Stonecutter', '/items/minecraft:stonecutter.png'),
(870, 'Cyan Terracotta', '/items/minecraft:cyan_terracotta.png'),
(871, 'Lime Terracotta', '/items/minecraft:lime_terracotta.png'),
(872, 'Golden Apple', '/items/minecraft:golden_apple.png'),
(873, 'Apple', '/items/minecraft:apple.png'),
(874, 'Iron Trapdoor', '/items/minecraft:iron_trapdoor.png'),
(875, 'White Stained Glass', '/items/minecraft:white_stained_glass.png'),
(876, 'Daylight Detector', '/items/minecraft:daylight_detector.png'),
(877, 'Rail', '/items/minecraft:rail.png'),
(878, 'Stripped Jungle Wood', '/items/minecraft:stripped_jungle_wood.png'),
(879, 'Flower Banner Pattern', '/items/minecraft:flower_banner_pattern.png'),
(880, 'Diamond Boots', '/items/minecraft:diamond_boots.png'),
(881, 'Warped Stairs', '/items/minecraft:warped_stairs.png'),
(882, 'Cracked Stone Bricks', '/items/minecraft:cracked_stone_bricks.png'),
(883, 'Oak Slab', '/items/minecraft:oak_slab.png'),
(884, 'Leather Boots', '/items/minecraft:leather_boots.png'),
(885, 'Stripped Crimson Hyphae', '/items/minecraft:stripped_crimson_hyphae.png'),
(886, 'Cherry Door', '/items/minecraft:cherry_door.png'),
(887, 'Cherry Chest Boat', '/items/minecraft:cherry_chest_boat.png'),
(888, 'Cherry Boat', '/items/minecraft:cherry_boat.png'),
(889, 'White Concrete Powder', '/items/minecraft:white_concrete_powder.png'),
(890, 'Anvil', '/items/minecraft:anvil.png'),
(891, 'Warped Slab', '/items/minecraft:warped_slab.png'),
(892, 'Host Armor Trim Smithing Template', '/items/minecraft:host_armor_trim_smithing_template.png'),
(893, 'Oak Hanging Sign', '/items/minecraft:oak_hanging_sign.png'),
(894, 'Light Gray Concrete Powder', '/items/minecraft:light_gray_concrete_powder.png'),
(895, 'Map', '/items/minecraft:map.png'),
(896, 'Sponge', '/items/minecraft:sponge.png'),
(897, 'Wet Sponge', '/items/minecraft:wet_sponge.png'),
(898, 'Orange Tulip', '/items/minecraft:orange_tulip.png'),
(899, 'Cyan Candle', '/items/minecraft:cyan_candle.png'),
(900, 'Jungle Door', '/items/minecraft:jungle_door.png'),
(901, 'Conduit', '/items/minecraft:conduit.png'),
(902, 'Nautilus Shell', '/items/minecraft:nautilus_shell.png'),
(903, 'Heart Of The Sea', '/items/minecraft:heart_of_the_sea.png'),
(904, 'Muddy Mangrove Roots', '/items/minecraft:muddy_mangrove_roots.png'),
(905, 'Mangrove Roots', '/items/minecraft:mangrove_roots.png'),
(906, 'Iron Door', '/items/minecraft:iron_door.png'),
(907, 'Armor Stand', '/items/minecraft:armor_stand.png'),
(908, 'Magenta Concrete Powder', '/items/minecraft:magenta_concrete_powder.png'),
(909, 'Diamond Leggings', '/items/minecraft:diamond_leggings.png'),
(910, 'Lime Glazed Terracotta', '/items/minecraft:lime_glazed_terracotta.png'),
(911, 'Dark Oak Slab', '/items/minecraft:dark_oak_slab.png'),
(912, 'Acacia Trapdoor', '/items/minecraft:acacia_trapdoor.png'),
(913, 'Diamond Helmet', '/items/minecraft:diamond_helmet.png'),
(914, 'Green Banner', '/items/minecraft:green_banner.png'),
(915, 'Jungle Pressure Plate', '/items/minecraft:jungle_pressure_plate.png'),
(916, 'Black Stained Glass', '/items/minecraft:black_stained_glass.png'),
(917, 'Azure Bluet', '/items/minecraft:azure_bluet.png'),
(918, 'Nether Brick Fence', '/items/minecraft:nether_brick_fence.png'),
(919, 'Repeater', '/items/minecraft:repeater.png'),
(920, 'Tide Armor Trim Smithing Template', '/items/minecraft:tide_armor_trim_smithing_template.png'),
(921, 'Ice', '/items/minecraft:ice.png'),
(922, 'Black Concrete Powder', '/items/minecraft:black_concrete_powder.png'),
(923, 'Cyan Glazed Terracotta', '/items/minecraft:cyan_glazed_terracotta.png'),
(924, 'Polished Blackstone Pressure Plate', '/items/minecraft:polished_blackstone_pressure_plate.png'),
(925, 'Jungle Button', '/items/minecraft:jungle_button.png'),
(926, 'Spruce Button', '/items/minecraft:spruce_button.png'),
(927, 'Polished Blackstone Button', '/items/minecraft:polished_blackstone_button.png'),
(928, 'Recovery Compass', '/items/minecraft:recovery_compass.png'),
(929, 'Echo Shard', '/items/minecraft:echo_shard.png'),
(930, ':wart Blocks', '/items/#minecraft:wart_blocks.png'),
(931, ':logs', '/items/#minecraft:logs.png'),
(932, ':leaves', '/items/#minecraft:leaves.png'),
(933, 'Sweet Berries', '/items/minecraft:sweet_berries.png'),
(934, 'Glow Berries', '/items/minecraft:glow_berries.png'),
(935, 'Pufferfish', '/items/minecraft:pufferfish.png'),
(936, 'Tropical Fish', '/items/minecraft:tropical_fish.png'),
(937, 'Suspicious Sand', '/items/minecraft:suspicious_sand.png'),
(938, ':wooden Trapdoors', '/items/#minecraft:wooden_trapdoors.png'),
(939, 'Beetroot Seeds', '/items/minecraft:beetroot_seeds.png'),
(940, 'Torchflower Seeds', '/items/minecraft:torchflower_seeds.png'),
(941, 'Pitcher Pod', '/items/minecraft:pitcher_pod.png'),
(942, 'Wheat Seeds', '/items/minecraft:wheat_seeds.png'),
(943, 'Music Disc Otherside', '/items/minecraft:music_disc_otherside.png'),
(944, 'Music Disc Pigstep', '/items/minecraft:music_disc_pigstep.png'),
(945, 'Music Disc Relic', '/items/minecraft:music_disc_relic.png'),
(946, ':creeper Drop Music Discs', '/items/#minecraft:creeper_drop_music_discs.png'),
(947, 'Tropical Fish Bucket', '/items/minecraft:tropical_fish_bucket.png'),
(948, ':crimson Stems', '/items/#minecraft:crimson_stems.png'),
(949, ':logs That Burn', '/items/#minecraft:logs_that_burn.png'),
(950, ':warped Stems', '/items/#minecraft:warped_stems.png'),
(951, 'Written Book', '/items/minecraft:written_book.png'),
(952, ':decorated Pot Sherds', '/items/#minecraft:decorated_pot_sherds.png'),
(953, 'Cherry Sapling', '/items/minecraft:cherry_sapling.png'),
(954, 'Oak Sapling', '/items/minecraft:oak_sapling.png'),
(955, 'Acacia Sapling', '/items/minecraft:acacia_sapling.png'),
(956, 'Birch Sapling', '/items/minecraft:birch_sapling.png'),
(957, 'Spruce Sapling', '/items/minecraft:spruce_sapling.png'),
(958, 'Mangrove Propagule', '/items/minecraft:mangrove_propagule.png'),
(959, 'Dark Oak Sapling', '/items/minecraft:dark_oak_sapling.png'),
(960, 'Azalea', '/items/minecraft:azalea.png'),
(961, 'Jungle Sapling', '/items/minecraft:jungle_sapling.png'),
(962, 'Flowering Azalea', '/items/minecraft:flowering_azalea.png'),
(963, ':swords', '/items/#minecraft:swords.png'),
(964, ':hoes', '/items/#minecraft:hoes.png'),
(965, ':shovels', '/items/#minecraft:shovels.png'),
(966, ':pickaxes', '/items/#minecraft:pickaxes.png'),
(967, 'Trident', '/items/minecraft:trident.png'),
(968, ':axes', '/items/#minecraft:axes.png'),
(969, ':jungle Logs', '/items/#minecraft:jungle_logs.png'),
(970, ':birch Logs', '/items/#minecraft:birch_logs.png'),
(971, ':spruce Logs', '/items/#minecraft:spruce_logs.png'),
(972, ':acacia Logs', '/items/#minecraft:acacia_logs.png'),
(973, ':cherry Logs', '/items/#minecraft:cherry_logs.png'),
(974, ':mangrove Logs', '/items/#minecraft:mangrove_logs.png'),
(975, ':dark Oak Logs', '/items/#minecraft:dark_oak_logs.png'),
(976, ':oak Logs', '/items/#minecraft:oak_logs.png'),
(977, ':wooden Stairs', '/items/#minecraft:wooden_stairs.png'),
(978, 'Warped Wart Block', '/items/minecraft:warped_wart_block.png'),
(979, ':tools', '/items/#minecraft:tools.png'),
(980, ':wooden Fences', '/items/#minecraft:wooden_fences.png'),
(981, 'Player Head', '/items/minecraft:player_head.png'),
(982, 'Dragon Head', '/items/minecraft:dragon_head.png'),
(983, 'Piglin Head', '/items/minecraft:piglin_head.png'),
(984, 'Skeleton Skull', '/items/minecraft:skeleton_skull.png'),
(985, 'Zombie Head', '/items/minecraft:zombie_head.png'),
(986, ':wooden Slabs', '/items/#minecraft:wooden_slabs.png'),
(987, 'Petrified Oak Slab', '/items/minecraft:petrified_oak_slab.png'),
(988, ':chest Boats', '/items/#minecraft:chest_boats.png'),
(989, 'Explorer Pottery Sherd', '/items/minecraft:explorer_pottery_sherd.png'),
(990, 'Arms Up Pottery Sherd', '/items/minecraft:arms_up_pottery_sherd.png'),
(991, 'Burn Pottery Sherd', '/items/minecraft:burn_pottery_sherd.png'),
(992, 'Blade Pottery Sherd', '/items/minecraft:blade_pottery_sherd.png'),
(993, 'Snort Pottery Sherd', '/items/minecraft:snort_pottery_sherd.png'),
(994, 'Sheaf Pottery Sherd', '/items/minecraft:sheaf_pottery_sherd.png'),
(995, 'Heart Pottery Sherd', '/items/minecraft:heart_pottery_sherd.png'),
(996, 'Brewer Pottery Sherd', '/items/minecraft:brewer_pottery_sherd.png'),
(997, 'Angler Pottery Sherd', '/items/minecraft:angler_pottery_sherd.png'),
(998, 'Plenty Pottery Sherd', '/items/minecraft:plenty_pottery_sherd.png'),
(999, 'Danger Pottery Sherd', '/items/minecraft:danger_pottery_sherd.png'),
(1000, 'Archer Pottery Sherd', '/items/minecraft:archer_pottery_sherd.png'),
(1001, 'Miner Pottery Sherd', '/items/minecraft:miner_pottery_sherd.png'),
(1002, 'Mourner Pottery Sherd', '/items/minecraft:mourner_pottery_sherd.png'),
(1003, 'Friend Pottery Sherd', '/items/minecraft:friend_pottery_sherd.png'),
(1004, 'Howl Pottery Sherd', '/items/minecraft:howl_pottery_sherd.png'),
(1005, 'Prize Pottery Sherd', '/items/minecraft:prize_pottery_sherd.png'),
(1006, 'Heartbreak Pottery Sherd', '/items/minecraft:heartbreak_pottery_sherd.png'),
(1007, 'Shelter Pottery Sherd', '/items/minecraft:shelter_pottery_sherd.png'),
(1008, 'Skull Pottery Sherd', '/items/minecraft:skull_pottery_sherd.png'),
(1009, 'Music Disc Chirp', '/items/minecraft:music_disc_chirp.png'),
(1010, 'Music Disc Stal', '/items/minecraft:music_disc_stal.png'),
(1011, 'Music Disc Far', '/items/minecraft:music_disc_far.png'),
(1012, 'Music Disc Strad', '/items/minecraft:music_disc_strad.png'),
(1013, 'Music Disc Ward', '/items/minecraft:music_disc_ward.png'),
(1014, 'Music Disc 13', '/items/minecraft:music_disc_13.png'),
(1015, 'Music Disc Blocks', '/items/minecraft:music_disc_blocks.png'),
(1016, 'Music Disc Mellohi', '/items/minecraft:music_disc_mellohi.png'),
(1017, 'Music Disc Cat', '/items/minecraft:music_disc_cat.png'),
(1018, 'Music Disc 11', '/items/minecraft:music_disc_11.png'),
(1019, 'Music Disc Wait', '/items/minecraft:music_disc_wait.png'),
(1020, 'Music Disc Mall', '/items/minecraft:music_disc_mall.png'),
(1021, 'Flowering Azalea Leaves', '/items/minecraft:flowering_azalea_leaves.png'),
(1022, 'Chorus Flower', '/items/minecraft:chorus_flower.png'),
(1023, 'Spore Blossom', '/items/minecraft:spore_blossom.png'),
(1024, 'Cherry Leaves', '/items/minecraft:cherry_leaves.png'),
(1025, ':tall Flowers', '/items/#minecraft:tall_flowers.png'),
(1026, ':small Flowers', '/items/#minecraft:small_flowers.png'),
(1027, 'Podzol', '/items/minecraft:podzol.png'),
(1028, 'Mycelium', '/items/minecraft:mycelium.png'),
(1029, 'Rooted Dirt', '/items/minecraft:rooted_dirt.png'),
(1030, 'Grass Block', '/items/minecraft:grass_block.png'),
(1031, 'Oak Leaves', '/items/minecraft:oak_leaves.png'),
(1032, 'Dark Oak Leaves', '/items/minecraft:dark_oak_leaves.png'),
(1033, 'Mangrove Leaves', '/items/minecraft:mangrove_leaves.png'),
(1034, 'Birch Leaves', '/items/minecraft:birch_leaves.png'),
(1035, 'Acacia Leaves', '/items/minecraft:acacia_leaves.png'),
(1036, 'Spruce Leaves', '/items/minecraft:spruce_leaves.png'),
(1037, 'Jungle Leaves', '/items/minecraft:jungle_leaves.png'),
(1038, 'Azalea Leaves', '/items/minecraft:azalea_leaves.png'),
(1039, ':gold Ores', '/items/#minecraft:gold_ores.png'),
(1040, 'Bell', '/items/minecraft:bell.png'),
(1041, 'Gilded Blackstone', '/items/minecraft:gilded_blackstone.png'),
(1042, ':wooden Doors', '/items/#minecraft:wooden_doors.png'),
(1043, 'Damaged Anvil', '/items/minecraft:damaged_anvil.png'),
(1044, 'Chipped Anvil', '/items/minecraft:chipped_anvil.png'),
(1045, ':wooden Buttons', '/items/#minecraft:wooden_buttons.png'),
(1046, ':stone Buttons', '/items/#minecraft:stone_buttons.png'),
(1047, 'Knowledge Book', '/items/minecraft:knowledge_book.png'),
(1048, 'Enchanted Book', '/items/minecraft:enchanted_book.png'),
(1049, 'Tipped Arrow', '/items/minecraft:tipped_arrow.png'),
(1050, 'Soul Sand', '/items/minecraft:soul_sand.png'),
(1051, 'Soul Soil', '/items/minecraft:soul_soil.png'),
(1052, ':wool Carpets', '/items/#minecraft:wool_carpets.png'),
(1053, ':wool', '/items/#minecraft:wool.png'),
(1054, 'Saddle', '/items/minecraft:saddle.png'),
(1055, 'Diamond Horse Armor', '/items/minecraft:diamond_horse_armor.png'),
(1056, 'Name Tag', '/items/minecraft:name_tag.png'),
(1057, 'Suspicious Stew', '/items/minecraft:suspicious_stew.png'),
(1058, 'Sculk Catalyst', '/items/minecraft:sculk_catalyst.png'),
(1059, 'Sculk', '/items/minecraft:sculk.png'),
(1060, 'Experience Bottle', '/items/minecraft:experience_bottle.png'),
(1061, 'Potion', '/items/minecraft:potion.png'),
(1062, 'Crimson Nylium', '/items/minecraft:crimson_nylium.png'),
(1063, 'Crimson Fungus', '/items/minecraft:crimson_fungus.png'),
(1064, 'Crimson Roots', '/items/minecraft:crimson_roots.png'),
(1065, 'Piglin Banner Pattern', '/items/minecraft:piglin_banner_pattern.png'),
(1066, 'Rotten Flesh', '/items/minecraft:rotten_flesh.png'),
(1067, 'Gameplay/fishing/fish', '/items/minecraft:gameplay/fishing/fish.png'),
(1068, 'Totem Of Undying', '/items/minecraft:totem_of_undying.png'),
(1069, 'Creeper Drop Music Discs', '/items/minecraft:creeper_drop_music_discs.png'),
(1070, 'Phantom Membrane', '/items/minecraft:phantom_membrane.png'),
(1071, 'Pearlescent Froglight', '/items/minecraft:pearlescent_froglight.png'),
(1072, 'Verdant Froglight', '/items/minecraft:verdant_froglight.png'),
(1073, 'Ochre Froglight', '/items/minecraft:ochre_froglight.png'),
(1074, 'Seagrass', '/items/minecraft:seagrass.png'),
(1075, 'Rabbit Foot', '/items/minecraft:rabbit_foot.png'),
(1076, 'Lily Pad', '/items/minecraft:lily_pad.png'),
(1077, 'Splash Potion', '/items/minecraft:splash_potion.png'),
(1078, 'Gameplay/fishing/junk', '/items/minecraft:gameplay/fishing/junk.png'),
(1079, 'Gameplay/fishing/treasure', '/items/minecraft:gameplay/fishing/treasure.png');
