INSERT INTO item (id, name, image) VALUES 
(1, "Dropper", "/items/minecraft:dropper.png"),
(2, "Cobblestone", "/items/minecraft:cobblestone.png"),
(3, "Redstone", "/items/minecraft:redstone.png"),
(4, "Jungle Fence Gate", "/items/minecraft:jungle_fence_gate.png"),
(5, "Stick", "/items/minecraft:stick.png"),
(6, "Jungle Planks", "/items/minecraft:jungle_planks.png"),
(7, "Stone Pressure Plate", "/items/minecraft:stone_pressure_plate.png"),
(8, "Stone", "/items/minecraft:stone.png"),
(9, "Bamboo Block", "/items/minecraft:bamboo_block.png"),
(10, "Bamboo", "/items/minecraft:bamboo.png"),
(11, "Cooked Porkchop", "/items/minecraft:cooked_porkchop.png"),
(12, "Polished Deepslate", "/items/minecraft:polished_deepslate.png"),
(13, "Pink Bed", "/items/minecraft:pink_bed.png"),
(14, "Pink Dye", "/items/minecraft:pink_dye.png"),
(15, "Black Bed", "/items/minecraft:black_bed.png"),
(16, "Blue Bed", "/items/minecraft:blue_bed.png"),
(17, "Brown Bed", "/items/minecraft:brown_bed.png"),
(18, "Cyan Bed", "/items/minecraft:cyan_bed.png"),
(19, "Gray Bed", "/items/minecraft:gray_bed.png"),
(20, "Green Bed", "/items/minecraft:green_bed.png"),
(21, "Light Blue Bed", "/items/minecraft:light_blue_bed.png"),
(22, "Light Gray Bed", "/items/minecraft:light_gray_bed.png"),
(23, "Lime Bed", "/items/minecraft:lime_bed.png"),
(24, "Magenta Bed", "/items/minecraft:magenta_bed.png"),
(25, "Orange Bed", "/items/minecraft:orange_bed.png"),
(26, "Purple Bed", "/items/minecraft:purple_bed.png"),
(27, "Red Bed", "/items/minecraft:red_bed.png"),
(28, "Yellow Bed", "/items/minecraft:yellow_bed.png"),
(29, "White Bed", "/items/minecraft:white_bed.png"),
(30, "Dune Armor Trim Smithing Template", "/items/minecraft:dune_armor_trim_smithing_template.png"),
(31, "Diamond", "/items/minecraft:diamond.png"),
(32, "Sandstone", "/items/minecraft:sandstone.png"),
(33, "Diorite Stairs", "/items/minecraft:diorite_stairs.png"),
(34, "Acacia Door", "/items/minecraft:acacia_door.png"),
(35, "Acacia Planks", "/items/minecraft:acacia_planks.png"),
(36, "Spruce Slab", "/items/minecraft:spruce_slab.png"),
(37, "Spruce Planks", "/items/minecraft:spruce_planks.png"),
(38, "Cracked Deepslate Bricks", "/items/minecraft:cracked_deepslate_bricks.png"),
(39, "Gray Terracotta", "/items/minecraft:gray_terracotta.png"),
(40, "Terracotta", "/items/minecraft:terracotta.png"),
(41, "Gray Dye", "/items/minecraft:gray_dye.png"),
(42, "End Stone Brick Slab", "/items/minecraft:end_stone_brick_slab.png"),
(43, "Red Glazed Terracotta", "/items/minecraft:red_glazed_terracotta.png"),
(44, "Gold Ingot", "/items/minecraft:gold_ingot.png"),
(45, "Cobbled Deepslate Stairs", "/items/minecraft:cobbled_deepslate_stairs.png"),
(46, "Cobbled Deepslate Wall", "/items/minecraft:cobbled_deepslate_wall.png"),
(47, "Smooth Red Sandstone Slab", "/items/minecraft:smooth_red_sandstone_slab.png"),
(48, "Brown Concrete Powder", "/items/minecraft:brown_concrete_powder.png"),
(49, "Brown Dye", "/items/minecraft:brown_dye.png"),
(50, "Sand", "/items/minecraft:sand.png"),
(51, "Gravel", "/items/minecraft:gravel.png"),
(52, "Pink Terracotta", "/items/minecraft:pink_terracotta.png"),
(53, "Smooth Basalt", "/items/minecraft:smooth_basalt.png"),
(54, "Furnace Minecart", "/items/minecraft:furnace_minecart.png"),
(55, "Furnace", "/items/minecraft:furnace.png"),
(56, "Minecart", "/items/minecraft:minecart.png"),
(57, "Dark Oak Planks", "/items/minecraft:dark_oak_planks.png"),
(58, "Deepslate Tile Stairs", "/items/minecraft:deepslate_tile_stairs.png"),
(59, "Bucket", "/items/minecraft:bucket.png"),
(60, "Iron Ingot", "/items/minecraft:iron_ingot.png"),
(61, "Blue Stained Glass Pane", "/items/minecraft:blue_stained_glass_pane.png"),
(62, "Blue Stained Glass", "/items/minecraft:blue_stained_glass.png"),
(63, "Lime Dye", "/items/minecraft:lime_dye.png"),
(64, "Cobbled Deepslate Slab", "/items/minecraft:cobbled_deepslate_slab.png"),
(65, "Beehive", "/items/minecraft:beehive.png"),
(66, "Honeycomb", "/items/minecraft:honeycomb.png"),
(67, "Campfire", "/items/minecraft:campfire.png"),
(68, "Lime Wool", "/items/minecraft:lime_wool.png"),
(69, "Black Wool", "/items/minecraft:black_wool.png"),
(70, "Blue Wool", "/items/minecraft:blue_wool.png"),
(71, "Brown Wool", "/items/minecraft:brown_wool.png"),
(72, "Cyan Wool", "/items/minecraft:cyan_wool.png"),
(73, "Gray Wool", "/items/minecraft:gray_wool.png"),
(74, "Green Wool", "/items/minecraft:green_wool.png"),
(75, "Light Blue Wool", "/items/minecraft:light_blue_wool.png"),
(76, "Light Gray Wool", "/items/minecraft:light_gray_wool.png"),
(77, "Magenta Wool", "/items/minecraft:magenta_wool.png"),
(78, "Orange Wool", "/items/minecraft:orange_wool.png"),
(79, "Pink Wool", "/items/minecraft:pink_wool.png"),
(80, "Purple Wool", "/items/minecraft:purple_wool.png"),
(81, "Red Wool", "/items/minecraft:red_wool.png"),
(82, "Yellow Wool", "/items/minecraft:yellow_wool.png"),
(83, "White Wool", "/items/minecraft:white_wool.png"),
(84, "White Terracotta", "/items/minecraft:white_terracotta.png"),
(85, "White Dye", "/items/minecraft:white_dye.png"),
(86, "Chiseled Red Sandstone", "/items/minecraft:chiseled_red_sandstone.png"),
(87, "Red Sandstone Slab", "/items/minecraft:red_sandstone_slab.png"),
(88, "White Banner", "/items/minecraft:white_banner.png"),
(89, "Light Gray Stained Glass Pane", "/items/minecraft:light_gray_stained_glass_pane.png"),
(90, "Glass Pane", "/items/minecraft:glass_pane.png"),
(91, "Light Gray Dye", "/items/minecraft:light_gray_dye.png"),
(92, "Powered Rail", "/items/minecraft:powered_rail.png"),
(93, "Waxed Oxidized Copper", "/items/minecraft:waxed_oxidized_copper.png"),
(94, "Oxidized Copper", "/items/minecraft:oxidized_copper.png"),
(95, "Oak Wood", "/items/minecraft:oak_wood.png"),
(96, "Oak Log", "/items/minecraft:oak_log.png"),
(97, "Red Terracotta", "/items/minecraft:red_terracotta.png"),
(98, "Red Dye", "/items/minecraft:red_dye.png"),
(99, "Lapis Block", "/items/minecraft:lapis_block.png"),
(100, "Lapis Lazuli", "/items/minecraft:lapis_lazuli.png"),
(101, "Blackstone Stairs", "/items/minecraft:blackstone_stairs.png"),
(102, "Blackstone", "/items/minecraft:blackstone.png"),
(103, "Honey Bottle", "/items/minecraft:honey_bottle.png"),
(104, "Honey Block", "/items/minecraft:honey_block.png"),
(105, "Glass Bottle", "/items/minecraft:glass_bottle.png"),
(106, "Blue Dye", "/items/minecraft:blue_dye.png"),
(107, "Brown Terracotta", "/items/minecraft:brown_terracotta.png"),
(108, "Cobblestone Wall", "/items/minecraft:cobblestone_wall.png"),
(109, "Cauldron", "/items/minecraft:cauldron.png"),
(110, "Cut Copper Stairs", "/items/minecraft:cut_copper_stairs.png"),
(111, "Oak Fence Gate", "/items/minecraft:oak_fence_gate.png"),
(112, "Oak Planks", "/items/minecraft:oak_planks.png"),
(113, "Blue Terracotta", "/items/minecraft:blue_terracotta.png"),
(114, "Red Sandstone Wall", "/items/minecraft:red_sandstone_wall.png"),
(115, "Red Sandstone", "/items/minecraft:red_sandstone.png"),
(116, "Stone Shovel", "/items/minecraft:stone_shovel.png"),
(117, "Packed Mud", "/items/minecraft:packed_mud.png"),
(118, "Mud", "/items/minecraft:mud.png"),
(119, "Wheat", "/items/minecraft:wheat.png"),
(120, "Glass", "/items/minecraft:glass.png"),
(121, "Gold Nugget", "/items/minecraft:gold_nugget.png"),
(122, "Jungle Stairs", "/items/minecraft:jungle_stairs.png"),
(123, "Spruce Stairs", "/items/minecraft:spruce_stairs.png"),
(124, "Polished Blackstone Slab", "/items/minecraft:polished_blackstone_slab.png"),
(125, "Spruce Fence Gate", "/items/minecraft:spruce_fence_gate.png"),
(126, "Polished Blackstone Stairs", "/items/minecraft:polished_blackstone_stairs.png"),
(127, "Polished Blackstone", "/items/minecraft:polished_blackstone.png"),
(128, "Oxeye Daisy", "/items/minecraft:oxeye_daisy.png"),
(129, "Leather Chestplate", "/items/minecraft:leather_chestplate.png"),
(130, "Leather", "/items/minecraft:leather.png"),
(131, "Golden Carrot", "/items/minecraft:golden_carrot.png"),
(132, "Carrot", "/items/minecraft:carrot.png"),
(133, "Smooth Quartz Slab", "/items/minecraft:smooth_quartz_slab.png"),
(134, "Smooth Quartz", "/items/minecraft:smooth_quartz.png"),
(135, "Oxidized Cut Copper Slab", "/items/minecraft:oxidized_cut_copper_slab.png"),
(136, "Oxidized Cut Copper", "/items/minecraft:oxidized_cut_copper.png"),
(137, "Deepslate Bricks", "/items/minecraft:deepslate_bricks.png"),
(138, "Magenta Glazed Terracotta", "/items/minecraft:magenta_glazed_terracotta.png"),
(139, "Deepslate Brick Wall", "/items/minecraft:deepslate_brick_wall.png"),
(140, "Fletching Table", "/items/minecraft:fletching_table.png"),
(141, "Flint", "/items/minecraft:flint.png"),
(142, "Glow Item Frame", "/items/minecraft:glow_item_frame.png"),
(143, "Item Frame", "/items/minecraft:item_frame.png"),
(144, "Glow Ink Sac", "/items/minecraft:glow_ink_sac.png"),
(145, "Stripped Dark Oak Wood", "/items/minecraft:stripped_dark_oak_wood.png"),
(146, "Stripped Dark Oak Log", "/items/minecraft:stripped_dark_oak_log.png"),
(147, "Stone Bricks", "/items/minecraft:stone_bricks.png"),
(148, "Deepslate Brick Stairs", "/items/minecraft:deepslate_brick_stairs.png"),
(149, "Brick Wall", "/items/minecraft:brick_wall.png"),
(150, "Bricks", "/items/minecraft:bricks.png"),
(151, "Redstone Lamp", "/items/minecraft:redstone_lamp.png"),
(152, "Glowstone", "/items/minecraft:glowstone.png"),
(153, "Brown Banner", "/items/minecraft:brown_banner.png"),
(154, "Light Gray Stained Glass", "/items/minecraft:light_gray_stained_glass.png"),
(155, "Blue Banner", "/items/minecraft:blue_banner.png"),
(156, "Crimson Door", "/items/minecraft:crimson_door.png"),
(157, "Crimson Planks", "/items/minecraft:crimson_planks.png"),
(158, "Clock", "/items/minecraft:clock.png"),
(159, "Light Blue Banner", "/items/minecraft:light_blue_banner.png"),
(160, "Purpur Block", "/items/minecraft:purpur_block.png"),
(161, "Popped Chorus Fruit", "/items/minecraft:popped_chorus_fruit.png"),
(162, "Cut Red Sandstone", "/items/minecraft:cut_red_sandstone.png"),
(163, "Sandstone Wall", "/items/minecraft:sandstone_wall.png"),
(164, "Warped Hyphae", "/items/minecraft:warped_hyphae.png"),
(165, "Warped Stem", "/items/minecraft:warped_stem.png"),
(166, "Waxed Oxidized Cut Copper", "/items/minecraft:waxed_oxidized_cut_copper.png"),
(167, "Diorite Slab", "/items/minecraft:diorite_slab.png"),
(168, "Green Dye", "/items/minecraft:green_dye.png"),
(169, "Mossy Stone Bricks", "/items/minecraft:mossy_stone_bricks.png"),
(170, "Moss Block", "/items/minecraft:moss_block.png"),
(171, "Mangrove Hanging Sign", "/items/minecraft:mangrove_hanging_sign.png"),
(172, "Stripped Mangrove Log", "/items/minecraft:stripped_mangrove_log.png"),
(173, "Chain", "/items/minecraft:chain.png"),
(174, "Cooked Chicken", "/items/minecraft:cooked_chicken.png"),
(175, "Waxed Exposed Copper", "/items/minecraft:waxed_exposed_copper.png"),
(176, "Exposed Copper", "/items/minecraft:exposed_copper.png"),
(177, "Wayfinder Armor Trim Smithing Template", "/items/minecraft:wayfinder_armor_trim_smithing_template.png"),
(178, "Waxed Exposed Cut Copper Slab", "/items/minecraft:waxed_exposed_cut_copper_slab.png"),
(179, "Waxed Exposed Cut Copper", "/items/minecraft:waxed_exposed_cut_copper.png"),
(180, "Baked Potato", "/items/minecraft:baked_potato.png"),
(181, "Sugar", "/items/minecraft:sugar.png"),
(182, "Observer", "/items/minecraft:observer.png"),
(183, "Quartz", "/items/minecraft:quartz.png"),
(184, "Pink Banner", "/items/minecraft:pink_banner.png"),
(185, "Waxed Oxidized Cut Copper Slab", "/items/minecraft:waxed_oxidized_cut_copper_slab.png"),
(186, "Smooth Sandstone", "/items/minecraft:smooth_sandstone.png"),
(187, "Dark Oak Trapdoor", "/items/minecraft:dark_oak_trapdoor.png"),
(188, "Purple Dye", "/items/minecraft:purple_dye.png"),
(189, "Waxed Weathered Cut Copper Stairs", "/items/minecraft:waxed_weathered_cut_copper_stairs.png"),
(190, "Candle", "/items/minecraft:candle.png"),
(191, "String", "/items/minecraft:string.png"),
(192, "Lantern", "/items/minecraft:lantern.png"),
(193, "Torch", "/items/minecraft:torch.png"),
(194, "Iron Nugget", "/items/minecraft:iron_nugget.png"),
(195, "Polished Granite Stairs", "/items/minecraft:polished_granite_stairs.png"),
(196, "Polished Granite", "/items/minecraft:polished_granite.png"),
(197, "Waxed Weathered Cut Copper", "/items/minecraft:waxed_weathered_cut_copper.png"),
(198, "Mossy Cobblestone Wall", "/items/minecraft:mossy_cobblestone_wall.png"),
(199, "Light Weighted Pressure Plate", "/items/minecraft:light_weighted_pressure_plate.png"),
(200, "Green Terracotta", "/items/minecraft:green_terracotta.png"),
(201, "Cracked Nether Bricks", "/items/minecraft:cracked_nether_bricks.png"),
(202, "Mossy Cobblestone Stairs", "/items/minecraft:mossy_cobblestone_stairs.png"),
(203, "Cherry Fence", "/items/minecraft:cherry_fence.png"),
(204, "Cherry Planks", "/items/minecraft:cherry_planks.png"),
(205, "Polished Deepslate Stairs", "/items/minecraft:polished_deepslate_stairs.png"),
(206, "Slime Ball", "/items/minecraft:slime_ball.png"),
(207, "Slime Block", "/items/minecraft:slime_block.png"),
(208, "Iron Block", "/items/minecraft:iron_block.png"),
(209, "Birch Pressure Plate", "/items/minecraft:birch_pressure_plate.png"),
(210, "Birch Planks", "/items/minecraft:birch_planks.png"),
(211, "Hopper Minecart", "/items/minecraft:hopper_minecart.png"),
(212, "Hopper", "/items/minecraft:hopper.png"),
(213, "Copper Block", "/items/minecraft:copper_block.png"),
(214, "Copper Ingot", "/items/minecraft:copper_ingot.png"),
(215, "Nether Brick Slab", "/items/minecraft:nether_brick_slab.png"),
(216, "Nether Bricks", "/items/minecraft:nether_bricks.png"),
(217, "End Crystal", "/items/minecraft:end_crystal.png"),
(218, "Ender Eye", "/items/minecraft:ender_eye.png"),
(219, "Ghast Tear", "/items/minecraft:ghast_tear.png"),
(220, "Acacia Boat", "/items/minecraft:acacia_boat.png"),
(221, "Weathered Cut Copper", "/items/minecraft:weathered_cut_copper.png"),
(222, "Weathered Copper", "/items/minecraft:weathered_copper.png"),
(223, "Oak Sign", "/items/minecraft:oak_sign.png"),
(224, "Polished Blackstone Brick Slab", "/items/minecraft:polished_blackstone_brick_slab.png"),
(225, "Cyan Carpet", "/items/minecraft:cyan_carpet.png"),
(226, "Cyan Dye", "/items/minecraft:cyan_dye.png"),
(227, "Black Carpet", "/items/minecraft:black_carpet.png"),
(228, "Blue Carpet", "/items/minecraft:blue_carpet.png"),
(229, "Brown Carpet", "/items/minecraft:brown_carpet.png"),
(230, "Gray Carpet", "/items/minecraft:gray_carpet.png"),
(231, "Green Carpet", "/items/minecraft:green_carpet.png"),
(232, "Light Blue Carpet", "/items/minecraft:light_blue_carpet.png"),
(233, "Light Gray Carpet", "/items/minecraft:light_gray_carpet.png"),
(234, "Lime Carpet", "/items/minecraft:lime_carpet.png"),
(235, "Magenta Carpet", "/items/minecraft:magenta_carpet.png"),
(236, "Orange Carpet", "/items/minecraft:orange_carpet.png"),
(237, "Pink Carpet", "/items/minecraft:pink_carpet.png"),
(238, "Purple Carpet", "/items/minecraft:purple_carpet.png"),
(239, "Red Carpet", "/items/minecraft:red_carpet.png"),
(240, "Yellow Carpet", "/items/minecraft:yellow_carpet.png"),
(241, "White Carpet", "/items/minecraft:white_carpet.png"),
(242, "Yellow Concrete Powder", "/items/minecraft:yellow_concrete_powder.png"),
(243, "Yellow Dye", "/items/minecraft:yellow_dye.png"),
(244, "Diamond Sword", "/items/minecraft:diamond_sword.png"),
(245, "Mossy Cobblestone Slab", "/items/minecraft:mossy_cobblestone_slab.png"),
(246, "Waxed Cut Copper Stairs", "/items/minecraft:waxed_cut_copper_stairs.png"),
(247, "Coarse Dirt", "/items/minecraft:coarse_dirt.png"),
(248, "Dirt", "/items/minecraft:dirt.png"),
(249, "Warped Fence", "/items/minecraft:warped_fence.png"),
(250, "Warped Planks", "/items/minecraft:warped_planks.png"),
(251, "Bamboo Pressure Plate", "/items/minecraft:bamboo_pressure_plate.png"),
(252, "Bamboo Planks", "/items/minecraft:bamboo_planks.png"),
(253, "Chiseled Stone Bricks", "/items/minecraft:chiseled_stone_bricks.png"),
(254, "Stone Brick Slab", "/items/minecraft:stone_brick_slab.png"),
(255, "Andesite", "/items/minecraft:andesite.png"),
(256, "Diorite", "/items/minecraft:diorite.png"),
(257, "Brush", "/items/minecraft:brush.png"),
(258, "Feather", "/items/minecraft:feather.png"),
(259, "Brown Stained Glass", "/items/minecraft:brown_stained_glass.png"),
(260, "Cyan Concrete Powder", "/items/minecraft:cyan_concrete_powder.png"),
(261, "Andesite Wall", "/items/minecraft:andesite_wall.png"),
(262, "Stone Sword", "/items/minecraft:stone_sword.png"),
(263, "Waxed Cut Copper", "/items/minecraft:waxed_cut_copper.png"),
(264, "Waxed Copper Block", "/items/minecraft:waxed_copper_block.png"),
(265, "Birch Door", "/items/minecraft:birch_door.png"),
(266, "Redstone Block", "/items/minecraft:redstone_block.png"),
(267, "Comparator", "/items/minecraft:comparator.png"),
(268, "Redstone Torch", "/items/minecraft:redstone_torch.png"),
(269, "Mangrove Door", "/items/minecraft:mangrove_door.png"),
(270, "Mangrove Planks", "/items/minecraft:mangrove_planks.png"),
(271, "Crimson Pressure Plate", "/items/minecraft:crimson_pressure_plate.png"),
(272, "Target", "/items/minecraft:target.png"),
(273, "Hay Block", "/items/minecraft:hay_block.png"),
(274, "Stripped Warped Hyphae", "/items/minecraft:stripped_warped_hyphae.png"),
(275, "Stripped Warped Stem", "/items/minecraft:stripped_warped_stem.png"),
(276, "Purple Candle", "/items/minecraft:purple_candle.png"),
(277, "Smooth Sandstone Stairs", "/items/minecraft:smooth_sandstone_stairs.png"),
(278, "Dark Oak Wood", "/items/minecraft:dark_oak_wood.png"),
(279, "Dark Oak Log", "/items/minecraft:dark_oak_log.png"),
(280, "Brown Glazed Terracotta", "/items/minecraft:brown_glazed_terracotta.png"),
(281, "Warped Sign", "/items/minecraft:warped_sign.png"),
(282, "Diamond Chestplate", "/items/minecraft:diamond_chestplate.png"),
(283, "Fishing Rod", "/items/minecraft:fishing_rod.png"),
(284, "Waxed Cut Copper Slab", "/items/minecraft:waxed_cut_copper_slab.png"),
(285, "Dark Oak Hanging Sign", "/items/minecraft:dark_oak_hanging_sign.png"),
(286, "Mushroom Stew", "/items/minecraft:mushroom_stew.png"),
(287, "Brown Mushroom", "/items/minecraft:brown_mushroom.png"),
(288, "Red Mushroom", "/items/minecraft:red_mushroom.png"),
(289, "Bowl", "/items/minecraft:bowl.png"),
(290, "Cobblestone Slab", "/items/minecraft:cobblestone_slab.png"),
(291, "Cookie", "/items/minecraft:cookie.png"),
(292, "Cocoa Beans", "/items/minecraft:cocoa_beans.png"),
(293, "Sentry Armor Trim Smithing Template", "/items/minecraft:sentry_armor_trim_smithing_template.png"),
(294, "Soul Torch", "/items/minecraft:soul_torch.png"),
(295, "Coal", "/items/minecraft:coal.png"),
(296, "Charcoal", "/items/minecraft:charcoal.png"),
(297, "Soul Lantern", "/items/minecraft:soul_lantern.png"),
(298, "End Stone Bricks", "/items/minecraft:end_stone_bricks.png"),
(299, "Polished Blackstone Wall", "/items/minecraft:polished_blackstone_wall.png"),
(300, "Polished Diorite Stairs", "/items/minecraft:polished_diorite_stairs.png"),
(301, "Orange Dye", "/items/minecraft:orange_dye.png"),
(302, "Torchflower", "/items/minecraft:torchflower.png"),
(303, "Spruce Fence", "/items/minecraft:spruce_fence.png"),
(304, "Granite Wall", "/items/minecraft:granite_wall.png"),
(305, "Deepslate Brick Slab", "/items/minecraft:deepslate_brick_slab.png"),
(306, "Bamboo Mosaic", "/items/minecraft:bamboo_mosaic.png"),
(307, "Bamboo Slab", "/items/minecraft:bamboo_slab.png"),
(308, "Warped Button", "/items/minecraft:warped_button.png"),
(309, "Waxed Oxidized Cut Copper Stairs", "/items/minecraft:waxed_oxidized_cut_copper_stairs.png"),
(310, "Oxidized Cut Copper Stairs", "/items/minecraft:oxidized_cut_copper_stairs.png"),
(311, "Sugar Cane", "/items/minecraft:sugar_cane.png"),
(312, "Light Blue Dye", "/items/minecraft:light_blue_dye.png"),
(313, "Blue Orchid", "/items/minecraft:blue_orchid.png"),
(314, "Deepslate Tile Slab", "/items/minecraft:deepslate_tile_slab.png"),
(315, "Light Gray Glazed Terracotta", "/items/minecraft:light_gray_glazed_terracotta.png"),
(316, "Shulker Box", "/items/minecraft:shulker_box.png"),
(317, "Chest", "/items/minecraft:chest.png"),
(318, "Shulker Shell", "/items/minecraft:shulker_shell.png"),
(319, "Music Disc 5", "/items/minecraft:music_disc_5.png"),
(320, "Disc Fragment 5", "/items/minecraft:disc_fragment_5.png"),
(321, "Melon", "/items/minecraft:melon.png"),
(322, "Melon Slice", "/items/minecraft:melon_slice.png"),
(323, "Dark Oak Sign", "/items/minecraft:dark_oak_sign.png"),
(324, "Polished Blackstone Bricks", "/items/minecraft:polished_blackstone_bricks.png"),
(325, "Cooked Salmon", "/items/minecraft:cooked_salmon.png"),
(326, "Sticky Piston", "/items/minecraft:sticky_piston.png"),
(327, "Piston", "/items/minecraft:piston.png"),
(328, "Trapped Chest", "/items/minecraft:trapped_chest.png"),
(329, "Tripwire Hook", "/items/minecraft:tripwire_hook.png"),
(330, "Dark Oak Fence Gate", "/items/minecraft:dark_oak_fence_gate.png"),
(331, "Sandstone Slab", "/items/minecraft:sandstone_slab.png"),
(332, "Chiseled Sandstone", "/items/minecraft:chiseled_sandstone.png"),
(333, "Ender Chest", "/items/minecraft:ender_chest.png"),
(334, "Obsidian", "/items/minecraft:obsidian.png"),
(335, "Smooth Red Sandstone", "/items/minecraft:smooth_red_sandstone.png"),
(336, "Orange Stained Glass Pane", "/items/minecraft:orange_stained_glass_pane.png"),
(337, "Acacia Pressure Plate", "/items/minecraft:acacia_pressure_plate.png"),
(338, "Brick Slab", "/items/minecraft:brick_slab.png"),
(339, "Bamboo Mosaic Stairs", "/items/minecraft:bamboo_mosaic_stairs.png"),
(340, "Emerald", "/items/minecraft:emerald.png"),
(341, "Emerald Block", "/items/minecraft:emerald_block.png"),
(342, "Pink Stained Glass", "/items/minecraft:pink_stained_glass.png"),
(343, "Cut Copper", "/items/minecraft:cut_copper.png"),
(344, "Purpur Slab", "/items/minecraft:purpur_slab.png"),
(345, "Purpur Pillar", "/items/minecraft:purpur_pillar.png"),
(346, "Mangrove Button", "/items/minecraft:mangrove_button.png"),
(347, "Leather Helmet", "/items/minecraft:leather_helmet.png"),
(348, "Polished Granite Slab", "/items/minecraft:polished_granite_slab.png"),
(349, "Red Sandstone Stairs", "/items/minecraft:red_sandstone_stairs.png"),
(350, "Acacia Button", "/items/minecraft:acacia_button.png"),
(351, "Amethyst Block", "/items/minecraft:amethyst_block.png"),
(352, "Amethyst Shard", "/items/minecraft:amethyst_shard.png"),
(353, "Stone Stairs", "/items/minecraft:stone_stairs.png"),
(354, "Birch Chest Boat", "/items/minecraft:birch_chest_boat.png"),
(355, "Birch Boat", "/items/minecraft:birch_boat.png"),
(356, "Prismarine Stairs", "/items/minecraft:prismarine_stairs.png"),
(357, "Orange Candle", "/items/minecraft:orange_candle.png"),
(358, "Stripped Acacia Wood", "/items/minecraft:stripped_acacia_wood.png"),
(359, "Stripped Acacia Log", "/items/minecraft:stripped_acacia_log.png"),
(360, "Dried Kelp Block", "/items/minecraft:dried_kelp_block.png"),
(361, "Dried Kelp", "/items/minecraft:dried_kelp.png"),
(362, "Andesite Stairs", "/items/minecraft:andesite_stairs.png"),
(363, "Beetroot Soup", "/items/minecraft:beetroot_soup.png"),
(364, "Beetroot", "/items/minecraft:beetroot.png"),
(365, "Cooked Cod", "/items/minecraft:cooked_cod.png"),
(366, "Orange Glazed Terracotta", "/items/minecraft:orange_glazed_terracotta.png"),
(367, "Bone Meal", "/items/minecraft:bone_meal.png"),
(368, "Bone", "/items/minecraft:bone.png"),
(369, "Netherite Scrap", "/items/minecraft:netherite_scrap.png"),
(370, "Jack O Lantern", "/items/minecraft:jack_o_lantern.png"),
(371, "Carved Pumpkin", "/items/minecraft:carved_pumpkin.png"),
(372, "End Stone Brick Wall", "/items/minecraft:end_stone_brick_wall.png"),
(373, "Cooked Mutton", "/items/minecraft:cooked_mutton.png"),
(374, "Chiseled Quartz Block", "/items/minecraft:chiseled_quartz_block.png"),
(375, "Quartz Slab", "/items/minecraft:quartz_slab.png"),
(376, "Polished Blackstone Brick Wall", "/items/minecraft:polished_blackstone_brick_wall.png"),
(377, "Iron Chestplate", "/items/minecraft:iron_chestplate.png"),
(378, "Cobbled Deepslate", "/items/minecraft:cobbled_deepslate.png"),
(379, "Mangrove Boat", "/items/minecraft:mangrove_boat.png"),
(380, "Cooked Beef", "/items/minecraft:cooked_beef.png"),
(381, "Vine", "/items/minecraft:vine.png"),
(382, "Prismarine", "/items/minecraft:prismarine.png"),
(383, "Writable Book", "/items/minecraft:writable_book.png"),
(384, "Book", "/items/minecraft:book.png"),
(385, "Ink Sac", "/items/minecraft:ink_sac.png"),
(386, "Dispenser", "/items/minecraft:dispenser.png"),
(387, "Bow", "/items/minecraft:bow.png"),
(388, "Green Stained Glass Pane", "/items/minecraft:green_stained_glass_pane.png"),
(389, "Lily Of The Valley", "/items/minecraft:lily_of_the_valley.png"),
(390, "Bamboo Sign", "/items/minecraft:bamboo_sign.png"),
(391, "Chiseled Polished Blackstone", "/items/minecraft:chiseled_polished_blackstone.png"),
(392, "Brick", "/items/minecraft:brick.png"),
(393, "Nether Brick", "/items/minecraft:nether_brick.png"),
(394, "Stone Slab", "/items/minecraft:stone_slab.png"),
(395, "Magenta Dye", "/items/minecraft:magenta_dye.png"),
(396, "Allium", "/items/minecraft:allium.png"),
(397, "Quartz Stairs", "/items/minecraft:quartz_stairs.png"),
(398, "Quartz Block", "/items/minecraft:quartz_block.png"),
(399, "Quartz Pillar", "/items/minecraft:quartz_pillar.png"),
(400, "Nether Brick Wall", "/items/minecraft:nether_brick_wall.png"),
(401, "Oak Boat", "/items/minecraft:oak_boat.png"),
(402, "Acacia Sign", "/items/minecraft:acacia_sign.png"),
(403, "Warped Pressure Plate", "/items/minecraft:warped_pressure_plate.png"),
(404, "Pumpkin Seeds", "/items/minecraft:pumpkin_seeds.png"),
(405, "Pumpkin", "/items/minecraft:pumpkin.png"),
(406, "Sandstone Stairs", "/items/minecraft:sandstone_stairs.png"),
(407, "Cut Sandstone", "/items/minecraft:cut_sandstone.png"),
(408, "Magenta Stained Glass Pane", "/items/minecraft:magenta_stained_glass_pane.png"),
(409, "Clay", "/items/minecraft:clay.png"),
(410, "Clay Ball", "/items/minecraft:clay_ball.png"),
(411, "Ender Pearl", "/items/minecraft:ender_pearl.png"),
(412, "Blaze Powder", "/items/minecraft:blaze_powder.png"),
(413, "Crimson Button", "/items/minecraft:crimson_button.png"),
(414, "Deepslate Tile Wall", "/items/minecraft:deepslate_tile_wall.png"),
(415, "Calibrated Sculk Sensor", "/items/minecraft:calibrated_sculk_sensor.png"),
(416, "Sculk Sensor", "/items/minecraft:sculk_sensor.png"),
(417, "Purple Glazed Terracotta", "/items/minecraft:purple_glazed_terracotta.png"),
(418, "Stripped Mangrove Wood", "/items/minecraft:stripped_mangrove_wood.png"),
(419, "Purple Concrete Powder", "/items/minecraft:purple_concrete_powder.png"),
(420, "Orange Terracotta", "/items/minecraft:orange_terracotta.png"),
(421, "White Tulip", "/items/minecraft:white_tulip.png"),
(422, "Netherite Shovel", "/items/minecraft:netherite_shovel.png"),
(423, "Cyan Stained Glass", "/items/minecraft:cyan_stained_glass.png"),
(424, "Yellow Terracotta", "/items/minecraft:yellow_terracotta.png"),
(425, "Andesite Slab", "/items/minecraft:andesite_slab.png"),
(426, "Blackstone Wall", "/items/minecraft:blackstone_wall.png"),
(427, "Shears", "/items/minecraft:shears.png"),
(428, "Rabbit Stew", "/items/minecraft:rabbit_stew.png"),
(429, "Cooked Rabbit", "/items/minecraft:cooked_rabbit.png"),
(430, "Honeycomb Block", "/items/minecraft:honeycomb_block.png"),
(431, "Black Dye", "/items/minecraft:black_dye.png"),
(432, "Wither Rose", "/items/minecraft:wither_rose.png"),
(433, "Eye Armor Trim Smithing Template", "/items/minecraft:eye_armor_trim_smithing_template.png"),
(434, "End Stone", "/items/minecraft:end_stone.png"),
(435, "Crimson Fence", "/items/minecraft:crimson_fence.png"),
(436, "Stone Brick Wall", "/items/minecraft:stone_brick_wall.png"),
(437, "Yellow Glazed Terracotta", "/items/minecraft:yellow_glazed_terracotta.png"),
(438, "Smoker", "/items/minecraft:smoker.png"),
(439, "Bamboo Trapdoor", "/items/minecraft:bamboo_trapdoor.png"),
(440, "Tnt Minecart", "/items/minecraft:tnt_minecart.png"),
(441, "Tnt", "/items/minecraft:tnt.png"),
(442, "Exposed Cut Copper Stairs", "/items/minecraft:exposed_cut_copper_stairs.png"),
(443, "Cherry Fence Gate", "/items/minecraft:cherry_fence_gate.png"),
(444, "Chiseled Nether Bricks", "/items/minecraft:chiseled_nether_bricks.png"),
(445, "Dandelion", "/items/minecraft:dandelion.png"),
(446, "Heavy Weighted Pressure Plate", "/items/minecraft:heavy_weighted_pressure_plate.png"),
(447, "Netherite Ingot", "/items/minecraft:netherite_ingot.png"),
(448, "White Candle", "/items/minecraft:white_candle.png"),
(449, "Dark Oak Stairs", "/items/minecraft:dark_oak_stairs.png"),
(450, "Cherry Button", "/items/minecraft:cherry_button.png"),
(451, "Netherite Sword", "/items/minecraft:netherite_sword.png"),
(452, "Dark Prismarine Slab", "/items/minecraft:dark_prismarine_slab.png"),
(453, "Spruce Trapdoor", "/items/minecraft:spruce_trapdoor.png"),
(454, "Fire Charge", "/items/minecraft:fire_charge.png"),
(455, "Gunpowder", "/items/minecraft:gunpowder.png"),
(456, "Weathered Cut Copper Slab", "/items/minecraft:weathered_cut_copper_slab.png"),
(457, "Quartz Bricks", "/items/minecraft:quartz_bricks.png"),
(458, "Coast Armor Trim Smithing Template", "/items/minecraft:coast_armor_trim_smithing_template.png"),
(459, "Oak Trapdoor", "/items/minecraft:oak_trapdoor.png"),
(460, "Purple Stained Glass Pane", "/items/minecraft:purple_stained_glass_pane.png"),
(461, "Purple Stained Glass", "/items/minecraft:purple_stained_glass.png"),
(462, "Blaze Rod", "/items/minecraft:blaze_rod.png"),
(463, "Crimson Sign", "/items/minecraft:crimson_sign.png"),
(464, "Barrel", "/items/minecraft:barrel.png"),
(465, "Red Stained Glass", "/items/minecraft:red_stained_glass.png"),
(466, "Polished Blackstone Brick Stairs", "/items/minecraft:polished_blackstone_brick_stairs.png"),
(467, "Mossy Stone Brick Stairs", "/items/minecraft:mossy_stone_brick_stairs.png"),
(468, "Oak Pressure Plate", "/items/minecraft:oak_pressure_plate.png"),
(469, "Gray Stained Glass", "/items/minecraft:gray_stained_glass.png"),
(470, "Polished Deepslate Wall", "/items/minecraft:polished_deepslate_wall.png"),
(471, "Smooth Stone Slab", "/items/minecraft:smooth_stone_slab.png"),
(472, "Warped Trapdoor", "/items/minecraft:warped_trapdoor.png"),
(473, "Sunflower", "/items/minecraft:sunflower.png"),
(474, "Gray Glazed Terracotta", "/items/minecraft:gray_glazed_terracotta.png"),
(475, "Granite Slab", "/items/minecraft:granite_slab.png"),
(476, "Granite", "/items/minecraft:granite.png"),
(477, "Black Glazed Terracotta", "/items/minecraft:black_glazed_terracotta.png"),
(478, "Warped Fungus On A Stick", "/items/minecraft:warped_fungus_on_a_stick.png"),
(479, "Warped Fungus", "/items/minecraft:warped_fungus.png"),
(480, "Polished Deepslate Slab", "/items/minecraft:polished_deepslate_slab.png"),
(481, "Blue Ice", "/items/minecraft:blue_ice.png"),
(482, "Packed Ice", "/items/minecraft:packed_ice.png"),
(483, "Golden Boots", "/items/minecraft:golden_boots.png"),
(484, "Acacia Wood", "/items/minecraft:acacia_wood.png"),
(485, "Acacia Log", "/items/minecraft:acacia_log.png"),
(486, "Red Sand", "/items/minecraft:red_sand.png"),
(487, "Cut Sandstone Slab", "/items/minecraft:cut_sandstone_slab.png"),
(488, "Mossy Cobblestone", "/items/minecraft:mossy_cobblestone.png"),
(489, "Spyglass", "/items/minecraft:spyglass.png"),
(490, "Diamond Block", "/items/minecraft:diamond_block.png"),
(491, "Stripped Oak Wood", "/items/minecraft:stripped_oak_wood.png"),
(492, "Stripped Oak Log", "/items/minecraft:stripped_oak_log.png"),
(493, "End Rod", "/items/minecraft:end_rod.png"),
(494, "Red Nether Brick Slab", "/items/minecraft:red_nether_brick_slab.png"),
(495, "Light Blue Candle", "/items/minecraft:light_blue_candle.png"),
(496, "Golden Leggings", "/items/minecraft:golden_leggings.png"),
(497, "Blue Candle", "/items/minecraft:blue_candle.png"),
(498, "Crimson Hanging Sign", "/items/minecraft:crimson_hanging_sign.png"),
(499, "Stripped Crimson Stem", "/items/minecraft:stripped_crimson_stem.png"),
(500, "Snout Armor Trim Smithing Template", "/items/minecraft:snout_armor_trim_smithing_template.png"),
(501, "Compass", "/items/minecraft:compass.png"),
(502, "Bamboo Button", "/items/minecraft:bamboo_button.png"),
(503, "Brown Candle", "/items/minecraft:brown_candle.png"),
(504, "Red Nether Brick Wall", "/items/minecraft:red_nether_brick_wall.png"),
(505, "Pink Candle", "/items/minecraft:pink_candle.png"),
(506, "Bamboo Hanging Sign", "/items/minecraft:bamboo_hanging_sign.png"),
(507, "Stripped Bamboo Block", "/items/minecraft:stripped_bamboo_block.png"),
(508, "Cherry Hanging Sign", "/items/minecraft:cherry_hanging_sign.png"),
(509, "Stripped Cherry Log", "/items/minecraft:stripped_cherry_log.png"),
(510, "Red Nether Brick Stairs", "/items/minecraft:red_nether_brick_stairs.png"),
(511, "Red Nether Bricks", "/items/minecraft:red_nether_bricks.png"),
(512, "Moss Carpet", "/items/minecraft:moss_carpet.png"),
(513, "Oak Door", "/items/minecraft:oak_door.png"),
(514, "Wooden Sword", "/items/minecraft:wooden_sword.png"),
(515, "Nether Wart Block", "/items/minecraft:nether_wart_block.png"),
(516, "Nether Wart", "/items/minecraft:nether_wart.png"),
(517, "Paper", "/items/minecraft:paper.png"),
(518, "Iron Boots", "/items/minecraft:iron_boots.png"),
(519, "Respawn Anchor", "/items/minecraft:respawn_anchor.png"),
(520, "Crying Obsidian", "/items/minecraft:crying_obsidian.png"),
(521, "Sea Lantern", "/items/minecraft:sea_lantern.png"),
(522, "Prismarine Crystals", "/items/minecraft:prismarine_crystals.png"),
(523, "Prismarine Shard", "/items/minecraft:prismarine_shard.png"),
(524, "Polished Andesite Slab", "/items/minecraft:polished_andesite_slab.png"),
(525, "Pink Petals", "/items/minecraft:pink_petals.png"),
(526, "End Stone Brick Stairs", "/items/minecraft:end_stone_brick_stairs.png"),
(527, "Stripped Birch Wood", "/items/minecraft:stripped_birch_wood.png"),
(528, "Stripped Birch Log", "/items/minecraft:stripped_birch_log.png"),
(529, "Blackstone Slab", "/items/minecraft:blackstone_slab.png"),
(530, "Granite Stairs", "/items/minecraft:granite_stairs.png"),
(531, "Iron Axe", "/items/minecraft:iron_axe.png"),
(532, "Waxed Weathered Copper", "/items/minecraft:waxed_weathered_copper.png"),
(533, "Bookshelf", "/items/minecraft:bookshelf.png"),
(534, "Mangrove Chest Boat", "/items/minecraft:mangrove_chest_boat.png"),
(535, "Birch Sign", "/items/minecraft:birch_sign.png"),
(536, "Diamond Axe", "/items/minecraft:diamond_axe.png"),
(537, "Lodestone", "/items/minecraft:lodestone.png"),
(538, "Cherry Slab", "/items/minecraft:cherry_slab.png"),
(539, "Oak Button", "/items/minecraft:oak_button.png"),
(540, "Mangrove Sign", "/items/minecraft:mangrove_sign.png"),
(541, "Orange Stained Glass", "/items/minecraft:orange_stained_glass.png"),
(542, "Gray Stained Glass Pane", "/items/minecraft:gray_stained_glass_pane.png"),
(543, "Spruce Pressure Plate", "/items/minecraft:spruce_pressure_plate.png"),
(544, "Warped Door", "/items/minecraft:warped_door.png"),
(545, "Cobblestone Stairs", "/items/minecraft:cobblestone_stairs.png"),
(546, "Rose Bush", "/items/minecraft:rose_bush.png"),
(547, "Dark Prismarine", "/items/minecraft:dark_prismarine.png"),
(548, "Red Stained Glass Pane", "/items/minecraft:red_stained_glass_pane.png"),
(549, "Note Block", "/items/minecraft:note_block.png"),
(550, "Iron Bars", "/items/minecraft:iron_bars.png"),
(551, "Turtle Helmet", "/items/minecraft:turtle_helmet.png"),
(552, "Scute", "/items/minecraft:scute.png"),
(553, "Polished Andesite", "/items/minecraft:polished_andesite.png"),
(554, "Netherite Hoe", "/items/minecraft:netherite_hoe.png"),
(555, "Shield", "/items/minecraft:shield.png"),
(556, "Yellow Stained Glass Pane", "/items/minecraft:yellow_stained_glass_pane.png"),
(557, "Yellow Stained Glass", "/items/minecraft:yellow_stained_glass.png"),
(558, "Diamond Hoe", "/items/minecraft:diamond_hoe.png"),
(559, "Brown Stained Glass Pane", "/items/minecraft:brown_stained_glass_pane.png"),
(560, "Scaffolding", "/items/minecraft:scaffolding.png"),
(561, "Jungle Slab", "/items/minecraft:jungle_slab.png"),
(562, "Lever", "/items/minecraft:lever.png"),
(563, "Iron Hoe", "/items/minecraft:iron_hoe.png"),
(564, "Smooth Sandstone Slab", "/items/minecraft:smooth_sandstone_slab.png"),
(565, "Purple Banner", "/items/minecraft:purple_banner.png"),
(566, "Acacia Fence", "/items/minecraft:acacia_fence.png"),
(567, "Dark Oak Boat", "/items/minecraft:dark_oak_boat.png"),
(568, "Bone Block", "/items/minecraft:bone_block.png"),
(569, "Weathered Cut Copper Stairs", "/items/minecraft:weathered_cut_copper_stairs.png"),
(570, "Arrow", "/items/minecraft:arrow.png"),
(571, "Wooden Hoe", "/items/minecraft:wooden_hoe.png"),
(572, "Magenta Stained Glass", "/items/minecraft:magenta_stained_glass.png"),
(573, "Dark Oak Door", "/items/minecraft:dark_oak_door.png"),
(574, "Light Blue Terracotta", "/items/minecraft:light_blue_terracotta.png"),
(575, "Poppy", "/items/minecraft:poppy.png"),
(576, "Prismarine Brick Stairs", "/items/minecraft:prismarine_brick_stairs.png"),
(577, "Waxed Weathered Cut Copper Slab", "/items/minecraft:waxed_weathered_cut_copper_slab.png"),
(578, "Mangrove Wood", "/items/minecraft:mangrove_wood.png"),
(579, "Mangrove Log", "/items/minecraft:mangrove_log.png"),
(580, "Birch Stairs", "/items/minecraft:birch_stairs.png"),
(581, "Birch Wood", "/items/minecraft:birch_wood.png"),
(582, "Birch Log", "/items/minecraft:birch_log.png"),
(583, "Exposed Cut Copper Slab", "/items/minecraft:exposed_cut_copper_slab.png"),
(584, "Light Gray Terracotta", "/items/minecraft:light_gray_terracotta.png"),
(585, "Exposed Cut Copper", "/items/minecraft:exposed_cut_copper.png"),
(586, "Acacia Fence Gate", "/items/minecraft:acacia_fence_gate.png"),
(587, "Shaper Armor Trim Smithing Template", "/items/minecraft:shaper_armor_trim_smithing_template.png"),
(588, "Black Stained Glass Pane", "/items/minecraft:black_stained_glass_pane.png"),
(589, "Dark Prismarine Stairs", "/items/minecraft:dark_prismarine_stairs.png"),
(590, "Raw Iron Block", "/items/minecraft:raw_iron_block.png"),
(591, "Raw Iron", "/items/minecraft:raw_iron.png"),
(592, "Waxed Exposed Cut Copper Stairs", "/items/minecraft:waxed_exposed_cut_copper_stairs.png"),
(593, "Polished Andesite Stairs", "/items/minecraft:polished_andesite_stairs.png"),
(594, "Stone Brick Stairs", "/items/minecraft:stone_brick_stairs.png"),
(595, "Smooth Quartz Stairs", "/items/minecraft:smooth_quartz_stairs.png"),
(596, "Green Stained Glass", "/items/minecraft:green_stained_glass.png"),
(597, "Crimson Hyphae", "/items/minecraft:crimson_hyphae.png"),
(598, "Crimson Stem", "/items/minecraft:crimson_stem.png"),
(599, "Bamboo Door", "/items/minecraft:bamboo_door.png"),
(600, "Chiseled Deepslate", "/items/minecraft:chiseled_deepslate.png"),
(601, "Gold Block", "/items/minecraft:gold_block.png"),
(602, "Cut Copper Slab", "/items/minecraft:cut_copper_slab.png"),
(603, "Polished Diorite Slab", "/items/minecraft:polished_diorite_slab.png"),
(604, "Orange Banner", "/items/minecraft:orange_banner.png"),
(605, "Acacia Hanging Sign", "/items/minecraft:acacia_hanging_sign.png"),
(606, "Netherite Upgrade Smithing Template", "/items/minecraft:netherite_upgrade_smithing_template.png"),
(607, "Netherrack", "/items/minecraft:netherrack.png"),
(608, "Wooden Axe", "/items/minecraft:wooden_axe.png"),
(609, "Green Glazed Terracotta", "/items/minecraft:green_glazed_terracotta.png"),
(610, "Magenta Terracotta", "/items/minecraft:magenta_terracotta.png"),
(611, "Gray Candle", "/items/minecraft:gray_candle.png"),
(612, "Spruce Door", "/items/minecraft:spruce_door.png"),
(613, "Red Banner", "/items/minecraft:red_banner.png"),
(614, "Smithing Table", "/items/minecraft:smithing_table.png"),
(615, "Wooden Shovel", "/items/minecraft:wooden_shovel.png"),
(616, "Acacia Slab", "/items/minecraft:acacia_slab.png"),
(617, "Blast Furnace", "/items/minecraft:blast_furnace.png"),
(618, "Smooth Stone", "/items/minecraft:smooth_stone.png"),
(619, "Stone Hoe", "/items/minecraft:stone_hoe.png"),
(620, "Bamboo Fence", "/items/minecraft:bamboo_fence.png"),
(621, "Wooden Pickaxe", "/items/minecraft:wooden_pickaxe.png"),
(622, "Stone Button", "/items/minecraft:stone_button.png"),
(623, "Light Gray Candle", "/items/minecraft:light_gray_candle.png"),
(624, "Birch Button", "/items/minecraft:birch_button.png"),
(625, "Diamond Shovel", "/items/minecraft:diamond_shovel.png"),
(626, "Stone Pickaxe", "/items/minecraft:stone_pickaxe.png"),
(627, "Lime Stained Glass Pane", "/items/minecraft:lime_stained_glass_pane.png"),
(628, "Lime Stained Glass", "/items/minecraft:lime_stained_glass.png"),
(629, "Mangrove Fence", "/items/minecraft:mangrove_fence.png"),
(630, "Decorated Pot", "/items/minecraft:decorated_pot.png"),
(631, "Golden Pickaxe", "/items/minecraft:golden_pickaxe.png"),
(632, "Golden Helmet", "/items/minecraft:golden_helmet.png"),
(633, "Bamboo Fence Gate", "/items/minecraft:bamboo_fence_gate.png"),
(634, "Bamboo Mosaic Slab", "/items/minecraft:bamboo_mosaic_slab.png"),
(635, "Cherry Trapdoor", "/items/minecraft:cherry_trapdoor.png"),
(636, "Lightning Rod", "/items/minecraft:lightning_rod.png"),
(637, "Netherite Chestplate", "/items/minecraft:netherite_chestplate.png"),
(638, "Creeper Banner Pattern", "/items/minecraft:creeper_banner_pattern.png"),
(639, "Creeper Head", "/items/minecraft:creeper_head.png"),
(640, "Deepslate", "/items/minecraft:deepslate.png"),
(641, "Loom", "/items/minecraft:loom.png"),
(642, "Cherry Pressure Plate", "/items/minecraft:cherry_pressure_plate.png"),
(643, "Jukebox", "/items/minecraft:jukebox.png"),
(644, "Lead", "/items/minecraft:lead.png"),
(645, "Brick Stairs", "/items/minecraft:brick_stairs.png"),
(646, "Magenta Banner", "/items/minecraft:magenta_banner.png"),
(647, "Magma Block", "/items/minecraft:magma_block.png"),
(648, "Magma Cream", "/items/minecraft:magma_cream.png"),
(649, "Oak Fence", "/items/minecraft:oak_fence.png"),
(650, "Jungle Trapdoor", "/items/minecraft:jungle_trapdoor.png"),
(651, "Composter", "/items/minecraft:composter.png"),
(652, "Lime Candle", "/items/minecraft:lime_candle.png"),
(653, "Stone Axe", "/items/minecraft:stone_axe.png"),
(654, "Dark Oak Fence", "/items/minecraft:dark_oak_fence.png"),
(655, "Warped Fence Gate", "/items/minecraft:warped_fence_gate.png"),
(656, "Cartography Table", "/items/minecraft:cartography_table.png"),
(657, "Grindstone", "/items/minecraft:grindstone.png"),
(658, "Peony", "/items/minecraft:peony.png"),
(659, "Deepslate Tiles", "/items/minecraft:deepslate_tiles.png"),
(660, "Flint And Steel", "/items/minecraft:flint_and_steel.png"),
(661, "Mud Brick Stairs", "/items/minecraft:mud_brick_stairs.png"),
(662, "Mud Bricks", "/items/minecraft:mud_bricks.png"),
(663, "Ladder", "/items/minecraft:ladder.png"),
(664, "Crimson Slab", "/items/minecraft:crimson_slab.png"),
(665, "Cyan Stained Glass Pane", "/items/minecraft:cyan_stained_glass_pane.png"),
(666, "Crimson Trapdoor", "/items/minecraft:crimson_trapdoor.png"),
(667, "Light Blue Concrete Powder", "/items/minecraft:light_blue_concrete_powder.png"),
(668, "Prismarine Bricks", "/items/minecraft:prismarine_bricks.png"),
(669, "Painting", "/items/minecraft:painting.png"),
(670, "Oak Stairs", "/items/minecraft:oak_stairs.png"),
(671, "Golden Sword", "/items/minecraft:golden_sword.png"),
(672, "Pink Glazed Terracotta", "/items/minecraft:pink_glazed_terracotta.png"),
(673, "Pumpkin Pie", "/items/minecraft:pumpkin_pie.png"),
(674, "Egg", "/items/minecraft:egg.png"),
(675, "Netherite Block", "/items/minecraft:netherite_block.png"),
(676, "Netherite Helmet", "/items/minecraft:netherite_helmet.png"),
(677, "Dripstone Block", "/items/minecraft:dripstone_block.png"),
(678, "Pointed Dripstone", "/items/minecraft:pointed_dripstone.png"),
(679, "Chest Minecart", "/items/minecraft:chest_minecart.png"),
(680, "Pink Concrete Powder", "/items/minecraft:pink_concrete_powder.png"),
(681, "Polished Basalt", "/items/minecraft:polished_basalt.png"),
(682, "Basalt", "/items/minecraft:basalt.png"),
(683, "Crafting Table", "/items/minecraft:crafting_table.png"),
(684, "Bamboo Chest Raft", "/items/minecraft:bamboo_chest_raft.png"),
(685, "Bamboo Raft", "/items/minecraft:bamboo_raft.png"),
(686, "Netherite Axe", "/items/minecraft:netherite_axe.png"),
(687, "Jungle Fence", "/items/minecraft:jungle_fence.png"),
(688, "Prismarine Slab", "/items/minecraft:prismarine_slab.png"),
(689, "Spruce Hanging Sign", "/items/minecraft:spruce_hanging_sign.png"),
(690, "Stripped Spruce Log", "/items/minecraft:stripped_spruce_log.png"),
(691, "Black Banner", "/items/minecraft:black_banner.png"),
(692, "Chiseled Bookshelf", "/items/minecraft:chiseled_bookshelf.png"),
(693, "Mud Brick Slab", "/items/minecraft:mud_brick_slab.png"),
(694, "Dark Oak Pressure Plate", "/items/minecraft:dark_oak_pressure_plate.png"),
(695, "Birch Fence Gate", "/items/minecraft:birch_fence_gate.png"),
(696, "Spire Armor Trim Smithing Template", "/items/minecraft:spire_armor_trim_smithing_template.png"),
(697, "Polished Diorite", "/items/minecraft:polished_diorite.png"),
(698, "Raw Copper Block", "/items/minecraft:raw_copper_block.png"),
(699, "Raw Copper", "/items/minecraft:raw_copper.png"),
(700, "Nether Brick Stairs", "/items/minecraft:nether_brick_stairs.png"),
(701, "Yellow Banner", "/items/minecraft:yellow_banner.png"),
(702, "Diorite Wall", "/items/minecraft:diorite_wall.png"),
(703, "Enchanting Table", "/items/minecraft:enchanting_table.png"),
(704, "Spruce Boat", "/items/minecraft:spruce_boat.png"),
(705, "Dark Oak Chest Boat", "/items/minecraft:dark_oak_chest_boat.png"),
(706, "Orange Concrete Powder", "/items/minecraft:orange_concrete_powder.png"),
(707, "Spruce Chest Boat", "/items/minecraft:spruce_chest_boat.png"),
(708, "Cyan Banner", "/items/minecraft:cyan_banner.png"),
(709, "Raiser Armor Trim Smithing Template", "/items/minecraft:raiser_armor_trim_smithing_template.png"),
(710, "Pink Stained Glass Pane", "/items/minecraft:pink_stained_glass_pane.png"),
(711, "Crossbow", "/items/minecraft:crossbow.png"),
(712, "Golden Chestplate", "/items/minecraft:golden_chestplate.png"),
(713, "Iron Sword", "/items/minecraft:iron_sword.png"),
(714, "Flower Pot", "/items/minecraft:flower_pot.png"),
(715, "Birch Slab", "/items/minecraft:birch_slab.png"),
(716, "Rabbit Hide", "/items/minecraft:rabbit_hide.png"),
(717, "Purple Terracotta", "/items/minecraft:purple_terracotta.png"),
(718, "Iron Leggings", "/items/minecraft:iron_leggings.png"),
(719, "Cracked Polished Blackstone Bricks", "/items/minecraft:cracked_polished_blackstone_bricks.png"),
(720, "Gray Concrete Powder", "/items/minecraft:gray_concrete_powder.png"),
(721, "Activator Rail", "/items/minecraft:activator_rail.png"),
(722, "Rib Armor Trim Smithing Template", "/items/minecraft:rib_armor_trim_smithing_template.png"),
(723, "Mangrove Slab", "/items/minecraft:mangrove_slab.png"),
(724, "Cherry Sign", "/items/minecraft:cherry_sign.png"),
(725, "Cracked Deepslate Tiles", "/items/minecraft:cracked_deepslate_tiles.png"),
(726, "Oak Chest Boat", "/items/minecraft:oak_chest_boat.png"),
(727, "Crimson Fence Gate", "/items/minecraft:crimson_fence_gate.png"),
(728, "Ward Armor Trim Smithing Template", "/items/minecraft:ward_armor_trim_smithing_template.png"),
(729, "Firework Rocket", "/items/minecraft:firework_rocket.png"),
(730, "Soul Campfire", "/items/minecraft:soul_campfire.png"),
(731, "Diamond Pickaxe", "/items/minecraft:diamond_pickaxe.png"),
(732, "Netherite Pickaxe", "/items/minecraft:netherite_pickaxe.png"),
(733, "Cut Red Sandstone Slab", "/items/minecraft:cut_red_sandstone_slab.png"),
(734, "Bamboo Stairs", "/items/minecraft:bamboo_stairs.png"),
(735, "Jungle Hanging Sign", "/items/minecraft:jungle_hanging_sign.png"),
(736, "Stripped Jungle Log", "/items/minecraft:stripped_jungle_log.png"),
(737, "Prismarine Brick Slab", "/items/minecraft:prismarine_brick_slab.png"),
(738, "Jungle Sign", "/items/minecraft:jungle_sign.png"),
(739, "Jungle Chest Boat", "/items/minecraft:jungle_chest_boat.png"),
(740, "Jungle Boat", "/items/minecraft:jungle_boat.png"),
(741, "Melon Seeds", "/items/minecraft:melon_seeds.png"),
(742, "Glistering Melon Slice", "/items/minecraft:glistering_melon_slice.png"),
(743, "Vex Armor Trim Smithing Template", "/items/minecraft:vex_armor_trim_smithing_template.png"),
(744, "Crimson Stairs", "/items/minecraft:crimson_stairs.png"),
(745, "Lime Concrete Powder", "/items/minecraft:lime_concrete_powder.png"),
(746, "Cherry Wood", "/items/minecraft:cherry_wood.png"),
(747, "Cherry Log", "/items/minecraft:cherry_log.png"),
(748, "Pink Tulip", "/items/minecraft:pink_tulip.png"),
(749, "Light Blue Stained Glass", "/items/minecraft:light_blue_stained_glass.png"),
(750, "White Stained Glass Pane", "/items/minecraft:white_stained_glass_pane.png"),
(751, "Prismarine Wall", "/items/minecraft:prismarine_wall.png"),
(752, "Stripped Spruce Wood", "/items/minecraft:stripped_spruce_wood.png"),
(753, "Snow", "/items/minecraft:snow.png"),
(754, "Snow Block", "/items/minecraft:snow_block.png"),
(755, "Cake", "/items/minecraft:cake.png"),
(756, "Milk Bucket", "/items/minecraft:milk_bucket.png"),
(757, "Green Candle", "/items/minecraft:green_candle.png"),
(758, "Mangrove Pressure Plate", "/items/minecraft:mangrove_pressure_plate.png"),
(759, "Iron Shovel", "/items/minecraft:iron_shovel.png"),
(760, "Birch Fence", "/items/minecraft:birch_fence.png"),
(761, "Red Concrete Powder", "/items/minecraft:red_concrete_powder.png"),
(762, "Fermented Spider Eye", "/items/minecraft:fermented_spider_eye.png"),
(763, "Spider Eye", "/items/minecraft:spider_eye.png"),
(764, "Jungle Wood", "/items/minecraft:jungle_wood.png"),
(765, "Jungle Log", "/items/minecraft:jungle_log.png"),
(766, "Blue Glazed Terracotta", "/items/minecraft:blue_glazed_terracotta.png"),
(767, "Dark Oak Button", "/items/minecraft:dark_oak_button.png"),
(768, "Smooth Red Sandstone Stairs", "/items/minecraft:smooth_red_sandstone_stairs.png"),
(769, "Mud Brick Wall", "/items/minecraft:mud_brick_wall.png"),
(770, "Cherry Stairs", "/items/minecraft:cherry_stairs.png"),
(771, "Wild Armor Trim Smithing Template", "/items/minecraft:wild_armor_trim_smithing_template.png"),
(772, "Leather Leggings", "/items/minecraft:leather_leggings.png"),
(773, "Lilac", "/items/minecraft:lilac.png"),
(774, "Spruce Sign", "/items/minecraft:spruce_sign.png"),
(775, "Beacon", "/items/minecraft:beacon.png"),
(776, "Nether Star", "/items/minecraft:nether_star.png"),
(777, "Brewing Stand", "/items/minecraft:brewing_stand.png"),
(778, "Magenta Candle", "/items/minecraft:magenta_candle.png"),
(779, "Mangrove Stairs", "/items/minecraft:mangrove_stairs.png"),
(780, "Mossy Stone Brick Slab", "/items/minecraft:mossy_stone_brick_slab.png"),
(781, "Acacia Stairs", "/items/minecraft:acacia_stairs.png"),
(782, "Bread", "/items/minecraft:bread.png"),
(783, "White Glazed Terracotta", "/items/minecraft:white_glazed_terracotta.png"),
(784, "Snowball", "/items/minecraft:snowball.png"),
(785, "Pitcher Plant", "/items/minecraft:pitcher_plant.png"),
(786, "Light Blue Glazed Terracotta", "/items/minecraft:light_blue_glazed_terracotta.png"),
(787, "Mossy Stone Brick Wall", "/items/minecraft:mossy_stone_brick_wall.png"),
(788, "Lime Banner", "/items/minecraft:lime_banner.png"),
(789, "Raw Gold", "/items/minecraft:raw_gold.png"),
(790, "Raw Gold Block", "/items/minecraft:raw_gold_block.png"),
(791, "Light Gray Banner", "/items/minecraft:light_gray_banner.png"),
(792, "Netherite Leggings", "/items/minecraft:netherite_leggings.png"),
(793, "Warped Hanging Sign", "/items/minecraft:warped_hanging_sign.png"),
(794, "Purpur Stairs", "/items/minecraft:purpur_stairs.png"),
(795, "Coal Block", "/items/minecraft:coal_block.png"),
(796, "Red Candle", "/items/minecraft:red_candle.png"),
(797, "Gray Banner", "/items/minecraft:gray_banner.png"),
(798, "Iron Helmet", "/items/minecraft:iron_helmet.png"),
(799, "Lectern", "/items/minecraft:lectern.png"),
(800, "Cornflower", "/items/minecraft:cornflower.png"),
(801, "Mangrove Fence Gate", "/items/minecraft:mangrove_fence_gate.png"),
(802, "Light Blue Stained Glass Pane", "/items/minecraft:light_blue_stained_glass_pane.png"),
(803, "Carrot On A Stick", "/items/minecraft:carrot_on_a_stick.png"),
(804, "Blue Concrete Powder", "/items/minecraft:blue_concrete_powder.png"),
(805, "Iron Pickaxe", "/items/minecraft:iron_pickaxe.png"),
(806, "Skull Banner Pattern", "/items/minecraft:skull_banner_pattern.png"),
(807, "Wither Skeleton Skull", "/items/minecraft:wither_skeleton_skull.png"),
(808, "Mojang Banner Pattern", "/items/minecraft:mojang_banner_pattern.png"),
(809, "Enchanted Golden Apple", "/items/minecraft:enchanted_golden_apple.png"),
(810, "Tinted Glass", "/items/minecraft:tinted_glass.png"),
(811, "Red Tulip", "/items/minecraft:red_tulip.png"),
(812, "Spectral Arrow", "/items/minecraft:spectral_arrow.png"),
(813, "Glowstone Dust", "/items/minecraft:glowstone_dust.png"),
(814, "Mangrove Trapdoor", "/items/minecraft:mangrove_trapdoor.png"),
(815, "Stripped Cherry Wood", "/items/minecraft:stripped_cherry_wood.png"),
(816, "Netherite Boots", "/items/minecraft:netherite_boots.png"),
(817, "Birch Hanging Sign", "/items/minecraft:birch_hanging_sign.png"),
(818, "Black Candle", "/items/minecraft:black_candle.png"),
(819, "Silence Armor Trim Smithing Template", "/items/minecraft:silence_armor_trim_smithing_template.png"),
(820, "Green Concrete Powder", "/items/minecraft:green_concrete_powder.png"),
(821, "Birch Trapdoor", "/items/minecraft:birch_trapdoor.png"),
(822, "Leather Horse Armor", "/items/minecraft:leather_horse_armor.png"),
(823, "Spruce Wood", "/items/minecraft:spruce_wood.png"),
(824, "Spruce Log", "/items/minecraft:spruce_log.png"),
(825, "Detector Rail", "/items/minecraft:detector_rail.png"),
(826, "Yellow Candle", "/items/minecraft:yellow_candle.png"),
(827, "Acacia Chest Boat", "/items/minecraft:acacia_chest_boat.png"),
(828, "Stonecutter", "/items/minecraft:stonecutter.png"),
(829, "Cyan Terracotta", "/items/minecraft:cyan_terracotta.png"),
(830, "Lime Terracotta", "/items/minecraft:lime_terracotta.png"),
(831, "Golden Apple", "/items/minecraft:golden_apple.png"),
(832, "Apple", "/items/minecraft:apple.png"),
(833, "Iron Trapdoor", "/items/minecraft:iron_trapdoor.png"),
(834, "White Stained Glass", "/items/minecraft:white_stained_glass.png"),
(835, "Daylight Detector", "/items/minecraft:daylight_detector.png"),
(836, "Rail", "/items/minecraft:rail.png"),
(837, "Stripped Jungle Wood", "/items/minecraft:stripped_jungle_wood.png"),
(838, "Flower Banner Pattern", "/items/minecraft:flower_banner_pattern.png"),
(839, "Diamond Boots", "/items/minecraft:diamond_boots.png"),
(840, "Warped Stairs", "/items/minecraft:warped_stairs.png"),
(841, "Cracked Stone Bricks", "/items/minecraft:cracked_stone_bricks.png"),
(842, "Oak Slab", "/items/minecraft:oak_slab.png"),
(843, "Leather Boots", "/items/minecraft:leather_boots.png"),
(844, "Stripped Crimson Hyphae", "/items/minecraft:stripped_crimson_hyphae.png"),
(845, "Cherry Door", "/items/minecraft:cherry_door.png"),
(846, "Cherry Chest Boat", "/items/minecraft:cherry_chest_boat.png"),
(847, "Cherry Boat", "/items/minecraft:cherry_boat.png"),
(848, "White Concrete Powder", "/items/minecraft:white_concrete_powder.png"),
(849, "Anvil", "/items/minecraft:anvil.png"),
(850, "Warped Slab", "/items/minecraft:warped_slab.png"),
(851, "Host Armor Trim Smithing Template", "/items/minecraft:host_armor_trim_smithing_template.png"),
(852, "Oak Hanging Sign", "/items/minecraft:oak_hanging_sign.png"),
(853, "Light Gray Concrete Powder", "/items/minecraft:light_gray_concrete_powder.png"),
(854, "Map", "/items/minecraft:map.png"),
(855, "Sponge", "/items/minecraft:sponge.png"),
(856, "Orange Tulip", "/items/minecraft:orange_tulip.png"),
(857, "Cyan Candle", "/items/minecraft:cyan_candle.png"),
(858, "Jungle Door", "/items/minecraft:jungle_door.png"),
(859, "Conduit", "/items/minecraft:conduit.png"),
(860, "Nautilus Shell", "/items/minecraft:nautilus_shell.png"),
(861, "Heart Of The Sea", "/items/minecraft:heart_of_the_sea.png"),
(862, "Muddy Mangrove Roots", "/items/minecraft:muddy_mangrove_roots.png"),
(863, "Mangrove Roots", "/items/minecraft:mangrove_roots.png"),
(864, "Iron Door", "/items/minecraft:iron_door.png"),
(865, "Armor Stand", "/items/minecraft:armor_stand.png"),
(866, "Magenta Concrete Powder", "/items/minecraft:magenta_concrete_powder.png"),
(867, "Diamond Leggings", "/items/minecraft:diamond_leggings.png"),
(868, "Lime Glazed Terracotta", "/items/minecraft:lime_glazed_terracotta.png"),
(869, "Dark Oak Slab", "/items/minecraft:dark_oak_slab.png"),
(870, "Acacia Trapdoor", "/items/minecraft:acacia_trapdoor.png"),
(871, "Golden Hoe", "/items/minecraft:golden_hoe.png"),
(872, "Diamond Helmet", "/items/minecraft:diamond_helmet.png"),
(873, "Green Banner", "/items/minecraft:green_banner.png"),
(874, "Jungle Pressure Plate", "/items/minecraft:jungle_pressure_plate.png"),
(875, "Black Stained Glass", "/items/minecraft:black_stained_glass.png"),
(876, "Golden Shovel", "/items/minecraft:golden_shovel.png"),
(877, "Azure Bluet", "/items/minecraft:azure_bluet.png"),
(878, "Nether Brick Fence", "/items/minecraft:nether_brick_fence.png"),
(879, "Repeater", "/items/minecraft:repeater.png"),
(880, "Tide Armor Trim Smithing Template", "/items/minecraft:tide_armor_trim_smithing_template.png"),
(881, "Ice", "/items/minecraft:ice.png"),
(882, "Black Concrete Powder", "/items/minecraft:black_concrete_powder.png"),
(883, "Cyan Glazed Terracotta", "/items/minecraft:cyan_glazed_terracotta.png"),
(884, "Polished Blackstone Pressure Plate", "/items/minecraft:polished_blackstone_pressure_plate.png"),
(885, "Black Terracotta", "/items/minecraft:black_terracotta.png"),
(886, "Jungle Button", "/items/minecraft:jungle_button.png"),
(887, "Spruce Button", "/items/minecraft:spruce_button.png"),
(888, "Golden Axe", "/items/minecraft:golden_axe.png"),
(889, "Polished Blackstone Button", "/items/minecraft:polished_blackstone_button.png"),
(890, "Recovery Compass", "/items/minecraft:recovery_compass.png"),
(891, "Echo Shard", "/items/minecraft:echo_shard.png");
