INSERT INTO mob (id, name, image, hp, player_relation) VALUES
(1, "Bat", "/mobs/minecraft:bat.png", 20, 0),
(2, "Pig", "/mobs/minecraft:pig.png", 20, 0),
(3, "Rabbit", "/mobs/minecraft:rabbit.png", 20, 0),
(4, "Sheep", "/mobs/minecraft:sheep.png", 20, 0),
(5, "Spider", "/mobs/minecraft:spider.png", 20, 2),
(6, "Zombie", "/mobs/minecraft:zombie.png", 20, 2),
(7, "Zombie Villager", "/mobs/minecraft:zombie_villager.png", 20, 2),
(8, "Skeleton", "/mobs/minecraft:skeleton.png", 20, 2),
(9, "Creeper", "/mobs/minecraft:creeper.png", 20, 2),
(10, "Slime", "/mobs/minecraft:slime.png", 20, 2),
(11, "Enderman", "/mobs/minecraft:enderman.png", 20, 2),
(12, "Witch", "/mobs/minecraft:witch.png", 20, 2),
(13, "Glow Squid", "/mobs/minecraft:glow_squid.png", 20, 0),
(14, "Chicken", "/mobs/minecraft:chicken.png", 20, 0),
(15, "Cow", "/mobs/minecraft:cow.png", 20, 0),
(16, "Horse", "/mobs/minecraft:horse.png", 20, 0),
(17, "Donkey", "/mobs/minecraft:donkey.png", 20, 0),
(18, "Llama", "/mobs/minecraft:llama.png", 20, 0),
(19, "Polar Bear", "/mobs/minecraft:polar_bear.png", 20, 0),
(20, "Stray", "/mobs/minecraft:stray.png", 20, 2),
(21, "Drowned", "/mobs/minecraft:drowned.png", 20, 2),
(22, "Cod", "/mobs/minecraft:cod.png", 20, 0),
(23, "Salmon", "/mobs/minecraft:salmon.png", 20, 0),
(24, "Squid", "/mobs/minecraft:squid.png", 20, 0),
(25, "Wolf", "/mobs/minecraft:wolf.png", 20, 0),
(26, "Parrot", "/mobs/minecraft:parrot.png", 20, 0),
(27, "Panda", "/mobs/minecraft:panda.png", 20, 0),
(28, "Ocelot", "/mobs/minecraft:ocelot.png", 20, 2),
(29, "Pufferfish", "/mobs/minecraft:pufferfish.png", 20, 0),
(30, "Tropical Fish", "/mobs/minecraft:tropical_fish.png", 20, 0),
(31, "Dolphin", "/mobs/minecraft:dolphin.png", 20, 0),
(32, "Mooshroom", "/mobs/minecraft:mooshroom.png", 20, 0),
(33, "Goat", "/mobs/minecraft:goat.png", 20, 0),
(34, "Frog", "/mobs/minecraft:frog.png", 20, 0),
(35, "Fox", "/mobs/minecraft:fox.png", 20, 0),
(36, "Strider", "/mobs/minecraft:strider.png", 20, 0),
(37, "Ghast", "/mobs/minecraft:ghast.png", 20, 2),
(38, "Zombified Piglin", "/mobs/minecraft:zombified_piglin.png", 20, 2),
(39, "Magma Cube", "/mobs/minecraft:magma_cube.png", 20, 2),
(40, "Piglin", "/mobs/minecraft:piglin.png", 20, 2),
(41, "Turtle", "/mobs/minecraft:turtle.png", 20, 0),
(42, "Hoglin", "/mobs/minecraft:hoglin.png", 20, 2),
(43, "Husk", "/mobs/minecraft:husk.png", 20, 2),
(44, "Axolotl", "/mobs/minecraft:axolotl.png", 20, 0),
(45, "Cat", "/mobs/minecraft:cat.png", 20, 0),
(46, "Pillager", "/mobs/minecraft:pillager.png", 20, 2),
(47, "Guardian", "/mobs/minecraft:guardian.png", 20, 2),
(48, "Blaze", "/mobs/minecraft:blaze.png", 20, 2),
(49, "Wither Skeleton", "/mobs/minecraft:wither_skeleton.png", 20, 2);
