INSERT INTO mob (id, name, image, hp, player_relation) VALUES
(1, 'Bat', '/mobs/minecraft_bat.png', 20, 0),
(2, 'Pig', '/mobs/minecraft_pig.png', 20, 0),
(3, 'Rabbit', '/mobs/minecraft_rabbit.png', 20, 0),
(4, 'Sheep', '/mobs/minecraft_sheep.png', 20, 0),
(5, 'Spider', '/mobs/minecraft_spider.png', 20, 2),
(6, 'Zombie', '/mobs/minecraft_zombie.png', 20, 2),
(7, 'Zombie Villager', '/mobs/minecraft_zombie_villager.png', 20, 2),
(8, 'Skeleton', '/mobs/minecraft_skeleton.png', 20, 2),
(9, 'Creeper', '/mobs/minecraft_creeper.png', 20, 2),
(10, 'Slime', '/mobs/minecraft_slime.png', 20, 2),
(11, 'Enderman', '/mobs/minecraft_enderman.png', 20, 2),
(12, 'Witch', '/mobs/minecraft_witch.png', 20, 2),
(13, 'Glow Squid', '/mobs/minecraft_glow_squid.png', 20, 0),
(14, 'Chicken', '/mobs/minecraft_chicken.png', 20, 0),
(15, 'Cow', '/mobs/minecraft_cow.png', 20, 0),
(16, 'Horse', '/mobs/minecraft_horse.png', 20, 0),
(17, 'Donkey', '/mobs/minecraft_donkey.png', 20, 0),
(18, 'Llama', '/mobs/minecraft_llama.png', 20, 0),
(19, 'Polar Bear', '/mobs/minecraft_polar_bear.png', 20, 0),
(20, 'Stray', '/mobs/minecraft_stray.png', 20, 2),
(21, 'Drowned', '/mobs/minecraft_drowned.png', 20, 2),
(22, 'Cod', '/mobs/minecraft_cod.png', 20, 0),
(23, 'Salmon', '/mobs/minecraft_salmon.png', 20, 0),
(24, 'Squid', '/mobs/minecraft_squid.png', 20, 0),
(25, 'Wolf', '/mobs/minecraft_wolf.png', 20, 0),
(26, 'Parrot', '/mobs/minecraft_parrot.png', 20, 0),
(27, 'Panda', '/mobs/minecraft_panda.png', 20, 0),
(28, 'Ocelot', '/mobs/minecraft_ocelot.png', 20, 2),
(29, 'Pufferfish', '/mobs/minecraft_pufferfish.png', 20, 0),
(30, 'Tropical Fish', '/mobs/minecraft_tropical_fish.png', 20, 0),
(31, 'Dolphin', '/mobs/minecraft_dolphin.png', 20, 0),
(32, 'Mooshroom', '/mobs/minecraft_mooshroom.png', 20, 0),
(33, 'Goat', '/mobs/minecraft_goat.png', 20, 0),
(34, 'Frog', '/mobs/minecraft_frog.png', 20, 0),
(35, 'Fox', '/mobs/minecraft_fox.png', 20, 0),
(36, 'Strider', '/mobs/minecraft_strider.png', 20, 0),
(37, 'Ghast', '/mobs/minecraft_ghast.png', 20, 2),
(38, 'Zombified Piglin', '/mobs/minecraft_zombified_piglin.png', 20, 2),
(39, 'Magma Cube', '/mobs/minecraft_magma_cube.png', 20, 2),
(40, 'Piglin', '/mobs/minecraft_piglin.png', 20, 2),
(41, 'Turtle', '/mobs/minecraft_turtle.png', 20, 0),
(42, 'Hoglin', '/mobs/minecraft_hoglin.png', 20, 2),
(43, 'Husk', '/mobs/minecraft_husk.png', 20, 2),
(44, 'Axolotl', '/mobs/minecraft_axolotl.png', 20, 0),
(45, 'Cat', '/mobs/minecraft_cat.png', 20, 0),
(46, 'Pillager', '/mobs/minecraft_pillager.png', 20, 2),
(47, 'Guardian', '/mobs/minecraft_guardian.png', 20, 2),
(48, 'Blaze', '/mobs/minecraft_blaze.png', 20, 2),
(49, 'Wither Skeleton', '/mobs/minecraft_wither_skeleton.png', 20, 2),
(50, 'Vindicator', '/mobs/minecraft_vindicator.png', 20, 0),
(51, 'Ender Dragon', '/mobs/minecraft_ender_dragon.png', 20, 0),
(52, 'Elder Guardian', '/mobs/minecraft_elder_guardian.png', 20, 0),
(53, 'Wither', '/mobs/minecraft_wither.png', 20, 0),
(54, 'Villager', '/mobs/minecraft_villager.png', 20, 0),
(55, 'Trader Llama', '/mobs/minecraft_trader_llama.png', 20, 0),
(56, 'Cave Spider', '/mobs/minecraft_cave_spider.png', 20, 0),
(57, 'Zombie Horse', '/mobs/minecraft_zombie_horse.png', 20, 0),
(58, 'Ravager', '/mobs/minecraft_ravager.png', 20, 0),
(59, 'Sniffer', '/mobs/minecraft_sniffer.png', 20, 0),
(60, 'Shulker', '/mobs/minecraft_shulker.png', 20, 0),
(61, 'Mule', '/mobs/minecraft_mule.png', 20, 0),
(62, 'Tadpole', '/mobs/minecraft_tadpole.png', 20, 0),
(63, 'Player', '/mobs/minecraft_player.png', 20, 0),
(64, 'Evoker', '/mobs/minecraft_evoker.png', 20, 0),
(65, 'Piglin Brute', '/mobs/minecraft_piglin_brute.png', 20, 0),
(66, 'Allay', '/mobs/minecraft_allay.png', 20, 0),
(67, 'Bee', '/mobs/minecraft_bee.png', 20, 0),
(68, 'Endermite', '/mobs/minecraft_endermite.png', 20, 0),
(69, 'Snow Golem', '/mobs/minecraft_snow_golem.png', 20, 0),
(70, 'Wandering Trader', '/mobs/minecraft_wandering_trader.png', 20, 0),
(71, 'Warden', '/mobs/minecraft_warden.png', 20, 0),
(72, 'Camel', '/mobs/minecraft_camel.png', 20, 0),
(73, 'Iron Golem', '/mobs/minecraft_iron_golem.png', 20, 0),
(74, 'Phantom', '/mobs/minecraft_phantom.png', 20, 0),
(75, 'Silverfish', '/mobs/minecraft_silverfish.png', 20, 0),
(76, 'Skeleton Horse', '/mobs/minecraft_skeleton_horse.png', 20, 0),
(77, 'Giant', '/mobs/minecraft_giant.png', 20, 0),
(78, 'Armor Stand', '/mobs/minecraft_armor_stand.png', 20, 0),
(79, 'Zoglin', '/mobs/minecraft_zoglin.png', 20, 0),
(80, 'Vex', '/mobs/minecraft_vex.png', 20, 0),
(81, 'Illusioner', '/mobs/minecraft_illusioner.png', 20, 0);
