INSERT INTO mob (id, name, image, hp, player_relation) VALUES
(1, 'Bat', '/mobs/minecraft:bat.png', 20, 0),
(2, 'Pig', '/mobs/minecraft:pig.png', 20, 0),
(3, 'Rabbit', '/mobs/minecraft:rabbit.png', 20, 0),
(4, 'Sheep', '/mobs/minecraft:sheep.png', 20, 0),
(5, 'Spider', '/mobs/minecraft:spider.png', 20, 2),
(6, 'Zombie', '/mobs/minecraft:zombie.png', 20, 2),
(7, 'Zombie Villager', '/mobs/minecraft:zombie_villager.png', 20, 2),
(8, 'Skeleton', '/mobs/minecraft:skeleton.png', 20, 2),
(9, 'Creeper', '/mobs/minecraft:creeper.png', 20, 2),
(10, 'Slime', '/mobs/minecraft:slime.png', 20, 2),
(11, 'Enderman', '/mobs/minecraft:enderman.png', 20, 2),
(12, 'Witch', '/mobs/minecraft:witch.png', 20, 2),
(13, 'Glow Squid', '/mobs/minecraft:glow_squid.png', 20, 0),
(14, 'Chicken', '/mobs/minecraft:chicken.png', 20, 0),
(15, 'Cow', '/mobs/minecraft:cow.png', 20, 0),
(16, 'Horse', '/mobs/minecraft:horse.png', 20, 0),
(17, 'Donkey', '/mobs/minecraft:donkey.png', 20, 0),
(18, 'Llama', '/mobs/minecraft:llama.png', 20, 0),
(19, 'Polar Bear', '/mobs/minecraft:polar_bear.png', 20, 0),
(20, 'Stray', '/mobs/minecraft:stray.png', 20, 2),
(21, 'Drowned', '/mobs/minecraft:drowned.png', 20, 2),
(22, 'Cod', '/mobs/minecraft:cod.png', 20, 0),
(23, 'Salmon', '/mobs/minecraft:salmon.png', 20, 0),
(24, 'Squid', '/mobs/minecraft:squid.png', 20, 0),
(25, 'Wolf', '/mobs/minecraft:wolf.png', 20, 0),
(26, 'Parrot', '/mobs/minecraft:parrot.png', 20, 0),
(27, 'Panda', '/mobs/minecraft:panda.png', 20, 0),
(28, 'Ocelot', '/mobs/minecraft:ocelot.png', 20, 2),
(29, 'Pufferfish', '/mobs/minecraft:pufferfish.png', 20, 0),
(30, 'Tropical Fish', '/mobs/minecraft:tropical_fish.png', 20, 0),
(31, 'Dolphin', '/mobs/minecraft:dolphin.png', 20, 0),
(32, 'Mooshroom', '/mobs/minecraft:mooshroom.png', 20, 0),
(33, 'Goat', '/mobs/minecraft:goat.png', 20, 0),
(34, 'Frog', '/mobs/minecraft:frog.png', 20, 0),
(35, 'Fox', '/mobs/minecraft:fox.png', 20, 0),
(36, 'Strider', '/mobs/minecraft:strider.png', 20, 0),
(37, 'Ghast', '/mobs/minecraft:ghast.png', 20, 2),
(38, 'Zombified Piglin', '/mobs/minecraft:zombified_piglin.png', 20, 2),
(39, 'Magma Cube', '/mobs/minecraft:magma_cube.png', 20, 2),
(40, 'Piglin', '/mobs/minecraft:piglin.png', 20, 2),
(41, 'Turtle', '/mobs/minecraft:turtle.png', 20, 0),
(42, 'Hoglin', '/mobs/minecraft:hoglin.png', 20, 2),
(43, 'Husk', '/mobs/minecraft:husk.png', 20, 2),
(44, 'Axolotl', '/mobs/minecraft:axolotl.png', 20, 0),
(45, 'Cat', '/mobs/minecraft:cat.png', 20, 0),
(46, 'Pillager', '/mobs/minecraft:pillager.png', 20, 2),
(47, 'Guardian', '/mobs/minecraft:guardian.png', 20, 2),
(48, 'Blaze', '/mobs/minecraft:blaze.png', 20, 2),
(49, 'Wither Skeleton', '/mobs/minecraft:wither_skeleton.png', 20, 2),
(50, 'Vindicator', '/mobs/minecraft:vindicator.png', 20, 0),
(51, 'Ender Dragon', '/mobs/minecraft:ender_dragon.png', 20, 0),
(52, 'Elder Guardian', '/mobs/minecraft:elder_guardian.png', 20, 0),
(53, 'Wither', '/mobs/minecraft:wither.png', 20, 0),
(54, 'Villager', '/mobs/minecraft:villager.png', 20, 0),
(55, 'Trader Llama', '/mobs/minecraft:trader_llama.png', 20, 0),
(56, 'Cave Spider', '/mobs/minecraft:cave_spider.png', 20, 0),
(57, 'Zombie Horse', '/mobs/minecraft:zombie_horse.png', 20, 0),
(58, 'Ravager', '/mobs/minecraft:ravager.png', 20, 0),
(59, 'Sniffer', '/mobs/minecraft:sniffer.png', 20, 0),
(60, 'Shulker', '/mobs/minecraft:shulker.png', 20, 0),
(61, 'Mule', '/mobs/minecraft:mule.png', 20, 0),
(62, 'Tadpole', '/mobs/minecraft:tadpole.png', 20, 0),
(63, 'Player', '/mobs/minecraft:player.png', 20, 0),
(64, 'Evoker', '/mobs/minecraft:evoker.png', 20, 0),
(65, 'Piglin Brute', '/mobs/minecraft:piglin_brute.png', 20, 0),
(66, 'Allay', '/mobs/minecraft:allay.png', 20, 0),
(67, 'Bee', '/mobs/minecraft:bee.png', 20, 0),
(68, 'Endermite', '/mobs/minecraft:endermite.png', 20, 0),
(69, 'Snow Golem', '/mobs/minecraft:snow_golem.png', 20, 0),
(70, 'Wandering Trader', '/mobs/minecraft:wandering_trader.png', 20, 0),
(71, 'Warden', '/mobs/minecraft:warden.png', 20, 0),
(72, 'Camel', '/mobs/minecraft:camel.png', 20, 0),
(73, 'Iron Golem', '/mobs/minecraft:iron_golem.png', 20, 0),
(74, 'Phantom', '/mobs/minecraft:phantom.png', 20, 0),
(75, 'Silverfish', '/mobs/minecraft:silverfish.png', 20, 0),
(76, 'Skeleton Horse', '/mobs/minecraft:skeleton_horse.png', 20, 0),
(77, 'Giant', '/mobs/minecraft:giant.png', 20, 0),
(78, 'Armor Stand', '/mobs/minecraft:armor_stand.png', 20, 0),
(79, 'Zoglin', '/mobs/minecraft:zoglin.png', 20, 0),
(80, 'Vex', '/mobs/minecraft:vex.png', 20, 0),
(81, 'Illusioner', '/mobs/minecraft:illusioner.png', 20, 0);
