INSERT INTO structure (id, name, image, description) VALUES
(1, 'Mansion', '/structures/mansion.png', 'The Mansion structure'),
(2, 'Ancient City', '/structures/ancient_city.png', 'The Ancient City structure'),
(3, 'Jungle Pyramid', '/structures/jungle_pyramid.png', 'The Jungle Pyramid structure'),
(4, 'Village Desert', '/structures/village_desert.png', 'The Village Desert structure'),
(5, 'Village Taiga', '/structures/village_taiga.png', 'The Village Taiga structure'),
(6, 'Stronghold', '/structures/stronghold.png', 'The Stronghold structure'),
(7, 'Ruined Portal Mountain', '/structures/ruined_portal_mountain.png', 'The Ruined Portal Mountain structure'),
(8, 'Mineshaft', '/structures/mineshaft.png', 'The Mineshaft structure'),
(9, 'Swamp Hut', '/structures/swamp_hut.png', 'The Swamp Hut structure'),
(10, 'Ocean Ruin Cold', '/structures/ocean_ruin_cold.png', 'The Ocean Ruin Cold structure'),
(11, 'Village Snowy', '/structures/village_snowy.png', 'The Village Snowy structure'),
(12, 'Buried Treasure', '/structures/buried_treasure.png', 'The Buried Treasure structure'),
(13, 'Ruined Portal Desert', '/structures/ruined_portal_desert.png', 'The Ruined Portal Desert structure'),
(14, 'End City', '/structures/end_city.png', 'The End City structure'),
(15, 'Pillager Outpost', '/structures/pillager_outpost.png', 'The Pillager Outpost structure'),
(16, 'Ruined Portal', '/structures/ruined_portal.png', 'The Ruined Portal structure'),
(17, 'Village Plains', '/structures/village_plains.png', 'The Village Plains structure'),
(18, 'Ruined Portal Jungle', '/structures/ruined_portal_jungle.png', 'The Ruined Portal Jungle structure'),
(19, 'Mineshaft Mesa', '/structures/mineshaft_mesa.png', 'The Mineshaft Mesa structure'),
(20, 'Monument', '/structures/monument.png', 'The Monument structure'),
(21, 'Ruined Portal Nether', '/structures/ruined_portal_nether.png', 'The Ruined Portal Nether structure'),
(22, 'Village Savanna', '/structures/village_savanna.png', 'The Village Savanna structure'),
(23, 'Nether Fossil', '/structures/nether_fossil.png', 'The Nether Fossil structure'),
(24, 'Trail Ruins', '/structures/trail_ruins.png', 'The Trail Ruins structure'),
(25, 'Ruined Portal Ocean', '/structures/ruined_portal_ocean.png', 'The Ruined Portal Ocean structure'),
(26, 'Bastion Remnant', '/structures/bastion_remnant.png', 'The Bastion Remnant structure'),
(27, 'Igloo', '/structures/igloo.png', 'The Igloo structure'),
(28, 'Shipwreck', '/structures/shipwreck.png', 'The Shipwreck structure'),
(29, 'Desert Pyramid', '/structures/desert_pyramid.png', 'The Desert Pyramid structure'),
(30, 'Ocean Ruin Warm', '/structures/ocean_ruin_warm.png', 'The Ocean Ruin Warm structure'),
(31, 'Ruined Portal Swamp', '/structures/ruined_portal_swamp.png', 'The Ruined Portal Swamp structure'),
(32, 'Shipwreck Beached', '/structures/shipwreck_beached.png', 'The Shipwreck Beached structure'),
(33, 'Fortress', '/structures/fortress.png', 'The Fortress structure');
